const acData=[
    {
        name:"Blue Star 1.5 Ton 3 Star Split Inverter AC - White  (IE318YKU, Copper Condenser)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC1/3.png?raw=true",
        info:"1 Year Warranty on Product, 10 Years Warranty on Inverter Compressor and 5 Years Warranty on PCB",
        description:"All Functional Part of AC Other than Aesthetic Parts (Plastic Parts) are Covered in Warranty.",
        price: 35990,
    },
    {
        name:"Blue Star 2023 Model 1.5 Ton 3 Star Split Inverter AC with Wi-fi Connect - White  (IC318YNUS, Copper Condenser)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC2/3.png?raw=true",
        info:"1 Year Warranty on Product, 5 Years Warranty on PCB and 10 Years Warranty on Inverter Compressor",
        description:"All Parts, Excluding Air Filter, Front Grill & Plastic Parts (After Installation). The Warranty Covers Defective Materials and Workmanship From the Date of Purchase. Beyond the First Year of the Warranty Period",
        price: 37350,
    },
    {
        name:"Voltas 2023 Model 1.5 Ton 5 Star Split Inverter AC - White  (185V Vectra Elite(4503617), Copper Condenser)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC3/3.png?raw=true",
        info:"1 Year Warranty on Product and 10 Years Warranty on Compressor",
        description:"Warranty of the Product is Limited to Manufacturing Defects Only",
        price: 37900,
    },
    {
        name:"CARRIER 1 Ton 5 Star Split Inverter AC - White  (12K ESTER NEO EXi INVERTER R32 SPLIT AC_CAI12ES5R34F1, Copper Condenser)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC4/3.png?raw=true",
        info:"1 Year Warranty on Product, 5 Years Warranty on PCB and 10 Years Warranty on Compressor",
        description:"All Functional Part of AC and Compressor Other Than Aesthetic Parts (Plastic Parts)",
        price: 34900,
    },
    {
        name:"Hisense 2024 Model 1.5 Ton 3 Star Split Inverter AC - White  (AS-18TR4R3BP1/AS18TR4RI3BP1/AS18TR4RO3BP1, Copper Condenser)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC5/3.png?raw=true",
        info:"1 Year Comprehensive Warranty on Product, 5 Years Warranty on PCB and 10 Years Warranty on Compressor",
        description:"All Functional Parts of AC are Covered in Warranty",
        price: 29900,
    },
    {
        name:"Blue Star 2023 Model 1 Ton 3 Star Window AC - White  (WFB312LN, Copper Condenser",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC6/3.png?raw=true",
        info:"1 Year Warranty on Product and 5 Years Warranty on Compressor",
        description:"All functional Parts of AC Excluding Air Filters, Plastic Parts (Including IDU Panel and Louvre). For Details Refer User Manual",
        price: 27900,
    },
    {
        name:"LG 2023 Model Convertible 4-in-1 Cooling 1 Ton 5 Star Window Inverter HD Filter, Clean Filter Indicator AC with Wi-fi Connect - White  (PW-Q12WUZA, Copper Condenser)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC7/3.png?raw=true",
        info:"1 Year Warranty on Product, 5 Years on PCB and 10 Years on Compresso",
        description:"All Parts, Excluding the Grill and Plastic Parts. The Warranty Covers Defective Materials and Workmanship from the Date of Purchase. Beyond the First Year of the Warranty Period, Only the Compressor Repair will be Provided Free of Cost and When Necessary.",
        price: 61999,
    },
    {
        name:"CARRIER 1.5 Ton 5 Star Window AC - White  (18 K Estra Cx (5 Star) WRAC AC R32 / CAW18SC5R31F1, Copper Condenser)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC8/3.png?raw=true",
        info:"1 Year Warranty on Product and 5 Years on Compressor",
        description:"All Functional Part of AC and Compressor Other Than Aesthetic Parts (Plastic Parts) will Covered in Warranty",
        price: 34081,
    },
    {
        name:"Blue Star 2023 Model 1 Ton Portable Turbo AC - White  (PC12DB)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC9/3.png?raw=true",
        info:"1 Year Warranty on Product and 5 Years on Compressor",
        description:"In a world where comfort meets brilliant technology, the Blue Star Portable Turbo AC stands as a beacon of innovation. Elevate your living space, indulge in superior cooling, and bask in the convenience of features meticulously designed for your well-being. ",
        price: 39000,
    },
   
    {
        name:"Lloyd 1 Ton 3 Star Portable AC - White  (LP12B01TP, Copper Condenser)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/AC/AC10/3.png?raw=true",
        info:"1 Year Comprehensive Warranty From Lloyd",
        description:"All Parts",
        price: 39990,
    }
]
module.exports = { data: acData };