const acData=[
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price: 1,
    },
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price: 1,
    },
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price: 1,
    },
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price: 1,
    },
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price: 1,
    },
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price: 1,
    },
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price: 1,
    },
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price: 1,
    },
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price: 1,
    },
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price: 1,
    },
]