const fridgeData=[
    // {
    //     name:"Whirlpool 270 L Frost Free Triple Door Refrigerator  (Alpha Steel, FP 313D PROTTON ROY ALPHA STEEL (Z))",
    //     image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge1/1.png?raw=true",
    //     image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge1/2.png?raw=true",
    //     image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge1/3.png?raw=true",
    //     info:"1 Year Warranty on Product and 9 Years Warranty on Compressor",
    //     description:"Parts: Plastic, Glassware, Bulb or Tube. Any Accessories External to the Product. The Product is Not Used According to the Instructions Given in the Instructions Manual. Defects Caused by Improper Use as Determined by the Company Personnel. Modification or Alteration of Any Nature Made in the Electrical Circuitry or Physical Construction of the Set. Site (Where the Premises is Kept) Conditions That do not Confirm to the Recommended Operating Conditions of the Machine. The Serial Number is Removed, Altered or Obliterated from the Machine. Defects due to Cause Beyond Control like Lightening, Abnormal Voltage, Acts of God or While in Transit to the Service Centres or Purchaser's Residence",
    //     price:28790,
    // },
    // {
    //     name:"SAMSUNG 183 L Frost Free Single Door 4 Star Refrigerator  (Himalayan Poppy Red, RR20C1824HN/HL)",
    //     image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge2/01.png?raw=true",
    //     image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge2/2.png?raw=true",
    //     image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge2/3.png?raw=true",
    //     info:"1 Year Comprehensive Warranty on Product and 20 Years Warranty on Compressor",
    //     description:"All Parts Excluding Plastic Parts, Glassware, Bulb and Tube from the Date of Purchase Against Defective Material and Workmanship",
    //     price:18100 ,
    // },
    {
        name:"Haier 598 L Frost Free Triple Door Convertible Refrigerator  (Black White Glass, HRT-683KWG-P)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge3/Screenshot%202024-04-08%20110811.png?raw=true",
        info:"1 Year Warranty on Product and 10 Years Warranty on Compressor",
        description:"All Parts Excluding Plastic Parts, Glassware, Bulb and Tube from the Date of Purchase Against Defective Material and Workmanship",
        price: 94990,
    },
    {
        name:"Whirlpool 240 L Frost Free Triple Door Bottom Mount Refrigerator  (Wine Stream, FP 263D PROTTON ROY WN STRM -21445)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge4/3.png?raw=true",
        info:"1 Year on Product and 10 Years on Compressor From Whirlpool",
        description:"Warranty of the product is limited to manufacturing defects only.",
        price: 28450,
    },
    {
        name:"SAMSUNG 236 L Frost Free Double Door 2 Star Convertible Refrigerator with Digital Inverter with Display  (Camellia Purple, RT28C3922CR/HL)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge5/Screenshot%202024-04-08%20111201.png?raw=true",
        info:"1 year comprehensive warranty on the product, 20 years on compressor by the brand.",
        description:"All Parts Excluding Plastic Parts, Glassware, Bulb and Tube from the Date of Purchase Against Defective Material and Workmanship",
        price: 24690,
    },
    {
        name:"Haier 190 L Direct Cool Single Door 5 Star Refrigerator  (Dazzle steel, HED-205DS-P)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge6/3.png?raw=true",
        info:"1 Year Warranty on Product and 10 Years Warranty on Compressor",
        description:"All Parts Excluding Plastic Parts, Glassware, Bulb and Tube from the Date of Purchase, Against Defective Material and Workmanship",
        price: 15490,
    },
    {
        name:"LG 594 L Frost Free Side by Side Inverter Technology Star Refrigerator with with Hygiene Fresh+ and Smart ThinQ(WiFi Enabled)  (Matte Black, GC-B22FTQPL)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge7/3.png?raw=true",
        info:"1 Year Warranty on Product and 10 Years Warranty on Compressor from LG",
        description:"All Parts Excluding Plastic Parts, Glassware, Bulb and Tube from the Date of Purchase Against Defective Material and Workmanship",
        price: 90990,
    },
    {
        name:"SAMSUNG 550 L Frost Free French Door Bottom Mount Convertible Refrigerator  (Black Matt (Doi), RF57A5032B1/TL)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge8/3.png?raw=true",
        info:"1 year comprehensive warranty on product, 20 years on compressor, For all Refrigerators with Digital Inverter Compressors, sold on or after 1st Dec 2022 (All Refrigerator apart from Non-Digital Inverter Technology Direct Cool Models) the Warranty period on the Digital Inverter Compressor shall be revised from 10 years to 20 years.",
        description:"All Parts Excluding Plastic Parts, Glassware, Bulb and Tube from the Date of Purchase Against Defective Material and Workmanship.",
        price: 74990,
    },
    {
        name:"Haier 240 L Frost Free Double Door Top Mount 2 Star Refrigerator  (Moon Silver, HEF-252EGS-P)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge9/3.png?raw=true",
        info:"1 Year Warranty on Product and 10 Years Warranty on Compressor",
        description:"All Parts Excluding Plastic Parts, Glassware, Bulb and Tube from the Date of Purchase Against Defective Material and Workmanship",
        price: 20990,
    },
    {
        name:"LG 655 L Frost Free Side by Side Refrigerator with Smart Inverter Compressor, Express Freeze & Multi Air-Flow  (Dazzle Steel, GL-B257HDSY)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridges/fridge10/3.png?raw=true",
        info:"1 Year Warranty on Product and 10 Years Warranty on Compressor (T&C)",
        description:"All Parts Excluding Plastic Parts, Glassware, Bulb and Tube from the Date of Purchase Against Defective Material and Workmanship",
        price: 72990,
    },
];
module.exports = { data: fridgeData };