const fridgeData=[
    {
        name:"Whirlpool 270 L Frost Free Triple Door Refrigerator  (Alpha Steel, FP 313D PROTTON ROY ALPHA STEEL (Z))",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridge/fridge1/Screenshot%202024-04-07%20231532.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridge/fridge1/Screenshot%202024-04-07%20231615.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/fridge/fridge1/Screenshot%202024-04-07%20231654.png?raw=true",
        info:"1 Year Warranty on Product and 9 Years Warranty on Compressor",
        description:"Parts: Plastic, Glassware, Bulb or Tube. Any Accessories External to the Product. The Product is Not Used According to the Instructions Given in the Instructions Manual. Defects Caused by Improper Use as Determined by the Company Personnel. Modification or Alteration of Any Nature Made in the Electrical Circuitry or Physical Construction of the Set. Site (Where the Premises is Kept) Conditions That do not Confirm to the Recommended Operating Conditions of the Machine. The Serial Number is Removed, Altered or Obliterated from the Machine. Defects due to Cause Beyond Control like Lightening, Abnormal Voltage, Acts of God or While in Transit to the Service Centres or Purchaser's Residence",
        price:28790,
    },
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price:1 ,
    },
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price: 1,
    },
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price: 1,
    },
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price: 1,
    },
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price: 1,
    },
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price: 1,
    },
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price: 1,
    },
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price: 1,
    },
    {
        name:"",
        image1:"",
        image2:"",
        image3:"",
        info:"",
        description:"",
        price: 1,
    },
]