const tvData=[
    {
        name:"SAMSUNG Crystal Vision 4K iSmart with Voice Assistant 138 cm (55 inch) Ultra HD (4K) LED Smart Tizen TV 2023 Edition with IOT Sensors for Light & Camera  (UA55CUE70AKLXL)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV1/3.png?raw=true",
        info:"1 Year Comprehensive Warranty on Product and 1 Year Additional Warranty",
        description:"All Manufacturing Defects",
        price: 45990,
    },
    {
        name:"Mi X Series 138 cm (55 inch) Ultra HD (4K) LED Smart Google TV 2023 Edition with 4K Dolby Vision | HDR 10 | Dolby Audio |,DTS X | DTS Virtual: X | Vivid Picture Engine",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV2/3.png?raw=true",
        info:"1 Year Warranty on Product and 2 Years Warranty on Panel",
        description:"All Manufacturing Defects",
        price: 37999,
    },
    {
        name:"TOSHIBA M550MP 139 cm (55 inch) QLED Ultra HD (4K) Smart Google TV With Full Array Local Dimming, Power Bass woofer, and HSR 120 Mode  (55M550MP)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV3/3.png?raw=true",
        info:"4 Years Comprehensive Warranty for orders from 15thFebruary 2024. You will enjoy 4 years warranty on this product based onyour invoice and the date mentioned on invoice",
        description:"All Manufacturing Defects",
        price: 40990,
    },
    {
        name:"Hisense Tornado 164 cm (65 inch) Ultra HD (4K) LED Smart Google TV 2023 Edition with Built-in JBL Soundbar, 25W Subwoofer and 120 High Refresh Rate Mode  (65A7K)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV4/3.png?raw=true",
        info:"2 Years Comprehensive Warranty",
        description:"All Manufacturing Defects",
        price: 49999,
    },
    {
        name:"SONY Bravia X74L 138.8 cm (55 inch) Ultra HD (4K) LED Smart Google TV  (KD-55X74L)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV5/3.png?raw=true",
        info:"2 Years Comprehensive Warranty",
        description:"The Sony LED Smart Android TV is powered by an X1 4K processor to deliver exceptional quality visuals. The Dolby Audio system is sure to provide immersive audio so you can have a complete audio experience in the comfort of your home",
        price: 57990,
    },
    {
        name:"Mi X Series 163.9 cm (65 inch) Ultra HD (4K) LED Smart Google TV 2023 Edition with 4K Dolby Vision | HDR 10 | Dolby Audio |,DTS X | DTS Virtual: X | Vivid Picture Engine",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV6/3.png?raw=true",
        info:"1 Year Warranty on Product and 2 Years Warranty on Panel",
        description:"All Manufacturing Defects",
        price: 60000,
    },
    {
        name:"SONY Bravia X74K 138.8 cm (55 inch) Ultra HD (4K) LED Smart Google TV  (KD-55X74K)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV7/3.png?raw=true",
        info:"1 Year Comprehensive Warranty",
        description:"All Manufacturing Defects",
        price: 52490,
    },
    {
        name:"LG UR7500 139 cm (55 inch) Ultra HD (4K) LED Smart WebOS TV 2023 Edition with a5 AI Processor 4K Gen6 and 60Hz Refresh Rate, Magic remote capability  (55UR7500PSC)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV8/3.png?raw=true",
        info:"1 Year Product Warranty Applicable",
        description:"All Manufacturing Defects",
        price: 45990,
    },
    {
        name:"Panasonic 139 cm (55 inch) Ultra HD (4K) LED Smart Google TV 2023 Edition  (TH-55MX660DX)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV9/3.png?raw=true",
        info:"1 Year Warranty on Product",
        description:"All Manufacturing Defects",
        price: 42990,
    },
    {
        name:"Sansui 140 cm (55 inch) Ultra HD (4K) LED Smart Android TV with Dolby Audio and DTS (Mystique Black)  (JSW55ASUHD)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/TV/TV10/3.png?raw=true",
        info:"1 Year Warranty on Product",
        description:"Boasting an enhanced audio-visual experience, the Sansui JSW55ASUHD 139.7 cm (55) UHD Smart TV is an ideal addition to your home. With its Dolby Audio and DTS Studio Sound, this TV offers a captivating stereo system.",
        price: 32900,
    }
];
module.exports = { data: tvData };