const gift1Data=[
    {
        name:"Femora Borosilicate Glass Salad Bowl Borosilicate Glass Mixing Bowl 400 ml  (Pack of 1, White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/bowl/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/bowl/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/bowl/3.png?raw=true",
        info:"Type: Salad Bowl Made of : Borosilicate Glass Microwave Safe Pack of 1 Capacity: 400 ml",
        description:"You can cook, serve and store in one cookware without having to use a single pot or pan. Femora mixing bowls are the perfect choice to store food and cook food in the microwave/oven. Pop the leftovers in the fridge or the freezer without the need to transfer them to a new container. The mixing bowl comes with a 1 Year replacement warranty against thermal shock",
        price: 299,
    },
    {
        name:"H&M Store Carbon Steel Bread Mould 2  (Pack of 2)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/bread%20mould/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/bread%20mould/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/bread%20mould/3.png?raw=true",
        info:"Made of Carbon Steel OTG Safe Microwave Safe Freezer Safe",
        description:" Make delicious baked goods at home with this non-stick carbon-steel square and round cake mould and bread mould from H&M store. The bread mould features a square shape and deep walls for baking generously sized loaves of homemade cakes for slicing and sharing with family and friends. In addition to favorite flavored cakes like vanilla, chocolate, pineapple, strawberry, etc, the mold can also be used to bake small batches of lasagna, casseroles, pie, and more.",
        price: 398,
    },
    {
        name:"SCIVER Aluminium Cake Mould 3  (Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/cake%20mould/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/cake%20mould/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/cake%20mould/3.png?raw=true",
        info:"Made of Carbon Steel OTG Safe Microwave Safe Freezer Safe",
        description:"  Aluminum 5,6 & 7 inches Diameter and 2.25 inch Height Round Cake Mould for OVENS. Setof 3 Pieces (5 inch=300 grams) (6 inch=500 gram) (7 inch 750 gram) for cake uses.You can enjoy the benefits of mould by making ice cream in your home fridge.Easy Wash and Re-Use moulds After used you can easy clean.",
        price: 448,
    },
    {
        name:"Flipkart SmartBuy Kitchenware Fruit Vegetable Chopping Board Wooden Cutting Board  (Brown Pack of 1 Dishwasher Safe",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/chopping%20board/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/chopping%20board/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/chopping%20board/3.png?raw=true",
        info:"Width x Height: 9 inch x 12 inch Rectangle Shaped Dishwasher Safe Type: Cutting Board Material: Wooden",
        description:"Cutting Board, which is used for making your work easy, will also prevent your kitchen platform from scratches and cut marks. Easy Chopping and Storage Made from wood, this stripped cutting board is sturdy and perfect for regular use. As this board comes with a steel hook.",
        price: 319,
    },
    {
        name:"Coozico Pack of 2 Glass Coffee Mug Set of 2 Use for Home and Office Big Tea Glass Cup  (Clear, Cup)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/coffee%20mug/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/coffee%20mug/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/coffee%20mug/3.png?raw=true",
        info:"Cup   Glass   Pack of: 2   Capacity: 450 ml",
        description:" Starts a wonderful Day with our mugs. Beautiful addition to any cafe, restaurant, pub and definitely to your own home. Can be used for Capucinno cups, Lungo cups, Macchiato, Latte, Espresso cups, Demitasse cups, Tea, smoothie and juice. A hot cup of coffee or soothing tea only is as good as the mug you drink it from. To get the full taste and experience of your morning or evening beverage, you need a cup that is both well-made and durable. ",
        price: 399,
    },
    {
        name:"HUMBLE KART Manual Food Chopper, Compact & Powerful Hand Held Vegetable Chopper/Blender to Chop Fruits/Vegetables/Nuts/Herbs/Onions/Garlic (Chopper 1000ML) Vegetable & Fruit Chopper  (1 Chopper)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/food%20chopper/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/food%20chopper/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/food%20chopper/3.png?raw=true",
        info:"Blade Material: Steel Made of: Plastic Type Chopper Ideal For: Vegetable & Fruit",
        description:"ts premium transparent chopper which helps you to How to Become a Professional in Chopping? The answer is simple – bring in Amar Impex Vegetable Chopper! The handy tool is ready to use in just a few steps: 1)Place the food container bowl on your kitchen counter top. 2)Keep the stainless steel 5-blades’ set in the center of the container",
        price: 248,
    },
    {
        name:"Refulgix USB Rechargeable Mini Portable Hand Fan With Noise Cancelling Design Battery Operated Personal Fan for Women, Makeup, Office, Travel, USB Fan  (Blue)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/hand%20fan/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/hand%20fan/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/hand%20fan/3.png?raw=true",
        info:" Refulgix USB Rechargeable Mini Portable Hand Fan With Noise Cancelling Design Battery Operated Personal Fan for Women, Makeup, Office, Travel, USB Fan (Black)",
        description:"Mini Portable Fan is equipped with a powerful brushless motor that delivers strong, consistent airflow, making it perfect for hot summer days and stuffy indoor spaces. Large Blades & 3-Speeds: This fan features large blades that are designed to move more air with less noise. Additionally, it has three speed settings to choose from, so you can adjust the airflow to your preference. Detachable To Clean: The cover of the fan is detachable,",
        price: 499,
    },
    {
        name:"Jany creation Plastic Dessert Bowl 6 Pcs Icecream cups set  (Pack of 6, Multicolor)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/icecream%20bowl/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/icecream%20bowl/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/icecream%20bowl/3.png?raw=true",
        info:" Model Number JC-ICE Model Name 6 Pcs Icecream cups set Capacity 250 ml Freezer Safe Yes Lid Included No  Scratch Resistant  Yes  Stackable  No  Sales Package  6 BowlNet Quantity6 Dimensions Weight 200 g Warranty Warranty Summary N/A Covered in Warranty N/A Not Covered in Warranty   N/A   Warranty Service Type   N/A",
        description:"Serve delicious and yummy deserts that you have prepared for your guests in the most stylish way by using our wide range of dessert bowls. The elegant design and impressive looks add delight to your kitchenware, which will surely earn you compliments for your classy choice in dining.",
        price: 195,
    },
    {
        name:"IndusBay Microwave sage Toughened Glass Round Casserole Serve Bowl Containers Borosilicate Bowl with Lid, 900 ML Serve Casserole  (1 L)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/serve%20bowl/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/serve%20bowl/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/serve%20bowl/3.png?raw=true",
        info:"Type: Casserole  Made of: Borosilicate Glass  Microwave Safe  Pack of: 1  Lid Included  Capacity: 1 L  Casserole Type: Serve Casserole",
        description:"Made of borosilicate glass. Unlike plastic and melamine will not leech chemicals into your food even over repeated usage Will retain 100 percent clarity, unlike regular soda lime glass will not turn milky or cloudy with time Can be safely used in the microwave, oven, fridge, freezer and dishwasher Non porous glass will not absorb stains or odors Color: Transparent, Material: Glass Package Contents: Package Contents: 1-Piece Round Glas Casserole and 1-Piece Lid (900 - ML)",
        price: 469,
    },
    {
        name:"DeoDap Multipurpose 13-in-1 Jumbo Manual Vegetable and Fruit Chopper Cutter Grater Slicer, Dicer, Fruit Slicer Vegetable & Fruit Grater & Slicer",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/vegetable%20cutter/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/vegetable%20cutter/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/0-500/vegetable%20cutter/3.png?raw=true",
        info:"Blade Material: Stainless Steel Made of: Plastic  Type: Grater & Slicer Ideal For: Vegetable & Fruit Dishwasher Safe",
        description:"Avoid the hassle and inconvenience of using different tools such as knives, peelers, shredders and cutting boards for your cutting and chopping needs in the kitchen. The Quick vegetable Dicer is the perfect solution to all cutting, chopping, dicing, slicing, peeling and shredding tasks in your kitchen. Featuring a unique design with easy operation, you can perform a large number of kitchen actions on this dicer with ease and safety.",
        price: 445,
    },
];
module.exports = { data:gift1Data};