const gift2Data=[
    {
        name:"iVBOX MAX-PRO Appam Pan Heavy-Weight Non-Stick appe Paniyarakkal Maker With Glass Lid with Lid 1 L capacity 24 cm diameter  (Aluminium, Non-stick)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/500-1000/appa%20maker/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/500-1000/appa%20maker/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/500-1000/appa%20maker/3.png?raw=true",
        info:"Made of: Aluminium Type: Paniarakkal Non-stick Lid Included Capacity: 1 L Diameter: 24 cm",
        description:"  Brand  iVBOX  Model Name  MAX-PRO Appam Pan Heavy-Weight Non-Stick appe Paniyarakkal Maker With Glass Lid Model Number Max-pro_appamGlass Color Silver Capacity 1 L Type Paniarakkal Induction Bottom Material Aluminium   Lid Included   Yes",
        price: 619,
    },
    {
        name:"riddhi enterprises Riddhi 100% copper Peacock Design Copper Water Bottle combo pack of 2 1000 ml Bottle  (Pack of 2, Copper, Copper)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/500-1000/copper%20bottle/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/500-1000/copper%20bottle/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/500-1000/copper%20bottle/3.png?raw=true",
        info:"Made of: Copper Bottle Type: Bottle Capacity: 1000 ml Pack of: 2",
        description:" Copper is an essential trace element that is vital to the health of all living things In humans, copper is essential to the proper functioning of organs and metabolic processes. The human body has complex homeostatic mechanisms which attempt to ensure a constant supply of available copper, while eliminating excess copper whenever this occurs. ",
        price: 1000,
    },
    {
        name:"Larah by Borosil Pack of 13 Opalware Fauna Dinner Set Dinner Set  (White, Green, Microwave Safe)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/500-1000/dinner%20set/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/500-1000/dinner%20set/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/500-1000/dinner%20set/Screenshot%202024-04-11%20231341.png?raw=true",
        info:"Made of: Opalware Sales Package: Full Plate, Mini Serving Bowl, Mini Veg Bowl  Pack of: 13  Microwave Safe  Diameter: Full Plate 10 inch, Mini Bowl 3.9 inch, Serving Bowl 7 inch, Weight: 2.77 Kg",
        description:"Blending beauty with functionality, the Borosil Larah 13-piece opal ware dinner set is an elegant way to serve dinner to your family or guests. You can set out a variety of dishes with the help of this dinner set, as it includes four full plates, eight mini bowls, and one serving bowl. Borosil, a well-established company, ",
        price: 850,
    },
    {
        name:"Glen Electric Egg Boiler Machine SA 3040 Egg Cooker  (Grey, 7 Eggs)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/500-1000/egg%20cooker/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/500-1000/egg%20cooker/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/500-1000/egg%20cooker/3.png?raw=true",
        info:"Cooking Modes: egg boiler, egg boiler machine, Electric Egg boiler, egg boiler electric  Power Consumed: 350 W  Automatic Shut-off  Weight: 0.75 kg",
        description:"The Glen 3040 Egg Boiler is a compact appliance that allows hard to soft boiling of eggs. It can boil 7 eggs at a time. It has a poaching cup that is safe for cooking. This egg boiler also has automatic off feature that cuts off the supply after the water is finished. It is an ideal appliance for homes and hostels.",
        price: 760,
    },
    {
        name:"Zulay Kitchen Electric Coffee Beater/ Dry Bean Spice Mill Maker Grinder Mixer SS Machine_S4G8Y 3 Cups Coffee Maker  (Multicolor)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/electric%20coffee%20beater/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/electric%20coffee%20beater/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/electric%20coffee%20beater/Screenshot%202024-04-11%20230740.png?raw=true",
        info:"Type: Drip Coffee Machine  Capacity: 2 Cups  Power Consumption: 200 W",
        description:"Coffee Grinder Electric,200W Powerful Spice Grinder, Espresso Grinder Herb Grinder Coffee Bean Grinder Electric for Spices, Herbs, Nuts with Brush, One Touch Push-Button Control Multiple Purposes: Multi-function grinder is suitable for grains, beans, seasonings.",
        price: 900,
    },
    {
        name:"NL Traders Plastic fruit juicer Electric Juice Maker Machine for Fruits and Vegetables Hand Juicer Hand Juicer  (Multicolor)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/electric%20juice%20maker/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/electric%20juice%20maker/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/electric%20juice%20maker/3.png?raw=true",
        info:" Brand Clairbell ModelNumberAYY_483Y_RECHARGEABLE PORTABLE USB JUICER BOTTLE SLECTRIC MIXER BLENDER GRINDER Material Plastic Capacity 400 ml Color Multicolo",
        description:"NL TRADERS Juice Maker Machine Built-in stainless-steel blade, effortless and time-saving, one key operation, convenient to use(Colour Will Be Send As Per Availability. Portable & Convenient to Charge: This little body light weight design is easy for you carry it to school,office,parks,camping, anywhere you want to. and it also convenient for charge by power bank, laptop, computer, car or other usb devices",
        price: 800,
    },
    {
        name:"Kingdom Facial Steamer Steamer for Cold & Cough, Vapourizer Vaporizer  (White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/facial%20steamer/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/facial%20steamer/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/facial%20steamer/Screenshot%202024-04-11%20230133.png?raw=true",
        info:"Type: Facial Steame",
        description:"EC grade 99.9% copper thimble. Usages : Inhalation , Soothes (Balm Effect) , Aroma Therapy & Ayurvedic Treatments , Facial Steam Bath , Before Manicure/ Pedicure , For Men : Softens Beards for Smooth and Clean Shave.",
        price: 1000,
    },
    {
        name:"Viktaay Crafts India Ceramic Serving Bowl Dinner Serving Casserole Donga Bowls Set of 3 for 4 People 1000ml, 600ml, 300ml.  (Pack of 3, Multicolor)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/serving%20bowl/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/serving%20bowl/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/serving%20bowl/3.png?raw=true",
        info:"Type: Serving Bowl Set  Made of : Ceramic Microwave Safe Pack of 3 Capacity: 1900 ml",
        description:"These Elegant Ceramic Serveware Bowls Makes For Essential Kitchen Accessories. Package Contents: Big bowl: dia-15.5x8.5 cm, vol -1000 ml, Medium bowl : dia-13x7cm, vol -600 ml, Small bowl : dia-11x6 cm, vol -300 ml. MATERIAL : Ceramic ; COLOR : Blue & Yellow; Product is Microwave and Dishwasher Safe and Lead free. This good quality stoneware product is food grade. ARDVAN INDIA picks & brings the very best of Indian artistry & craftsmanship",
        price: 916,
    },
    {
        name:"VibeX XVI-552DC-Extra Bass Headphones Wired Headset  (Classic White, On the Ear)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/wired%20headset/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/wired%20headset/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/wired%20headset/3.png?raw=true",
        info:"With Mic:Yes Connector type: 3.5 mm Flatwire: Stays tangle free even in your pocket",
        description:"XB450 Wired Headset Extra Bass On-Ear Headphone XB450 with 3.5mm Jack & in-Built Mic for Phone Calls & Tangle Free Cable Compatible with All Mobile Phones Makes sure rich bass is never missed out on. Providing excellent depth, the headphones ensure a pleasurable listening experience.",
        price: 881,
    },
    {
        name:"EVETIS Automatic 1L Portable Yogurt Making Machine Stainless Steel Container Dahi Maker Yogurt Maker  (Multicolor)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/yogurt%20making%20machine/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/yogurt%20making%20machine/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/500-1000/yogurt%20making%20machine/3.png?raw=true",
        info:"Yogurt Maker Usage Type: ELECTRIC Material: Stainless Steel, STEEL, Food Grade ABS PlasticPower Requirement: 220-240 v, 50HZ",
        description:" 1. Electric Automatic Yogurt Maker Mini Portable Yogurt Making Machine Stainless Steel Container with Lid Kitchen Appliance Yogurt Making Method 1. Disinfection Method:Flush the yogurt cup and yogurt cap with just boiled water for more than 1 minutes to sterillize them. Remark: only disinfect the yogurt cup and cap with boiled water but the upper cover and body of machine. ",
        price: 750,
    },
];
module.exports = { data:gift2Data};
