const gift3Data=[
    {
        name:"boAt Stone 350 10 W Bluetooth Speaker  (Blue, Mono Channel)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/bluetooth%20speaker/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/bluetooth%20speaker/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/bluetooth%20speaker/Screenshot%202024-04-11%20233723.png?raw=true",
        info:"Power Output(RMS): 10 W  Battery life: 12 hrs  Bluetooth Version: 5 Wireless range: 10 m Wireless music streaming via Bluetooth IPX7: Splash and Sweat Shield  Multiple Connectivity: BT, TF Card and AUX",
        description:"Its time to enjoy a seamless playback experience courtesy boAt Stone 350 10W portable wireless speaker. The speaker comes equipped with 1.96 dynamic drivers for an immersive stereo experience. It supports instant wireless connectivity with Bluetooth v5.0. The speaker pumps out nonstop audio for up to 12 hours on a single full charge.",
        price: 1699,
    },
    {
        name:"IMMUTABLE Smart Desk Fan with Mist Spray,LED Night Light, Battery iuyc9 Smart Desk Fan with Mist Spray,LED Night Light, Battery iuyc9 USB Air Cooler  (Multicolor)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/desk%20fan/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/desk%20fan/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/desk%20fan/Screenshot%202024-04-11%20234433.png?raw=true",
        info:" Sales Package 1 X FAN Input Power 25 W Light Color BLUE Charging Time 2 min Inbuilt Battery No W x H x D  10.2 cm x 27.7 cm  Weight  920 g  Other Dimensions  27.7 x 21.8 x 10.2 cm",
        description:" Built-in 1500mAh lithium battery and USB port,make the small Silent cooling fan easy to be charged.Coming with a type C USB charging cable,fully charged around 2 hrs,and wireless working time 2-6hrs.Around 6hrs working time only for fan function,around 2hrs working time for fan + misting + LED night light functions",
        price: 1500,
    },
    {
        name:"KYTONE Electric Food Chopper, 2L 8-Cup Stainless Steel Bowl Kitchen Mini Food Processor for Meat Vegetables Fruits or Nuts, 700w 4bi-Level Blades ",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/electric%20food%20chopper/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/electric%20food%20chopper/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/electric%20food%20chopper/Screenshot%202024-04-11%20235454.png?raw=true",
        info:"Blade Material: Stainless Steel Made of: Stainless Steel Type: Chopper Ideal For: Vegetable & Fruit Dishwasher Safe Electric",
        description:"This food processor is equipped with 4 stainless steel blades and 2 speed modes to choose from. You can mince, grind, mix, mix, and mince various ingredients, such as onions, meat, ham, garlic, onion, and small herbs. The electric food chopper comes with 700w real power, which is more efficient and faster than the manual food chopper.",
        price: 1476,
    },
    {
        name:"BAJAJ HB 20 300 W Hand Blender  (Green)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/hand%20blender/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/hand%20blender/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/hand%20blender/Screenshot%202024-04-11%20235052.png?raw=true",
        info:"  Sales Package  Motor||1N Stem||Instruction Manual||Warranty Card  Model  HB 20  Body Material    Blade Material Stainless Steel Lock System Turn and lock mechanism   Blending   Yes   Stirring   Yes   Frequency   50 Hz Safety Featurer  Turn and lock mechanism",
        description:"Bajaj HB 20 Hand Blender is designed with 300 Watts silent DC motor that ensures low noise level and hassle free blending. It comes with easy turn and lock mechanism for locking and detaching for easy to use and clean for your convenience. Bajaj HB 20 hand blender comes with ergonomically designed push button switch for convenient and safe operation.",
        price: 1249,
    },
    {
        name:"PHILIPS GC 1011 1200 W Steam Iron  (Blue)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/iron/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/iron/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/iron/Screenshot%202024-04-11%20234903.png?raw=true",
        info:"Spray: Yes Soleplate Type: Linished, Aluminium",
        description:"Everything that you wear will look crisp and new when you iron them using this steam iron from Philips. It features a thin soleplate for better heating and its vent design ensures that the steam is uniform across your clothes.",
        price: 1300,
    },
    {
        name:"DELL KM3322W Keyboard & Mouse Combo, Anti-fade & Spill-resistant Keys Wireless Multi-device Keyboard  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/keyboard%20%20mouse%20combo/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/keyboard%20%20mouse%20combo/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/keyboard%20%20mouse%20combo/Screenshot%202024-04-11%20234629.png?raw=true",
        info:"For Desktop, Laptop, AIOCase Material: Plastic  Size: Standard Interface: Wireless  Multimedia Keys",
        description:"Dell USB Wireless Keyboard and Mouse Set- KM3322W, Anti-Fade & Spill-Resistant Keys, up to 36 Month Battery Life, 3Y Advance Exchange Warranty, Black",
        price: 1249,
    },
    {
        name:"XERGY 20 Bonsai Tree Light,Fairy Light Tree Lamp with 108 LED Lights ,USB/Battery Table Lamp  (35 cm, Gold)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/light%20tree%20lamp/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/light%20tree%20lamp/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/light%20tree%20lamp/3.png?raw=true",
        info:"Color: Gold Power Source: USB, Non-Rechargeable Battery  W x H: 10 cm x 35 cm",
        description:"20 Bonsai Tree Light - Fairy Light Spirit Tree Lamp with 108 LED Lights - DIY Artificial Tree Lamp, USB/Battery Touch Switch, Deco of Children's Room, Bedroom, Living Room, Party WeddingModel Name 20Bonsai Tree Light,Fairy Light Tree Lamp with 108 LED Lights ,USB/Battery",
        price: 1000,
    },
    {
        name:"caresmith CS356 Charge Boost Massage Gun Massager  (Jet Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/massager/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/massager/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/massager/Screenshot%202024-04-11%20234234.png?raw=true",
        info:"Type: Full Body (Hammer, Tapping) Power Source: Battery Operated Massager Method: Percussion Color: Jet Black",
        description:"Say goodbye to muscle soreness with the all new Caresmith Charge Boost Massage Gun! Our body massager for pain relief is a premium percussion massager which features 6 speed levels and easy USB-C charging for a strong massaging experience! The advance full body & back massager gun dives deep into the muscle rectifying the pain and",
        price: 1498,
    },
    {
        name:"OTC Indian Chapati Electric/Roti/Maker with 2 year Warranty DN-13 Roti and Khakra Maker",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/roti%20maker/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/roti%20maker/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/roti%20maker/Screenshot%202024-04-11%20235249.png?raw=true",
        info:"  Width 10 cm Height 12 cm Weight 1 kg Plate Diameter 20 cm",
        description:"Portable Auto Roti Making Machine, Nonstick Alluminium Tawas, S.Steel Body, Double Thermostat Temp Control, Shock-Proof Insulated, No Roller Pin (Belan) Required - Ideal For Making Crisp Rotis, Parathas, Papads, Saves Time And Energy,Rolls And Cook Chapti In Less Than A Minute,Save Cooking Oil ,Fuel,Money.A Great Boon To Working And Housewives.Non Stick Cooking Reduces Calories Intake, Thermostatically Controlled,Makes Crispy Khakhras,Also Makes Rotis From Jawar,Bajra Maize Rice Flour Etc",
        price: 1090,
    },
    {
        name:"Aloof Unicorn Night Light, 16 Color Rechargeable Kids Night Light Cute Bedroom Night Lamp  (16.8 cm, Warm Yellow)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/unicorn%20night%20lamp/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/unicorn%20night%20lamp/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/gift%20voucher/1000-1500/unicorn%20night%20lamp/Screenshot%202024-04-11%20234023.png?raw=true",
        info:"Color: Multicolor  Power Source: USB  W x H: 9.4 cm x 16.8 cm With Shade Features: Speaker",
        description:"Enchanting Design: The ALOOF Children's Cute Lamp boasts a delightful UNICORN Shaped Night Light design, crafted from soft and safe silicone, making it an appealing and huggable accessory for any child's bedroom. • Versatile Illumination: With a 7-color switching mode, this Cute Night Light allows children to choose their preferred color,",
        price: 1100,
    },
];
module.exports = { data:gift3Data};
