const cameraData=[
    {
        name:"Canon EOS 200D II DSLR Camera EF-S18-55mm IS STM  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c1/3.png?raw=true",
        info:"2 Year Warranty (1 year standard warranty + 1 year additional warranty from the date of purchase made by the customer.)",
        description:" Is photography one of your passions? Bring home this EOS 200D II from Canon. This is Canon’s lightest DSLR that features a vari-angle LCD touch screen. It features a 24.1-megapixels APS-C CMOS sensor and a DIGIC 8 processor that capture stunning images. The EOS 200D II also has a lot of other features that make everyday photography a lot easier.",
        price: 55990,
    },
    {
        name:"FUJIFILM Instax Mini 11 Instant Camera  (Purple)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c2/3.png?raw=true",
        info:"1 Year Warranty",
        description:"  If you are looking for an instant camera to capture your favourite moments, then this Fujifilm Instax Mini 11 is ideal for you. It comes with a pull-out selfie lens so that you can click beautiful selfies and great close-up shots. Moreover, you can capture and print your pictures on high-quality mini-films that are as big as a credit card. Furthermore, you can customize the shutter button to suit your style.",
        price: 5999,
    },
    {
        name:"NIKON Z 50 Mirrorless Camera Body with 16-50mm & 50-250mm Lenses  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c3/3.png?raw=true",
        info:"2 Year Warranty",
        description:"Small but mighty, simple but powerful a Z series camera for creating amazing online stories. Professional looking stills, 4K Ultra HD videos, slow motion, time-lapse and more. Wi-Fi  and Bluetooth enabled, plus in-camera video editing. Beautifully designed with a comfortable grip, flip-down touchscreen LCD, smart button layout, extended Electronic Viewfinder and travel-proof ruggedness.,suitable_for-Enthusiast,-,sensor_type-APS-C size/DX-format,",
        price: 87990,
    },
    {
        name:"SONY ZV-E10L Mirrorless Camera Body with 1650 mm Power Zoom Lens Vlog Camera  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c4/3.png?raw=true",
        info:"2 Year Warranty. Warranty of the Product Is Limited to Only Manufacturing Defects on Camera Body",
        description:"  Capture more of your world.Professional-looking vlogs are easy with the ZV-E10, thanks to interchangeable lenses that capture the world however you choose to see it. Watch the video below to discover some of the many creative possibilities.The ZV-E10's image-stabilisation system can shoot smooth, clean video footage even when you're walking6. Another feature, Face Priority Auto Exposure (AE), will automatically brighten the lighting of your face.",
        price: 61489,
    },
    {
        name:"SONY Alpha ILCE-7M3 Full Frame Mirrorless Camera Body Only Featuring Eye AF and 4K movie recording  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c5/3.png?raw=true",
        info:"2 Year Warranty.Warranty of the Product is Limited to Only Manufacturing Defect on Camera Body and Lens.",
        description:" Bring home this Sony Mirrorless Camera Body and enjoy clicking dramatically enhanced images that are of high quality. Take aim with high AF performance and always keep your subject in the frame. The option of making videos using the 10fps continuous shooting feature and the ability to shoot 4K HDR videos that are more realistic will make it difficult for you to stop and lay this camera down.",
        price: 127489,
    },
    {
        name:"NIKON Z5 Mirrorless Camera 24-200 mm  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c6/3.png?raw=true",
        info:"2 Year Warranty",
        description:"Your full-frame mirrorless journey starts here.Push the limits of your creativity with Z 5, an innovative full frame mirrorless camera built around Nikon s revolutionary Z mount. Compact yet powerful, simple yet sophisticated, it s ready to grow with you. Whatever your skill level, the Z 5 delivers detailed imagery, precision autofocus and the tools you need to be as creative as possible.Harness the entire view of expansive full frame lenses, and capture over 50% more image area than crop-sensor cameras. Z 5 s 24.3",
        price: 142299,
    },
    {
        name:"FUJIFILM Instax Mini 9 Instant Camera  (Blue)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c7/3.png?raw=true",
        info:" Only Repair",
        description:"If you want to materialise your photos as soon as you click them, then you can use this compact camera by Fujifilm. It comes with a selfie mirror which lets you know the framing so that you can use it to enhance your selfies. You can also take close-up photos (up to 35 cm) with it. What’s more, it has a high-key mode which sets the brightness as per your surrounding so that your photos look vibrant and lovely.",
        price: 4999,
    },
    {
        name:"Canon EOS R6 Mark II Mirrorless Camera Body with 24-105mm USM Lens  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c8/3.png?raw=true",
        info:"2 Years Warranty",
        description:"The 6ame ChangeR.Seize the best of videography and photography with the EOS R6 Mark II. Capable of recording up to 6K 60p 10-bit RAW movies with HDMI output, this game changer provides you with the highest image quality and flexibility for post-processing.The highly accurate 40 frames per second (fps) burst shooting ensures you capture every moment with full clarity.,suitable_for-Professional,processor-DIGIC X,sensor_type-APS-C Full-frame CMOS,continuous_shooting_speed-Hi+: 11fps, Hi: 8fps, Mid: 6fps, Lo: 3fps",
        price: 279999,
    },
    {
        name:"Panasonic Lumix Series Lumix DC-S1RMGA with 24-105 mm lens Mirrorless Camera Body, 24-105 MM Lens  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c9/3.png?raw=true",
        info:"2 Years Warranty. Warranty of the Product is Limited to Only Manufacturing Defect on Camera Body, Warranty Does Not Cover Any External Accessories (Such as Battery, Cable, Carrying Bag), Damage Caused to the Product due to Improper Installation by Customer",
        description:"A new 47.3MP CMOS sensor that delivers incredibly realistic detail. Focus and image stabilization systems that capture each instant with stunning clarity. A body design that fluidly guides photographic intentions toward unforgettable images. With all these features and more, this full-frame mirrorless camera transports you to the world of passionate image creation.",
        price: 398990,
    },
    {
        name:"Panasonic G Series DC-G95MGW-K Mirrorless Camera Body with Single Lens: 12-60mm lens  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/camera/c10/3.png?raw=true",
        info:"2 Year Warranty.Manufacturing Defects.Warranty does not Cover Any External Accessories.",
        description:"Effective Pixels: 20 MP,Sensor Type: MOS  WiFi Available: 4K",
        price: 92999,
    },
];
module.exports = { data:cameraData};
