const computerData=[
    {
        name:"DZAB Intel Core i5 (8 GB DDR3/500 GB/128 GB SSD/Windows 11 Home/1 GB/19 Inch Screen/AIC-i52400-8-500-128-19-11Inch)  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp1/3.png?raw=true",
        info:"Windows 11 Home, Intel Core i5,  HDD Capacity 500 GB, RAM 8 GB DDR3 , 19 inch Display",
        description:"This Computer is Assemebled Computer build with as per available Cabinet, power supply, LED Monitor, Keyboard Mouse and other Accessories. The PC comes with Trial Window 11 and Microsoft Office. There is no DVD writer in this PC. You can use this pc for Office, Online Study, Programming or Gamming purpose (Note before buying please read warranty policy carefully)",
        price: 11935,
    },
    {
        name:"HP HP All-in-One 22-dd Celeron Dual Core (8 GB DDR4/500 GB/512 GB SSD/Windows 11 Home/21.5 Inch Screen/22-dd2986in) with MS Office  (White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp2/3.png?raw=true",
        info:"1 Year onsite warranty at the time of purchase.The only warranties for HP products and services are set forth in the express warranty statements accompanying such products and services. Nothing herein should be construed as constituting an additional warranty. HP shall not be liable for technical or editorial errors or omissions contained herein.",
        description:"Windows 11 Home, Intel Celeron Dual Core HDD Capacity 500 GB ,RAM 8 GB DDR4, 21.5 inch Display",
        price: 33499,
    },
    {
        name:"ZEBRONICS Intel Core i5 (8 GB / 1 TB / Windows 10) Assembled Desktop Computer  (19 inch Display)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp3/3.png?raw=true",
        info:"1 YEAR. Not Working & Power Issue. Not Covered in Warranty DAMAGE ,BURN,SOFTWARE",
        description:"Operating System: Windows 10,  Chipset  H61 Processor : Intel Core i5,Processor Speed:3.2 GHz, RAM Type: DDR3, RAM Capacity: 8 GB,  HDD Type:  HDD,HDD Capacity: 1 TB,   Graphics Card:No, Graphics Processor Intel® HD Graphic",
        price: 16489,
    },
    {
        name:"Apple 2021 iMac with 4.5K Retina display M1 (8 GB Unified/256 GB SSD/Mac OS Big Sur/24 Inch Screen/MGPC3HN/A)  (Silver, 461 mm x 547 mm x 130 mm, 4.48 kg)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp4/3.png?raw=true",
        info:"1 Year Limited Warranty. Manufacturing Defects.Not Covered in Warranty:Physical Damage",
        description:"This computer is unlike any you've ever seen. Thanks to the Apple M1 chip the processor, allows for an incredibly tiny design. A stunningly detailed 60.96 cm (24) 4.5K Retina display that immerses you in the big picture. You can look and sound your best with the most powerful camera and microphones ever in a Mac. And six speakers that fill a space with room-filling sound, elevating music and films to new heights. It easily integrates with the iPhone, so calls and messages are delivered to your iMac",
        price: 127490,
    },
    {
        name:"Lenovo IdeaCentre Ryzen 3 Dual Core (8 GB DDR4/512 GB SSD/Windows 11 Home/Integrated AMD Radeon Graphics/23.8 Inch Screen/24ADA6) with MS Office  (White, 433.56 mm x 541 mm x 185.34 mm, 6.81 kg)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp5/3.png?raw=true",
        info:"1 Year Onsite Warranty. Manufacturing Defects.Not Covered in Warranty Physical Damage",
        description:"Windows 11 Home, AMD Ryzen 3 Dual Core RAM 8 GB DDR4,  23.8 Inch Display, Microsoft Office Home & Office Edition 2021",
        price: 39490,
    },
    {
        name:"HP All-in-One Core i5 (8 GB DDR4/1 TB/256 GB SSD/Windows 11 Home/Intel Graphics/23.8 Inch Screen/24-cb1902in) with MS Office  (Starry white, 419 mm x 540.6 mm x 183.7 mm, 5.37 kg)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp6/3.png?raw=true",
        info:"1 Year onsite warranty at the time of purchase. The only warranties for HP products and services are set forth in the express warranty statements accompanying such products and services. Nothing herein should be construed as constituting an additional warranty.",
        description:"Windows 11 Home,  Intel Core i5,  HDD Capacity 1 TB,   RAM 8 GB DDR4 ,23.8 Inch Display",
        price: 65499,
    },
    {
        name:"ASUS AiO A3 Series All in One Desktop, Intel 12th Gen Core i3 (8 GB DDR4/512 GB SSD/Windows 11 Home/21.45 Inch Screen/A3202WBAK-BA004WS) with MS Office  (Black, 395 mm x 493 mm x 165 mm, 4.84 Kg)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp7/3.png?raw=true",
        info:"1 Year Onsite Warranty. Covered in Warranty Physical Damage",
        description:"You can enhance your productivity and get a lot done while saving space with the ASUS A3202 54.48 cm (21.45) All-in-one PC. Its sleek and light design allows you to easily move this PC from one place to another. Also, this all-in-one PC is made with a 54.48 cm (21.45) FHD display with a resolution of up to 1920x1080p that lets you enjoy lifelike visuals with fascinating colour and contrast. Furthermore, its wide 178-degree viewing angle allows you to see the screen even when you’re watching from sharp angles.",
        price: 42990,
    },
    
    {
        name:"Lenovo ideacentre Core i5 (16 GB DDR4/1000 GB SSD/Windows 11 Home/27 Inch Screen/AIO 3-27IAP7) with MS Office  (White, 56 cm x 75 cm x 23 cm, 8 Kg)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp8/3.png?raw=true",
        info:"1 Year Onsite Warranty. Manufacturing Defects. Not Covered in Warranty Physical Damage",
        description:"Lenovo is a Chinese multinational technology company. It designs, develops, manufactures and sells personal computers, tablet computers, smartphones, electronic storage devices and more. Since 2013, Lenovo is the world's largest personal computer vendor by unit sales.",
        price: 71990,
    },
    {
        name:"Vintech Intel Core i5 (8 GB / 256 GB / Windows 10) Assembled Desktop Computer  (19 inch Display)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp9/3.png?raw=true",
        info:"Operating System: Windows 10,  Chipset:  H61,  Processor:  Intel Core i5, Processor Speed: 3.2 GHz, RAM Type: DDR3,RAM Capacity: 8 GB,HDD Type:SSD HDDTYPE Capacity: 256 GB",
        description:"  This Computer is Assemebled Computer build with as per available Cabinet, power supply, LED Monitor, Keyboard Mouse and other Accessories. The PC comes with Trial Window 11 and Microsoft Office. There is no DVD writer in this PC. You can use this pc for Office, Online Study, Programming or Gamming purpose (Note before buying please read warranty policy carefully)",
        price: 14999,
    },
    {
        name:"ZEBRONICS Core i7 (16 GB / 2 TB / Windows 10) Assembled Desktop Computer  (22 cm Display)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/computer/cmp10/3.png?raw=true",
        info:"1 year warranty.Covered in Warranty: All in box",
        description:"Operating System: Windows 10, Chipset: 450g Processor:Core i7,Processor Speed: 4.4 GHz, RAM Type: DDR4, RAM Capacity: 16 GB, HDD Type: SSD, HDD Capacity: 2 TB",
        price: 50000,
    },
];
module.exports = { data:computerData};
