const laptopData=[
    {
        name:"Acer Aspire 3 Intel Core i3 12th Gen 1215U - (8 GB/512 GB SSD/Windows 11 Home) A315-59-36HE Thin and Light Laptop  (15.6 inch, Pure Silver, 1.7 Kg)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp1/3.png?raw=true",
        info:"1 Year Onsite Warranty. Manufacturing Defects. Not Covered in Warranty:  Physical Damage",
        description:"The Acer Aspire 3 laptop is not just a device; it's a companion that empowers your passion, enhances your productivity, and brings you closer to the people who matter. With its ready-to-go performance, Windows 11 integration, connectivity features, sleek design, and vibrant display, the Aspire 3 redefines what a laptop can be. Elevate your computing experience with a device that understands your needs and complements your lifestyle. The Acer Aspire 3 is not just a laptop; it's a gateway to a world of possibilities. Welcome to a new era of computing excellence.",
        price: 37250,
    },
    {
        name:"Lenovo IdeaPad Slim 3 Intel Core i5 12th Gen 1235U - (8 GB/512 GB SSD/Windows 11 Home) 15IAU7 Thin and Light Laptop  (15.6 Inch, Arctic Grey, 1.63 Kg, With MS Office)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp2/3.png?raw=true",
        info:"1 Year Limited Warranty. Manufacturing Defects.Not Covered in Warranty Physical Damage",
        description:" You can get your work done in no time with the Lenovo IdeaPad Slim 3 Laptop. With its lightweight body sporting up to 19.9 mm of thinness, this laptop enables you to effortlessly carry it anywhere. Offering up to four-sided narrow bezels and a screen-to-body ratio of up to 88%, this laptop renders impactful visuals. In addition, it has a long battery life of up to 8 hours, so you can use it for long durations.",
        price: 47990,
    },
    {
        name:"Apple 2020 Macbook Air Apple M1 - (8 GB/256 GB SSD/Mac OS Big Sur) MGN63HN/A  (13.3 inch, Space Grey, 1.29 kg)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp3/3.png?raw=true",
        info:"1 Year Limited Warranty. Manufacturing Defects.Not Covered in Warranty Physical Damage",
        description:"This Apple Macbook is powered by the Apple M1 chip and is easily portable so that you can carry it with you anywhere you want. This thin and light notebook is equipped with an 8-core CPU to handle all your tasks more efficiently. The 8-core GPU of this notebook takes graphic-intensive games and apps to a whole new level. It also comes with a 16-core Neural Engine to do machine learning tasks more effectively. Its fan-less design offers silent operations and has a long-lasting battery life which can last up to 18 hours on a single charge.",
        price: 74990,
    },
    {
        name:"HP 15s Intel Core i3 12th Gen 1215U - (8 GB/512 GB SSD/Windows 11 Home) 15s-fq5007TU Thin and Light Laptop  (15.6 Inch, Grey, 1.69 kg, With MS Office)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp4/3.png?raw=true",
        info:"1 Year Limited Warranty. Manufacturing Defects.Not Covered in Warranty Physical Damage",
        description:"  With this HP laptop, which is packed with amazing capabilities, you can find delight in beautiful graphics and easily multitask. The processing capacity of this laptop works in conjunction with the raw strength of the Intel processor and graphics to offer a learning environment that is adaptable and user-friendly. You can finish your tasks with this laptop's USB ports and integrated 4G LTE setup. For those who put in long hours of work day and night, this laptop provides a dependable workstation. Enjoy 1920 x 1080 resolution as well for clear visuals and images that give all of your digital content a distinct dimension. With the power of 2 million pixels, you can experience digital content in a mesmerising fashion.",
        price: 37290,
    },
    {
        name:"SAMSUNG Galaxy Book 2 Intel Core i5 12th Gen 1235U - (8 GB/512 GB SSD/Windows 11 Home) NP550 Thin and Light Laptop  (15.6 Inch, Graphite, 1.80 Kg, With MS Office)#JustHere",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp5/3.png?raw=true",
        info:"1 Year Limited Warranty. Manufacturing Defects.Not Covered in Warranty Physical Damage",
        description:" Processor Brand: Intel Processor Name Core i5 Processor Generation: 12th Gen SSD Yes SSD Capacity 512 GB RAM 8 GB RAM Type DDR4",
        price: 54990,
    },
    {
        name:"DELL Intel Core i3 12th Gen 1215U - (8 GB/512 GB SSD/Windows 11 Home) New Inspiron 15 Laptop Thin and Light Laptop  (38 cm, Carbon Black, 1.65 Kg, With MS Office)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp6/3.png?raw=true",
        info:"1 Year Onsite Hardware Service. Manufacturing Defects Not Covered in Warranty  Accidental Damage.",
        description:"With a PCIe SSD and a 12th-generation Intel Core i3 processor incorporated into this Dell laptop, you can enjoy a quick yet peaceful performance. Additionally, ComfortView software lowers hazardous blue light emissions to keep your eyes pleasant during prolonged viewing sessions. Furthermore, enjoy the large keycaps and a big touchpad that make it simple to access your content. Moreover, the FHD display of this laptop is surrounded by a stylish, slim bezel on three sides, enhancing your visual experience.",
        price: 34699,
    },
    {
        name:"Acer Predator Neo (2023) Intel Core i7 13th Gen 13700HX - (16 GB/1 TB SSD/Windows 11 Home/6 GB Graphics/NVIDIA GeForce RTX 4050) PHN16-71-757P Gaming Laptop  (16 Inch, Obsidian Black, 2.6 Kg)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp7/3.png?raw=true",
        info:"Acer Predator Neo (2023) Intel Core i7 13th Gen 13700HX - (16 GB/1 TB SSD/Windows 11 Home/6 GB Graphics/NVIDIA GeForce RTX 4050) PHN16-71-757P Gaming Laptop  (16 Inch, Obsidian Black, 2.6 Kg)",
        description:"You can enter a whole new level of the gaming world with the Acer Predator Helios Neo 16 laptop. Powered by the 13th Gen Intel Core i7 HX processor and 16 GB of DDR5-4800 MHz RAM, this laptop ensures an enhanced performance that makes your gaming experience flawless. The NVIDIA GeForce RTX 4050 series GPU ensures stunning graphics. This laptop uses AeroBlade fan technology to ensure that your system does not overheat. With the 165 Hz refresh rate and 3 ms response time you can enjoy a smooth gaming experience.",
        price: 112990,
    },
    {
        name:"HP 2023 Intel Core i5 12th Gen 1235U - (8 GB/512 GB SSD/Windows 11 Home) 15s-fy5002TU Thin and Light Laptop  (15.6 Inch, Natural Silver, 1.69 Kg, With MS Office)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp8/3.png?raw=true",
        info:"1 Year Onsite Hardware Service. Manufacturing Defects Not Covered in Warranty  Accidental Damage.",
        description:"You can enter a whole new level of the gaming world with the Acer Predator Helios Neo 16 laptop. Powered by the 13th Gen Intel Core i7 HX processor and 16 GB of DDR5-4800 MHz RAM, this laptop ensures an enhanced performance that makes your gaming experience flawless. The NVIDIA GeForce RTX 4050 series GPU ensures stunning graphics. This laptop uses AeroBlade fan technology to ensure that your system does not overheat. With the 165 Hz refresh rate and 3 ms response time you can enjoy a smooth gaming experience.",
        price: 49990,
    },
    {
        name:"Acer Predator Neo (2023) Intel Core i5 13th Gen 13500HX - (16 GB/512 GB SSD/Windows 11 Home/6 GB Graphics/NVIDIA GeForce RTX 4050) PHN16-71-59XW/ PHN16-71-553K/ PHN 16-71 Gaming Laptop  (16 Inch, Obsidian Black, 2.6 Kg)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp9/3.png?raw=true",
        info:"1 Year International Travelers Warranty (ITW). Manufacturing Defects Not Covered in Warranty Physical Damage",
        description:"  You can enter a whole new level of the gaming world with the Acer Predator Helios Neo 16 laptop. Powered by the 13th Gen Intel Core i7 HX processor and 16 GB of DDR5-4800 MHz RAM, this laptop ensures an enhanced performance that makes your gaming experience flawless. The NVIDIA GeForce RTX 4050 series GPU ensures stunning graphics. This laptop uses AeroBlade fan technology to ensure that your system does not overheat. With the 165 Hz refresh rate and 3 ms response time you can enjoy a smooth gaming experience. You can take control of the gaming world with the 4-zone RGB keyboard. This laptop features Intel Killer E2600 Ethernet and Intel Killer WiFi 6 AX1650 that enables you with quick connectivity.",
        price: 99990,
    },
    {
        name:"ASUS Vivobook S 14 Flip (2023) AMD Ryzen 5 Hexa Core 7530U - (16 GB/512 GB SSD/Windows 11 Home) TN3402YAB-LZ541WS 2 in 1 Laptop  (14 Inch, Quiet Blue, 1.50 Kg, With MS Office)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/laptop/lp10/3.png?raw=true",
        info:"1 Year International Travelers Warranty (ITW). Manufacturing Defects Not Covered in Warranty Physical Damage",
        description:"The Vivobook S 14 Flip laptop is a feature-packed laptop for all your adventures. It has a 360-degree hinge that allows you to work, play, sketch, and do much more. It ensures a smooth performance, thanks to the AMD Ryzen 7000 U series processor. The SSD storage provides more storage to store all your data. It has a wide 35.56 cm (14) display with Nanoedge touchscreen for easy access.",
        price: 58990,
    },
];
module.exports = { data:laptopData};
