const mobilesData=[
    {
        name:"OnePlus Nord CE 3 Lite 5G (Pastel Lime, 128 GB)  (8 GB RAM)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m1/3.png?raw=true",
        info:"Domestic Warranty of 12 months on phone & 6 months on accessories",
        description:"8 GB RAM | 128 GB ROM,  17.07 cm (6.72 inch) Display, 108MP Rear Camera, 5000 mAh Battery",
        price: 17618,
    },
    {
        name:"realme 12+ 5G (Pioneer Green, 256 GB)  (8 GB RAM)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m2/3.png?raw=true",
        info:"1 Year Manufacturer Warranty for Device and 6 Months Manufacturer",
        description:"  The realme 12+ 5G is a paradigm shift in smartphone innovation, boasting a 50 MP Sony LYT-600 OIS Portrait Camera for unparalleled photography, while the MediaTek Dimensity 7050 5G Chipset ensures powerful performance and seamless connectivity. Collaborating with Ollivier Savelli, the design incorporates luxury watch elements, offering a polished sunburst dial, 3D jubilee bracelet, and premium vegan leather. ",
        price: 21999,
    },
    {
        name:"Apple iPhone 13 (Blue, 128 GB)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m3/3.png?raw=true",
        info:"128 GB ROM: 15.49 cm (6.1 inch) Super Retina XDR Display 12MP + 12MP | 12MP Front Camera A15 Bionic Chip Processor",
        description:" iPhone 13. boasts an advanced dual-camera system that allows you to click mesmerising pictures with immaculate clarity. Furthermore, the lightning-fast A15 Bionic chip allows for seamless multitasking, elevating your performance to a new dimension. A big leap in battery life, a durable design, and a bright Super Retina XDR display facilitate boosting your user experience.",
        price: 52999,
    },
    {
        name:"Apple iPhone 14 Plus (Starlight, 128 GB)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m4/3.png?raw=true",
        info:"1 Year Warranty for Phone and 6 Months Warranty for In-Box Accessories",
        description:"Stay productive and improve your performance with the Super Retina XDR display that is comfortable for the eyes. Powered with a 12 MP main camera, enjoy taking pictures with friends and family. With a built-in rechargeable lithium-ion battery and equipped with the MagSafe wireless charging, you can charge your phone quickly up to 50 % in just half an hour by using a 20 W adapter. This phone is loaded with a horde of exciting features such as Siri, face ID, barometer, ambient light sensors etc., and is also resistant to dust and water as it is IP68 rated.",
        price: 66999,
    },
    {
        name:"Apple iPhone 14 (Blue, 128 GB)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m5/3.png?raw=true",
        info:"1 Year Warranty for Phone and 6 Months Warranty for In-Box Accessories",
        description:"Stay productive and improve your performance with the Super Retina XDR display that is comfortable for the eyes. Powered with a 12 MP main camera, enjoy taking pictures with friends and family. With a built-in rechargeable lithium-ion battery and equipped with the MagSafe wireless charging, you can charge your phone quickly up to 50 % in just half an hour by using a 20 W adapter. This phone is loaded with a horde of exciting features such as Siri, face ID, barometer, ambient light sensors etc., and is also resistant to dust and water as it is IP68 rated.",
        price: 58999,
    },
    {
        name:"Google Pixel 7 (Lemongrass, 128 GB)  (8 GB RAM)#JustHere",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m6/3.png?raw=true",
        info:"8 GB RAM | 128 GB ROM, 16.0 cm (6.3 inch) Full HD+ Display, 50MP + 12MP | 10.8MP Front Camera, 4270 mAh Battery, Google Tensor G2 Processor",
        description:"Experience smooth operation and brilliant user interface with the 5G-ready Google Pixel 7 smartphone that comes loaded with innovative features. Google Tensor G2 makes the Pixel 7 faster, more efficient, and more secure and it delivers even more helpful features. Furthermore, the Pixel 7 Camera takes incredible photos and videos in stunning colour and detail. It includes Super Res Zoom so that you can get super-sharp close-ups without an extra telephoto lens. Additionally, the Pixel 7's 16.002 cm (6.3) display is super sharp, with rich, vivid colours. And it's fast and responsive for smoother gaming, scrolling, and moving between apps. ",
        price: 46999,
    },
    {
        name:"Google Pixel 8 (Rose, 128 GB)  (8 GB RAM)#JustHere",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m7/3.png?raw=true",
        info:"8 GB RAM | 128 GB ROM, 15.75 cm (6.2 inch) Full HD+ Display, 50MP + 12MP | 10.5MP Front Camera 4575 mAh Battery, Tensor G3 Processor",
        description:"  Stay productive throughout the day with this Pixel 8 smartphone that brings to you a multitude of impressive and useful features. Built over a powerful chipset and custom-designed with Google AI for splendid photo and video features, this smartphone is a game changer. With a 6.2-inch high-resolution display, this phone displays sharp and clear content. Audio Magic Eraser uses Google AI to reduce distracting sounds. The phone is designed with safety features to quickly help you respond during emergency situations. With IP68 protection, the phone can handle dust and spills efficiently. Turning on the Extreme Battery Saver mode can help run your phone’s battery up to 72 hours.",
        price: 69999,
    },
    {
        name:"OnePlus 11R 5G (Galactic Silver, 128 GB)  (8 GB RAM)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m8/3.png?raw=true",
        info:"Domestic warranty of 12 months on phone & 6 months on accessories",
        description:"8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Display, 50MP Rear Camera, 5000 mAh Battery",
        price: 32906,
    },
    {
        name:"OnePlus 12R (Iron Grey, 256 GB)  (16 GB RAM)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m9/3.png?raw=true",
        info:"16 GB RAM | 256 GB ROM  17.22 cm (6.78 inch)Display,  50MP Rear Camera,  5500 mAh Battery",
        description:" The weight of the phone is 207 g, and the weight of the screen protector may add an additional 3g. The size and weight of the mobile phone may vary according to configuration, manufacturing process and measurement method. 3. Due to the mobile phone system file occupying space (including Android system and pre-installed apps),",
        price: 44983,
    },
    {
        name:"realme 11x 5G (Purple Dawn, 128 GB)  (6 GB RAM)#JustHere",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m9/3.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/mobiles/m9/3.png?raw=true",
        info:"1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories",
        description:"Avail yourself this 5G smartphone that offers a host of interesting features. The powerful MediaTek Dimensity 6100+ 5G chipset delivers a smooth performance. Click beautiful portraits with the 64 MP AI camera that offers exciting features like Street Photography Mode 4.0, Super Nightscape, 2x In-sensor zoom, and more. Equipped by a 5000 mAh long-lasting battery, this phone runs for a longer duration and can be recharged quickly with the 33 W SUPERVOOC charger available along with this device. ",
        price: 14999,
    },
];
module.exports = { data:mobilesData};
