const BluetoothData=[
    {
        name:"Syska PACE HE100H with ENC,10mm Driver,Fast Charging,100Hr Playback Bluetooth Headset  (JADE BLACK, In the Ear)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb1/3.png?raw=true",
        info:"1 Year Manufacturer Warranty from Date of Purchase.Manufacturing Defects Only.Not Covered in Warranty  Physical and Electrical Damages",
        description:"With Mic:Yes Wireless range: 10 m Charge & Forget : Enjoy unstoppable 100 Hrs of Playing Time with Charging Time of 2Hrs.IIRapid Pulse Charge : With Just 10 mins Charge, Play for 13 HrsIIAutoENC Technology for Surrounding Sound ReductionIIType C Charging Input",
        price: 1299,
    },
    {
        name:"HRX X-Wave 14R with Bass Boost Mode Bluetooth Headset  (Space Gold, In the Ear)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb2/3.png?raw=true",
        info:"1 Year Limited Domestic Brand Warranty.Warranty is Non-transferrable, Valid Only in the Territory of India and Extended Only to the First End User Customer (Customer). 2) Warranty will be Valid Only when the Original Purchase Invoice is Presented at the Time of Service. 3) Warranty will Cover Only Functional Parts and Software Issues having Manufacturing Defects and does Not Cover Damages Resulting from Unauthorised Adaptations/Adjustments/Tampering of the Product, Improper Installation of the Product, Normal Wear and Tear Caused Due to Use of Product.",
        description:"Presenting HRX X-Wave 14R – with an immersive Bass Boost Mode experience bringing a deep-focus on your cardio & workouts. The neckband’s liquid silicone finish is gentle on your skin and the device is sweat-proof and splash-proof. A Qualcomm chipset + 10 mm drivers enhance its audio and bass quality. The Bluetooth 5.0 and A2DP lets you pair with more than one device at a time and 8th Generation Qualcomm cVc Noise Cancellation Technology cuts out ambient noise from the mic.",
        price: 1599,
    },
    {
        name:"Beats Flex - Apple W1 Headphone Chip, Class 1 Bluetooth, 12Hrs Playtime Bluetooth Headset  (Yuzu Yellow, In the Ear)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb3/3.png?raw=true",
        info:"With Mic:Yes,Battery life: 12 hrsMagnetic earbuds with Auto-Play/Pause,Up to 12 hours of listening time All-day comfort with Flex-Form cable and four eartip options, Powered by the Apple W1 headphone chip for seamless connectivity",
        description:"FLEX ALL DAY The Flex-Form cable provides all-day comfort with durable Nitinol construction while four eartip options offer a personalized fit. Magnetic earbuds make listening that much easier by automatically playing music when they?re in your ears and pausing when they?re attached around your neck1.",
        price: 4499,
    },
    {
        name:"ZEBRONICS Yoga 1 Jumbo (Black) Bluetooth Headset  (Black, In the Ear)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb4/3.png?raw=true",
        info:"1 year carry into service centre.Manufacturing Defect.Not Covered in Warranty:Any Physical Damage And Accessories",
        description:"UMBO ZEB-YOGA 1 Bluetooth wireless earphones with 160H* backup time, 1000mAh built-in rechargeable battery, Flash charge for 15H* of extensive usage with just 10 minutes of charge, Environmental Noise Cancellation microphone, 50ms Low latency Gaming mode, Dual pairing, Voice assistant support for Android and iOS, Deep bass sound signature and much more interesting features!",
        price: 899,
    },
    {
        name:"SONY WI-XB400 Extra Bass Wireless Stereo Bluetooth Headset  (Black, In the Ear)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb5/3.png?raw=true",
        info:"1 Year Warranty.Manufacturing Defects.Not Covered in Warranty Physical Damages ",
        description:"With Mic:Yes,Bluetooth version: 4.2   Wireless range: 10 m, Battery life: 15 hrs | Charging time: Approximate 4.5 hrs, 10 mins charge 60 minsplaytime",
        price: 2999,
    },
    {
        name:"CMF by Nothing Neckband Pro 50dB Active Noise Cancellation, Smart Dial Design, 37 Hrs playtime Bluetooth Headset  (Dark Grey, In the Ear)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb6/2.png?raw=true",
        info:"1 Year Warranty,Manufacturing Defects.Not Covered in Warranty: Physical Damages",
        description:"With Mic:Yes,  Bluetooth version: 5.3 Wireless range: 15 m, Battery life: 37 hr, 50 dB Active noise cancellation,  Smart Dial Design,13.6mm Driver with Ultra Bass technology, Spatial Audio  Clear voice technology with AI Noise cancellation, 10 minutes of charging= 18 hours of playback",
        price: 1999,
    },
    {
        name:"OnePlus OnePlus Bullets Wireless Z2 Bluetooth Headset (Acoustic Red, In the Ear) Bluetooth Headset  (Acoustic Red, In the Ear)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb7/3.png?raw=true",
        info:"1 Year Warranty,Manufacturing Defects.Not Covered in Warranty: Physical Damages",
        description:"With Mic:Yes, Bluetooth version: 5, Battery life: 20 Hrs | Charging time: 10 Mins, Battery life: 20 Hrs, Charging time: 10 mins",
        price: 1499,
    },
    {
        name:"realme Buds Wireless 2 Neo with Type-C Fast Charge & Bass Boost+ Bluetooth Headset  (Blue, In the Ear)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb8/3.png?raw=true",
        info:"1 Year Warranty,Manufacturing Defects.Not Covered in Warranty: Physical Damages",
        description:"With Mic:Yes, 11.2mm Bass Boost Driver | 17hrs Total Playback, Environmental Noise Cancellation | IPX4 Water Resistant, Multi Device Switch | 88ms Low Latency, Quick Charge (120mins playback in 10min charge) Magnetic Tips With Instant Connection",
        price: 1299,
    },
    {
        name:"boAt Rockerz 255 Pro+ /258 Pro+ with ASAP Charge and upto 60 Hours Playback Bluetooth Headset  (Active Black, In the Ear)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb9/3.png?raw=true",
        info:"1 Year Warranty,Manufacturing Defects.Not Covered in Warranty: Physical Damages",
        description:"boAt Rockerz 255 Pro+ is a power-packed in-ear wireless neckband headphone that has been ergonomically designed to meet the needs of music lovers. The headphones come equipped with Bluetooth V5.0 for instant wireless connectivity. Its super powerful 300mAh battery provides a humongous playtime of up to 60 hours for an extended audio bliss. Its 10mm dynamic drivers help supply superior musical experience to the user with immersive sound. With our ASAP fast charge technology, you can get the headphones fully charged in just 60 minutes. ",
        price: 1299,
    },
    {
        name:"realme Buds Wireless 3 with 30dB ANC, 360 degree Spatial Audio, upto 40 hours Playback Bluetooth Headset  (Pure Black, In the Ear)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/bluetooth%20neckband/nb10/3.png?raw=true",
        info:"1 Year Warranty,Manufacturing Defects.Not Covered in Warranty: Physical Damages",
        description:" You can listen to your favourite tracks, play games, and attend calls in exceptional quality audio with the realme Buds Wireless 3 Neckband. With its ability to provide up to a 360-degree spatial audio effect, this neckband offers a captivating and immersive sound experience reminiscent of being in a theatre, where the sound envelops you from all directions. This feature creates a life-like and three-dimensional audio environment that boosts your senses.",
        price: 1799,
    },
];
module.exports = { data: BluetoothData};
