const powerbankData=[
    {
        name:"Mi 20000 mAh 18 W Power Bank  (Black, Lithium Polymer, Fast Charging for Mobile)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb1/3.png?raw=true",
        info:"Port- Type C and Micro USB  Cable- Type C Recharging time- 6.9 hours (with 18 W charger and USB cable) Weight: 434 g | Capacity: 20000 mAh Lithium Polymer Battery | Type-C Connector  Power Source: Battery  Charging Cable Included",
        description:"Don't let your devices run out of battery while you're away with this Mi power bank. Thanks to its 18 W fast charge support, this power bank helps you charge your devices quickly and efficiently. It also helps you charge almost all types of devices, such as smartphones, fitness bands and Mi wireless earphones and tablets.",
        price: 1999,
    },
    {
        name:"boAt 20000 mAh 22.5 W Power Bank  (Steel Blue, Lithium Polymer, Quick Charge 3.0 for Mobile)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb2/3.png?raw=true",
        info:"1 Year Warranty.Manufacturing Defects.Not Covered in Warranty  Physical Damages",
        description:"20000mAh capacity with Smart Power Management  Lightning quick charge  Universal compatibility Hassle-free charge Ultra-Durability including High Temperature and Scratch Resistance Built-in 12-layer Smart IC protection from short circuit, over charge & over discharge Input/Output control and LED indicators. Capacity: 20000 mAh Lithium Polymer Battery | Type-A, Type-C Connector Power Source: AC Adapter Charging Cable Included",
        price: 1499,
    },
    {
        name:"Mi 10000 mAh 22.5 W Pocket Size Power Bank  (Black, Lithium Polymer, Fast Charging for Mobile)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb3/3.png?raw=true",
        info:"6 Months Domestic Warranty. Manufacturing Defects  Not Covered in Warranty Physical Damages, Wear and Tear",
        description:"Whether you are off to travel to an exotic location or just commuting to work, you can carry the Mi 10000 mAh Pocket Power Bank Pro to ensure that your smartphones, tablets, smart accessories, and other devices can power through long and busy days. Thanks to its triple output ports, this power bank can replenish the charge of up to three devices simultaneously. Moreover, its 12-layer circuit-protection design safeguards your devices from short circuits, overheating, and over-current scenarios.",
        price: 1499,
    },
    {
        name:"Ambrane 10000 mAh 22.5 W Wired & Wireless With MagSafe Compact Pocket Size Power Bank  (Black, Lithium Polymer, Power Delivery 3.0, Quick Charge 3.0 for Mobile)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb4/3.png?raw=true",
        info:"6 Months Domestic Warranty. Manufacturing Defects  Not Covered in Warranty Physical Damages, Wear and Tear",
        description:" Elevate your charging experience with the AeroSync PB-10, a magsafe power bank designed for the tech-savvy. With power bank 10000mah capacity, it redefines powerbank fast charging. This wireless powerbank is the ultimate solution for power bank for iPhone, making it the best power bank to buy for those who demand efficienc",
        price: 1899,
    },
    {
        name:"Intex 30000 mAh 22 W Power Bank  (Black, Lithium-ion, Quick Charge 3.0 for Mobile)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb5/3.png?raw=true",
        info:"1 Year Warranty.Manufacturing Defects.Not Covered in Warranty  Physical Damages",
        description:"  Introducing the Strong Rhino QC PD 30K Poly Power Bank with a massive 22W Power Output, PD QC, and a heavy 30000mAh capacity, this power bank has a massive battery with rapid charging. Designed for long rides and long journeys, it provides adequate protection against overcharge, overcurrent, overcharge, and short circuits due to its smart IC protection layers and a capacitive digital display.",
        price: 1749,
    },
    {
        name:"URBN 20000 mAh 12 W Pocket Size Power Bank  (Camo, Lithium Polymer, Fast Charging for Mobile)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb6/3.png?raw=true",
        info:"6 Months Domestic Warranty. Manufacturing Defects  Not Covered in Warranty Physical Damages, Wear and Tear",
        description:" Introducing the Strong Rhino QC PD 30K Poly Power Bank with a massive 22W Power Output, PD QC, and a heavy 30000mAh capacity, this power bank has a massive battery with rapid charging. Designed for long rides and long journeys, it provides adequate protection against overcharge, overcurrent, overcharge, and short circuits due to its smart IC protection layers and a capacitive digital display.",
        price: 1499,
    },
    {
        name:"REDMI 10000 mAh 10 W Power Bank  (Black, Lithium Polymer, Fast Charging for Mobile)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb7/3.png?raw=true",
        info:"6 Months Domestic Warranty. Manufacturing Defects  Not Covered in Warranty Physical Damages, Wear and Tear",
        description:"Want to charge your devices on-the-go? Then this 10000 mAh power bank from Redmi will be a great addition to your travel bag. It features dual ports and two-way 10 W fast charging. That's not all, its anti-slip edge grip design ensures that you get to hold the device firmly and avoid any accidental drops.",
        price: 1099,
    },
    {
        name:"FluSun india 60000 mAh 24 W Power Bank  (White, Lithium-ion, Power Delivery 3.0, Fast Charging for Mobile)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb8/3.png?raw=true",
        info:"6 Months Domestic Warranty. Manufacturing Defects  Not Covered in Warranty Physical Damages, Wear and Tear",
        description:"  We understand your data is precious to you. Hence, to store your data in a safe manner, we have for you FluSun india 60000mAh Power Bank with 3 USB Ports. A safe warehouse of all your data, whether they are documents, your precious memories in the form of photos or your favourite music tracks or movies, keep them all well organized with this brilliant power bank from FluSun india. Especially, if you are travelling, this device is important for you as it will enable you to carry your data with you. It is fit for various mobile phones and devices. -Fit For Various Mobile Phone & Devices. Compact & Heavy Duty. Fast And Proper Charging. IC Controlled Output. Important Companion For Travellers.",
        price: 1799,
    },
    {
        name:"Spigen 20000 mAh 22.5 W Power Bank  (Navy Blue, Lithium Polymer, Fast Charging for Mobile)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb9/3.png?raw=true",
        info:"6 Months Domestic Warranty. Manufacturing Defects  Not Covered in Warranty Physical Damages, Wear and Tear",
        description:" Max 22.5W Output, Premium Quality Battery Cell Power Bank from Spigen 20W for 2 USB-C port and 22.5W for 1 USB-A port.",
        price: 2099,
    },
    {
        name:"PTron 10000 mAh 22.5 W Power Bank  (Black, Lithium Polymer, Quick Charge 3.0 for Mobile)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/powerbank/pb10/3.png?raw=true",
        info:"6 Months Domestic Warranty. Manufacturing Defects  Not Covered in Warranty Physical Damages, Wear and Tear",
        description:"pTron Dynamo 10000mAh power bank is a portable powerhouse with a dual USB & PD/Type-C output that offers high-speed charging and ensures your devices make it through your busiest and longest days. Dual USB input (micro USB & Type-C/PD) and output - 2 USB ports, which can charge the devices at the same time",
        price: 999,
    },
];
module.exports = { data: powerbankData};