const printerData=[
    {
        name:"Canon PIXMA MegaTank/Ink Efficient G3770 Multi-function WiFi Color Ink Tank Printer with Black (135 ml) & Color (70 ml) ink bottles  (4 Ink Bottles Included)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p1/3.png?raw=true",
        info:"1 Year or 30,000 Prints (which ever is earlier) Onsite warranty from the date of purchase",
        description:"You can print without a problem and finish your workplace assignment promptly with the Canon printer designed for easy printing. You can print regularly at work with this Canon printer without being concerned with the price of ink. Owing to the high-page-yield ink bottles, it can print up to 7,600 pages in monotone and 8,100 pages in colour. Additionally, you can quickly print from smartphones, tablets, laptops, and cloud storage thanks to the free Canon Print Inkjet/SELPHY and Canon Easy-PhotoPrint Editor programmes.",
        price: 13749,
    },
    {
        name:"Epson L3250 Multi-function WiFi Color Ink Tank Printer  (4 Ink Bottles Included)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p2/3.png?raw=true",
        info:"Output: Color  WiFi, WiFi Direct, USB | USa  Print Speed Mono A4: 10 ipm | Print Speed Color A4: 5 ipm  Supported OS: Windows, macOS, Linux",
        description:"   Printing Method :- Inkjet Type:- Multi-function Model Name:- L3250 Printing Output :- Color Brand:- Epson Refill Type:- Ink Bottle Ideal Usage :-Home & Small Office",
        price: 14349,
    },
    {
        name:"HP Smart Tank All In One 580 Multi-function WiFi Color Ink Tank Printer for Print, Scan & Copy with 1 additional black ink bottle to Print Upto 12000 Black & 6000 Color Pages and 1 Year Extended Warranty with PHA Coverage",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p3/3.png?raw=true",
        info:"1+1 Year Domestic Warranty. Link to redeem the extended warranty :",
        description:"  You can print assignments and documents with vibrant colours and legible texts using the HP Smart Tank 580 All-in-one Colour Printer. It helps you accomplish printing tasks in less time with its hassle-free mobile setup, guided buttons, two-sided printing, low-ink sensors, self-healing Wi-Fi, and exceptional print quality. In addition, with the powerful HP Smart app features, this printer lets you easily print and scan from anywhere. Moreover, this printer boasts smart-guided buttons that illuminate and provide assistance as you print.  ",
        price: 15299,
    },
    {
        name:"brother DCP-T525W All-in-One Refill Multi-function WiFi Color Ink Tank Printer (Borderless Printing) ideal for Home & Office Usage  (4 Ink Bottles Included)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p4/3.png?raw=true",
        info:"Output: Color WiFi | USB Print Speed Mono A4: 30 ppm | Print Speed Color A4: 12 ppm Supported OS: Windows, macOS, Linux",
        description:"You can print personal and professional documents with the help of the brother DCP-T525W Printer. With its document printing speeds of up to 30/12 ppm, you can do more printing activities in a short amount of time. Additionally, this printer's up to 150-sheet paper tray, which can be changed for different paper sizes, and an additional single-sheet manual feed slot for different paper types let you manage a host of printing tasks. Moreover, the ink tank for this printer's refill tank mechanism has a transparent cover that makes front access hassle-free. ",
        price: 14299,
    },
    {
        name:"HP 1008W Single Function WiFi Monochrome Laser Printer  (Toner Cartridge)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p5/3.png?raw=true",
        info:"1+1 Year Domestic Warranty. Link to redeem the extended warranty ",
        description:"You can get high printing efficiency and professional-grade results with the HP Laser 1008w Printer. Thanks to its optimal and rapid performance, this printer delivers exceptional performance for every printing task. In addition, with LaserJet printing technology, this printer offers consistent production with high-quality results, maintaining the same level of excellence on every page. Furthermore, this printer excels at generating crisp text, rich black shades, and precise graphics, eradicating the inconvenience of dealing with unclear documents.  ",
        price: 12999,
    },
    {
        name:"Canon E4570 Multi-function WiFi Color Inkjet Printer with Voice Activated Printing Google Assistant and Alexa with Auto Duplex feature and Auto-document feeder  (Ink Cartridge)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p6/3.png?raw=true",
        info:"1 year Onsite warranty from the date of purchase",
        description:" If you are looking for a printer that can help you save time and resources while keeping up with your printing needs, the Canon E4570 Printer is excellent for you. With its auto two-sided printing feature, this printer is designed for efficient utilisation of resources, helping you stay productive while saving time and paper. In addition, its up to 20 sheets Auto Document Feeder (ADF) enables automated batch copying and scanning of multi-page document originals. And, with an up to 5.2 cm LCD display, navigating and confirming print settings on this printer is a breeze.",
        price: 7999,
    },
    {
        name:"HP Ink Tank 316 Multi-function Color Ink Tank Printer (Color Page Cost: 20 Paise | Black Page Cost: 10 Paise)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p7/3.png?raw=true",
        info:"1 year Onsite warranty from the date of purchase",
        description:"Combining intuitive design with powerful performance, the HP Ink Tank 316 Printer is a must-have. It leverages a dependable and spill-free ink system to produce a large number of prints at a low cost per page. And, this allows for up to 8000 pages in colour or up to 6000 pages in black and white while still maintaining excellent quality results. Moreover, as a multifunctional device, this printer can handle all of your printing, scanning, and copying needs with ease and convenience. Besides, with the HP Smart app, you can print, scan, and copy from anywhere. ",
        price: 10999,
    },
    {
        name:"HP LaserJet Tank MFP 1005w Printer Multi-function WiFi Monochrome Laser Printer  (Toner Cartridge)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p8/3.png?raw=true",
        info:"1 year Onsite warranty from the date of purchase",
        description:"  Whether you use it at home or in an office setting, you can print documents while saving time and effort with the HP LaserJet Tank MFP 1005w Printer. It is an essential tool for delivering high-quality prints with sharp text and rich black colours consistently. Additionally, this printer offers the convenience of printing, scanning, and copying documents to help streamline your daily workflow. Furthermore, this printer is designed for easy maintenance, allowing you to print up to 50000 pages before needing to replace the imaging drum.",
        price: 20499,
    },
    {
        name:"Canon PIXMA MegaTank/Ink Efficient G4770 Multi-function WiFi Color Ink Tank Printer with Black (135 ml) & Color (70 ml) ink bottles  (4 Ink Bottles Included)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p9/3.png?raw=true",
        info:"1 Year or 30,000 Prints (which ever is earlier) Onsite warranty from the date of purchase",
        description:"The Canon printer is made for simple printing, so you can use it without altercation and complete your work assignment quickly. The ink bottle's nozzles are all specially crafted to fit into the appropriate ink tanks, preventing mixing mistakes and enabling a flawless ink refill operation. Moreover, up to 35 sheets of original paperwork may be loaded for batch scanning and photocopying to prevent continually opening and closing the scanner lid. With the free Canon Print Inkjet/SELPHY and Canon Easy-PhotoPrint Editor programmes, you can also easily print from smartphones, tablets, desktops, and cloud storage.",
        price: 20988,
    },
    {
        name:"Epson L4260 Multi-function WiFi Color Ink Tank Printer (Color Page Cost: 30 Paise | Black Page Cost: 12 Paise) with extended warranty of 3 years or 30,000 pages*  (4 Ink Bottles Included)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/printer/p10/3.png?raw=true",
        info:"1 years or 30,000 pages whichever comes early. Please register you product with us: https://customer.epson.co.in/customer/ewarranty.do#/reg/IN",
        description:"This sleek black EcoTank L4260 printer is in a class of its own. It comes with an integrated ink tank system and is compact enough to fit perfectly in small spaces. Equipped with auto-duplex printing, you can print on both sides of the paper easily, significantly reducing paper cost and wastage.",
        price: 21970,
    },
];
module.exports = { data:printerData};
