const smatewatchData=[
    {
        name:"Fastrack Revoltt FS1 Pro|World's First,1.96 Super AMOLED|Highest Resolution|BT Calling Smartwatch  (Black Strap, Free Size)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw1/3.png?raw=true",
        info:"1 Year Limited warranty  Covered in Warranty  Manufacturing Defects  Not Covered in Warranty  Physical Damage",
        description:"You can experience the utmost convenience and functionality with the Fastrack Revoltt FS1 Pro Smartwatch. Featuring up to a 4.978 cm (1.96) Super AMOLED arched display, this smartwatch offers a clear and vivid visual experience. This smartwatch delivers an exceptional visual experience by rendering bold colours with a high pixel resolution. Furthermore, with its arched design, this smartwatch provides an optimal viewing experience that is both immersive and visually appealing.",
        price: 2499,
    },
    {
        name:"Fastrack Revoltt FS1+|2.01'' Biggest UltraVU Display|Industry Best 950 Nits|BT Calling Smartwatch  (Black Strap, Free Size)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw2/3.png?raw=true",
        info:"1 Year Limited warranty  Covered in Warranty  Manufacturing Defects  Not Covered in Warranty  Physical Damage",
        description:"Large 2.01 UltraVU Display with 950 nits Brightness, SingleSync BT Calling, 110+ Multisports, Sleep Monitor with REM Sleep, Auto Stress Monitor, 24*7 HRM, SpO2, Womens Health, Music & Camera Control, In-Built Alarm, Stopwatch & Timer, In-Built Games, Multiple Menu Styles, IP68 Water Resistance, 200+ Watchfaces, 7 Days Battery",
        price: 1799,
    },
    {
        name:"Noise Colorfit Icon 2 1.8'' Display with Bluetooth Calling, AI Voice Assistant Smartwatch  (Black Strap, Regular)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw3/3.png?raw=true",
        info:"1 Year Manufacturer Warranty Covered in Warranty  Manufacturing Defects  Not Covered in Warranty Physical Damage",
        description:"1.8 LCD display   Bluetooth Calling Smartwatch with AI voice assistance  Noise Health SuiteTM: Blood Oxygen, 24*7 Heart rate monitor, Stress Monitor and Sleep Monitor  60 Sports mode & 100+ watch faces  NoiseFit app: Pair with the improved Noisefit app for better health insights With Call Function  Touchscreen  Fitness & Outdoor  Battery Runtime: Upto 7 days",
        price: 1299,
    },
    {
        name:"Noise Vision 3 with 1.96 AMOLED display with Thin Bezel, Metallic Build Smartwatch  (Metallic Black Strap, Regular)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw4/3.png?raw=true",
        info:"1 Year Manufacturer Warranty Covered in Warranty  Manufacturing Defects  Not Covered in Warranty Physical Damage",
        description:"With Call Function Touchscreen Fitness & Outdoor Battery Runtime: Upto 7 days Size   Regular   Touchscreen Yes  Water Resistant Yes Usage Fitness & OutdoorIdeal ForMen & WomenCompatible OSAndroid & iOS Brand Strap Color Metallic Black",
        price: 3499,
    },
    {
        name:"shopevolves Evolves Nextfit Hello 1.69'' HD, Metal Dial, BT Calling,150+ Face Smartwatch  (Gold Strap, Medium)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw5/3.png?raw=true",
        info:"12 months limited warranty against manufacturing defects",
        description:"Shopevolves Evolves NextFIT HELLO is a smartwatch that is fully packed with features. Its 1.69-inch HIGH-resolution DISPLAY with CNC cutting lathe tempered glass is absolutely stunning, its alloy body and carbon fiber back make it a sporty rugged beauty. Its 240x280 high definition display makes everything crisp and smooth and clearly visible under sunlight. The colors are super accurate and cover 98% of the color gamut. The full-touch UI is a breeze to operate. It includes sensors like a step counter and intelligent",
        price: 3689,
    },
    {
        name:"boAt Wave Fury with 1.83'' HD Display, Bluetooth Calling & Functional Crown Smartwatch  (Black Strap, Free Size)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw6/Screenshot%202024-04-14%20215237.png?raw=true",
        info:" 1 year warranty from the date of purchase  Covered in Warranty   Manufacturing Defects   boAt   boAt is an Indian lifestyle brand that deals in fashionable consumer electronics like- earphones, headphones, speakers,travel charger & premium rugged cables.",
        description:"The boAt Wave Fury, with its 1.83HD display and 500+ sports modes, is the ideal partner for your fitness transformation. This watch also comes with bluetooth calling which helps you stay connected to your closed ones. You can always stay on top of your vitals thanks to the watch's heart rate and SpO2 monitoring functions. With its functional crown you may scroll, zoom, and select with a twist and a tap. With IP67 dust, sweat, and splash resistance, nothing can stop you, regardless of how sunny or cloudy the day may be.",
        price: 1499,
    },
    {
        name:"boAt Storm Call 2 1.83'' HD Display,BT Calling,boAt Coins & DIY Watch Face Studio Smartwatch  (Metal Black Strap, Free Size)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw7/Screenshot%202024-04-14%20215538.png?raw=true",
        info:"1 Year Warranty from the Date of Purchase Covered in Warranty  Manufacturing Defects  Not Covered in Warranty  Physical Damages  boAt  boAt is an Indian lifestyle brand that deals in fashionable consumer electronics like- earphones, headphones, speakers,travel charger & premium rugged cables.",
        description:"The boAt Storm Call 2 is here to simplify your life and become your fitness transformation partner This is going to get clear of any obstacles that may get in the way of your goals.The 1.83'' HD display makes everything a vibrant and vivid appeal. Thanks to the Advanced Bluetooth calling feature, you can stay in touch with your loved ones wherever you go. With its boAt Coins you may avail coupons based on fitness activities.",
        price: 1499,
    },
    {
        name:"boAt Ultima Connect Max with 2.0 HD Display, BT Calling and 100+ Sports Modes Smartwatch  (Active Black Strap, Free Size)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw8/3.png?raw=true",
        info:"1 Year Warranty from the Date of Purchase Covered in Warranty  Manufacturing Defects  Not Covered in Warranty  Physical Damages  boAt  boAt is an Indian lifestyle brand that deals in fashionable consumer electronics like- earphones, headphones, speakers,travel charger & premium rugged cables",
        description:"   The boAt Ultima connect max is your new fitness partner and is here to simplify your life. Thus, being your best friend who will keep you going. Everything comes to life with its flawless and durable 2 inches HD display. With just one tap, you can stay in touch with your loved ones thanks to the advanced Bluetooth calling feature. The built-in games keeps your inner child alive. No matter how sunny or cloudy the day is, nothing can stop you with IP68 dust, sweat, and splash resistance. Moreover, the multiple sports mode will never let you miss out on your fitness routine.",
        price: 1377,
    },
    {
        name:"Ciberer BTALK2 1.43 AMOLED Display, Bluetooth Calling, 7 Days Battery, Men Women Premium Smartwatch  (Black Strap, Free Size)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw9/3.png?raw=true",
        info:" 1 Year of Manufacturing Warranty Email at ciberer@jtplraj.com or visit www.ciberer.in",
        description:" The Ciberer Btalk 2 stands out as a sleek and stylish smartwatch that seamlessly blends premium craftsmanship with an array of impressive features. Its slim and lightweight design, meticulously hand-polished stainless steel frame, and a bezel-less Ultra HD AMOLED display create an exquisite fusion of form and function. Elevating its utility, this smartwatch excels in health and fitness tracking, featuring continuous wrist-based heart",
        price: 3689,
    },
    {
        name:"Fire-Boltt Hulk 1.78 inch Amoled Bluetooth Calling with 120 sports modes Smartwatch  (Black Strap, 1.78)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/smart%20watch/sw10/3.png?raw=true",
        info:"Covers Manufacturing Defects  Covered in Warranty  Manufacturing Defect  Not Covered in Warranty  Physical & Water Damage",
        description:"Fire-Boltt Hulk smartwatch is a Bluetooth calling smart watch with an AMOLED display having 550 Nits Peak Brightness and inbuilt AI Assistant. The watch comes with a built-in mic and speaker for hd calling experience as well as listen to your favorite tunes. With a large 1.78 Display this watch has a 368 x 448 pixel high resolution for smooth and clear swipes and touch.",
        price: 2199,
    },
];
module.exports = { data: smatewatchData};