const WirelesschargersData=[
    {
        name:"UNIGEN MAGTEC 500 23W MagSafe Stand for iPhone 12/13/14/AirPods/Apple Watches Charging Pad",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc1/3.png?raw=true",
        info:"For: iPhone 15/14/13/12 Series, All Wireless Compatible Devices, All Apple Watches, Airpods Pro/3/Airpods Pro2 Indicator Present Color: Black",
        description:"The UNIGEN MAGTEC 500 15W 5 in 1 Magsafe Charging Station is a sleek and versatile solution for charging multiple Apple devices, including iPhone 15/14/13/12 series, All Apple Watches and AirPods 3 to Pro. With MagSafe technology for secure charging, it also features a built-in LED lamp and an extra USB port for simultaneous charging of other devices. The 15W power output ensures fast and efficient charging, making it a convenient and functional accessory for Apple users.",
        price: 3499,
    },
    {
        name:"boAt floAtpad 350 Qi Certified r with 6mm Transmission Range & 1 Type C Output Cable Charging Pad",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc2/3.png?raw=true",
        info:"1 Year Warranty from the Date of Purchase.Covered in Warranty  Physical Damage  Not Covered in Warranty  Manufacturing Defects",
        description:"  The floAtpad 350 Wireless charger by boAt is here to power up your cherished devices. This slim, lightweight and ultra-portable wireless charger will revolutionize the way you power up your devices and your life. The 6 mm transmission range on the wireless surface allows your devices to charge towards the future seamlessly. Moreover, the no slip grip on the wireless charging surface keeps your devices in place when being charged. The Wireless Output ranges between 5W, 7.5W, 10W and 15W and is Qi certified for safety, efficacy and compatibility with all wireless type devices.",
        price: 1299,
    },
    {
        name:"Portronics Freedom 4A Desktop Wired & Wireless Charging Pad",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc3/3.png?raw=true",
        info:"1 Year Manufacture Warranty  Covered in Warranty Manufacturing Defects  Not Covered in Warrant Physically Damaged",
        description:" Introducing the Portronics Freedom 4A - a multifunctional 15W wireless charger with a built-in digital alarm clock. Fast and efficient, it charges your devices rapidly in just 45 minutes, compatible with the iPhone series (12 and above) and other Qi-enabled devices. The ruggedly built charger ensures safety from surges, overvoltage, and overheating, while its compact design and lightweight body make it perfect for both home and office use. Set alarms, switch between 12/24 Hours modes, and adjust brightness with ease. Stay connected anywhere with this reliable and elegant charging solution.",
        price: 1299,
    },
    {
        name:"Qubo Z3 3-in-1 Magsafe Portable Travel Wireless 15W Fast Charging Pad",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc4/3.png?raw=true",
        info:"For: Iphone 12 Mini, Iphone 12, Iphone 12 Pro, Iphone 13 Mini, Iphone 13, Iphone 13 Pro, Iphone 13 Pro Max, Iphone 14, Iphone 14 Plus, Iphone 14 Pro, Iphone 14 Pro Max, Air Pods 2,3,Pro,Pro2, Apple Watch Ultra 8,7,6,5,4,SE, Color: Black",
        description:" Introducing the Portronics Freedom 4A - a multifunctional 15W wireless charger with a built-in digital alarm clock. Fast and efficient, it charges your devices rapidly in just 45 minutes, compatible with the iPhone series (12 and above) and other Qi-enabled devices. The ruggedly built charger ensures safety from surges, overvoltage, and overheating, while its compact design and lightweight body make it perfect for both home and office use. Set alarms, switch between 12/24 Hours modes, and adjust brightness with ease. Stay connected anywhere with this reliable and elegant charging solution.",
        price: 3199,
    },
    {
        name:"SAMSUNG Original Wireless Charger Duo Pad Charging Pad",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc5/3.png?raw=true",
        info:"For: Samsung Galaxy Fold, Samsung S21 Indicator Present Color: Black Input Current: 2.77 A",
        description:"The floAtpad 350 Wireless charger by boAt is here to power up your cherished devices. This slim, lightweight and ultra-portable wireless charger will revolutionize the way you power up your devices and your life. The 6 mm transmission range on the wireless surface allows your devices to charge towards the future seamlessly. Moreover, the no slip grip on the wireless charging surface keeps your devices in place when being charged. The Wireless Output ranges between 5W, 7.5W, 10W and 15W and is Qi certified for safety, efficacy and compatibility with all wireless type devices.",
        price: 4390,
    },
    {
        name:"RAEGR Arc 1500 UVC Disinfection Box Sterilizer Capsule with 10W Qi Fast Wireless Charger, Phone Sanitizer Sterilizer for All Smartphones / Watches / Masks & Other Personal Items Charging Pad",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc6/3.png?raw=true",
        info:"For: Cellular Phones Indicator Present Rechargeable Battery Color: White",
        description:"Three Modes of Fast Wireless charging : 10W / 7.5W & 5W. Compatible with all Qi Enabled Phones. Also Charges Mag-Safe compatible devices like iPhone 14/13/12 series,but the device might get slightly warm during the charging process due to the presence of magnets near the coil area,which is quite normal.",
        price: 4999,
    },
   
    {
        name:"Spigen AMP02797 Charging Pad",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc7/3.png?raw=true",
        info:"For: Cellular Phones Indicator Present Rechargeable Battery Color: White",
        description:"Spigen Mag Fit Duo Designed for MagSafe Charger Stand for iPhone 14, iPhone 13, iPhone 12 Models/Apple Watch Stand for All Series/Airpods MagSafe Charging Case - White",
        price: 1749,
    },
    {
        name:"RAEGR RG10215 MagFix Arc M1320 15W Foldable Mag-Safe Compatible Wireless Charger, Magnetic Wireless Charging Pad Compatible with Mag-Safe Charging Pad",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc8/3.png?raw=true",
        info:"1 Year Manufacture Warranty  Covered in Warranty Manufacturing Defects  Not Covered in Warrant Physically Damaged",
        description:"Designed For iPhone 12, 13, 14 and 15 Series] The magnetic 15W wireless charger delivers a unique experience toiphone 15 Series iPhone 14 / iPhone 14 Plus / iPhone 14 Pro / iPhone 14 Pro Max / iPhone 13 Mini / iPhone 13 / 13 Pro / iPhone 13 Pro Max / iPhone 12 Mini / iPhone 12 / iPhone 12 Pro / iPhone 12 Pro Max. Featuring an array of magnets around the wireless charging coil, optimized for alignment and efficiency, improves wireless charging for a better, more efficient experience. Your device might get warm while Wirelessly charging your device. These conditions are normal, and your device will return to a regular temperature when the charging process is complete . ",
        price: 2989,
    },
    {
        name:"ZEBRONICS Zeb-MAGSECURE Charging Pad",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc9/3.png?raw=true",
        info:"For: iPhone 12 mini, iPhone 12, iPhone 12 Pro, iPhone 12 Pro Max, iPhone 11, iPhone 11 Pro, iPhone 11 Pro Max, AirPods Pro, AirPods with Wireless Charging Case Color: Black",
        description:"Zebronics ZEB-MagSecure Wireless Magnteic Pad comes with a 15W Charging Power to charge supported Phones, TWS Earbuds wirelessly. It supports iPhone 12 mini, iPhone 12, iPhone 12 Pro, iPhone 12 Pro Max, iPhone 11, iPhone 11 Pro, iPhone 11 Pro Max, AirPods Pro, AirPods with Wireless Charging Case. Smartphones with wireless charging feature can also be charged on the Zeb-MagSecure, also TWS Earbuds with Wireless Charging Case.",
        price: 1305,
    },
    {
        name:"powerup stay charged Powerup® High-Speed Qi Wireless Charger Pad 10W Dual Coil for iPhone SE 2020 All Qi-enabled Devices - Grey Charging Pad",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/smart%20gadget/wireless%20chargers/wc10/3.png?raw=true",
        info:"For: All Smartphones and iPhones Indicator Present  Color: Grey Input Current: 1.8 A",
        description:" Brand: Powerup Stay Charged | Colour: Silver | Compatibility: Compatible with all Qi Enables Devices Powerup High-Speed Dual Coil Wireless Charger Qi Fast Charging Station Simplify your space with this wireless charging Pad. This charger uses Qi- transmitting coils to deliver charge to your phone wirelessly. ",
        price: 1911,
    },
];
module.exports = { data: WirelesschargersData};
