const airCoolerData=[
    {
        name:"Hindware 125 L Desert Air Cooler  (Black & White, Powerstorm 125L)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac1/3.png?raw=true",
        info:"1 Year on-site warranty by Hindware",
        description:"Parts: Outer Cabinet and Plastic Parts. Any Accessories External to the Product. The Product is Not Used according to the Instructions Given in the Instructions Manual. Defects Caused By Improper Use as Determined By the Company Personnel. Modification or Alteration of any Nature Made in the Electrical Circuitry or Physical Construction of the Set. Site (Where the Premises is Kept) Conditions that Do not Confirm to the Recommended Operating Conditions of the Product. The Serial Number is Removed, Altered or Obliterated from the Product. Defects Due to Cause Beyond Control Like Lightning, Abnormal Voltage, Acts of God or While in Transit to the Service Centers or Purchaser's Residence",
        price: 13499,
    },
    {
        name:"Hindware 90 L Desert Air Cooler  (Turquoise, White, I-fold)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac2/3.png?raw=true",
        info:"1 Year from the Date of Sale",
        description:"Warranty Does Not Cover Any Damage to Product or Parts Due to Agent User Misuse, Negligence, Accident, Improper Maintenance, Aggressive Cleaning Chemicals, Unauthorized Alterations to the Product, Normal Wear and Tear. Warranty is Not Valid for Products or Parts that Do Not Use Original SHIL Spare Parts, Repaired by Unauthorized Persons",
        price: 15819,
    },
    {
        name:"Kenstar 120 L Desert Air Cooler  (Grey, Cool Grande HC 120)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac3/3.png?raw=true",
        info:"1 Year Warranty on product",
        description:"Kenstar is a name that stands for international quality, style and durability. With an impressive product range, Kenstar enjoys the position of being one of the most preferred premium brands in India.Studies have shown that the Indian consumer needs are evolving. The consumer now wants premium quality at an optimum price and is open to accepting new product categories with sound technical support and trustworthy brands.",
        price: 11399,
    },
    {
        name:"Orient Electric 125 L Desert Air Cooler  (White, Smartchill 125L desert cooler)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac4/3.png?raw=true",
        info:"1 YEAR Warranty ",
        description:"Orient Electric Limited (OEL) is part of the diversified Indian conglomerate CK Birla Group. A distinguished name in the Indian fan industry for more than 60 years, Orient Electric has today established itself in the market as a one-stop brand for lifestyle electrical solutions which include fans, Lighting, Home Appliances and Switchgears.Orient Electric takes pride in its R&D capabilities, spirit of continuous innovation and commitment to manufacture cutting-edge lifestyle electrical products that meet the needs and expectations of new age consumers.",
        price: 13499,
    },
    {
        name:"Orient Electric 85 L Desert Air Cooler with Aerofan technology,Densenest Honeycomb design  (White, Black, Snowbreeze Magnus Neo 85/CD8502H)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac5/3.png?raw=true",
        info:"1 Year Warranty",
        description:"Orient Electric Limited (OEL) is part of the diversified Indian conglomerate CK Birla Group. A distinguished name in the Indian fan industry for more than 60 years, Orient Electric has today established itself in the market as a one-stop brand for lifestyle electrical solutions which include fans, Lighting, Home Appliances and Switchgears.Orient Electric takes pride in its R&D capabilities, spirit of continuous innovation and commitment to manufacture cutting-edge lifestyle electrical products that meet the needs and expectations of new age consumers.",
        price: 15289,
    },
    {
        name:"Symphony 75 L Desert Air Cooler  (White, Sumo75xl)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac6/3.png?raw=true",
        info:"1 Year Brand Warranty",
        description:"Specially engineered with a unique +Air Fan that produces strong and uniform air to fill the entire room with cool air instantly. Its honeycomb cooling pads with high water retention capacity and efficient cool flow dispenser to distribute water evenly help cool hot air quickly to provide enhanced cooling. For better performance change the pads regularly. Designed with ergonomic dial knobs for ease of use and a premium appearance. The multi-directional wheels of this air cooler facilitate easy movement from one place to another, making it suitable for both indoors and outdoors usage. Power consumption of this energy-efficient cooler is roughly 190 watts which makes it cost-effective and compatible to be used with inverters. So drop your worries about expensive electric bills or power cuts and enjoy fresh and cool air this summer.",
        price: 13999,
    },
    {
        name:"Orient Electric 50 L Window Air Cooler  (White, Magicool DX - CW5002B)#JustHere",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac7/3.png?raw=true",
        info:"1 Year Brand Warranty",
        description:"Orient Electric Limited (OEL) is part of the diversified Indian conglomerate CK Birla Group. A distinguished name in the Indian fan industry for more than 60 years, Orient Electric has today established itself in the market as a one-stop brand for lifestyle electrical solutions which include fans, Lighting, Home Appliances and Switchgears.Orient Electric takes pride in its R&D capabilities, spirit of continuous innovation and commitment to manufacture cutting-edge lifestyle electrical products that meet the needs and expectations of new age consumers.",
        price: 6799,
    },
    {
        name:"Symphony 80 L Room/Personal Air Cooler  (White, touch)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac8/3.png?raw=true",
        info:"1 year warranty",
        description:"The future of air cooling is here! A yet another innovation from Symphony, the world's largest brand in air cooling, Symphony Touch 55 is loaded with new age features like 6 aspen pads, fully closable louvers and cassette type removable pads that are unheard of in the domain of air cooling. With its stunning looks, 4-side cooling pads and powerful cooling aided by double blower, this technological marvel will surely lure you to Touch it.",
        price: 16499,
    },
    {
        name:"BAJAJ 70 L Desert Air Cooler  (White, Shield Series Chisel 70-480137)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac9/3.png?raw=true",
        info:"1 Years Warranty",
        description:"BAJAJ SHIELD SERIES CHISEL 70-480137 comes with 70lt storage capacity with 3 Side Cooler Master and Double Side Water Inlet.",
        price: 10799,
    },
    {
        
        name:"Voltas 36 L Room/Personal Air Cooler  (Grey & White, Delite 36)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/air%20cooler/ac10/3.png?raw=true",
        info:"1 Year Warranty",
        description:"Voltas is India's largest air conditioning company, and one of the world's premier engineering solutions providers and project specialists.",
        price: 6499,
    },
];
module.exports = {data:airCoolerData};


