const cellingFanData=[
    {
        name:"Crompton TRIGGER GLOW 1.2 M 1200 mm Remote Controlled 4 Blade Ceiling Fan  (ANTIQUE BRASS, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf1/3.png?raw=true",
        info:"2 Year company Warranty",
        description:"Crompton Greaves Consumer Electricals Ltd. manufactures and markets a wide spectrum of consumer products ranging from fans, light sources and luminaires, pumps and household appliances, such as geysers, mixer_grinder_juicers, toasters and irons. Crompton has been the market leader in fans, domestic pumps and street lighting for over 20 years. It has manufacturing locations in Goa, Vadodara, Ahmednagar and Baddi.",
        price: 5799,
    },
    {
        name:"Crompton Silentpro Enso_ 1225 mm 3 Blade Ceiling Fan  (Silk White, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf2/3.png?raw=true",
        info:"5 Year Company Warranty",
        description:"Crompton Greaves Consumer Electricals Ltd. manufactures and markets a wide spectrum of consumer products ranging from fans, light sources and luminaires, pumps and household appliances, such as geysers, mixer_grinder_juicers, toasters and irons. Crompton has been the market leader in fans, domestic pumps and street lighting for over 20 years. It has manufacturing locations in Goa, Vadodara, Ahmednagar and Baddi. Crompton products are available in nearly 150,000 retail points across the country. The business is rapidly expanding into new categories and expanding it's Reach.",
        price: 6399,
    },
    {
        name:"LUMINOUS Jaipur Mahal 1 Star 1320 mm 3 Blade Ceiling Fan  (Tan Brown, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf3/3.png?raw=true",
        info:"2 Years company warranty",
        description:"You can stay cool and relaxed even during summers with the Luminous Jaipur Mahal Ceiling Fan. Its wide sweep size of up to 1300 mm and air delivery of 230 CMM help spread air to each corner of the room to ensure proper ventilation. Also, with high speeds of up to 320 RPM, this ceiling fan powerfully circulates a breeze to ensure optimal comfort. Furthermore, designed with ultraviolet metallizing, it looks elegant and modern on the ceiling of any room.",
        price: 5299,
    },
    {
        name:"Atomberg Renesa+ Ceiling Fan 5 Star 1200 mm BLDC Motor with Remote 3 Blade Ceiling Fan  (Golden Oak, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf4/3.png?raw=true",
        info:"2+1 Years On-Site Warranty",
        description:"Atomberg Renesa+ fan features energy-efficient BLDC technology, providing superior air delivery of 235 CMM at 360 RPM (at top speed) while consuming only 35W (at top speed). With a 5-star rating, it saves up to 65% in electricity consumption. It includes a convenient IR Remote for easy control of speed and has unique features like boost mode, timer and sleep mode. With its wooden finish blades, sleek design and LED speed indicator, the Renesa+ adds a modern touch to your room decor. It provides consistent speed during voltage fluctuations. It is easy-to-clean, maintain and is corrosion-resistant. The fan comes with a 2+1 year warranty.",
        price: 4999,
    },
    {
        name:"HAVELLS Leganza (52Watt) 1 Star 1200 mm Ultra High Speed 4 Blade Ceiling Fan  (bronze gold, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf5/3.png?raw=true",
        info:"2 Years company warranty",
        description:"Havells India Limited is a leading Fast Moving Electrical Goods (FMEG) Company and a major power distribution equipment manufacturer with a strong global presence. Havells enjoys enviable market dominance across a wide spectrum of products, including Industrial & Domestic Circuit Protection Devices, Cables & Wires, Motors, fans, Modular Switches, Home Appliances, Air Conditioners, Electric Water Heaters, Power Capacitors, Luminaires for Domestic, Commercial and Industrial Applications.",
        price: 4099,
    },
    {
        name:"LUMINOUS JAIPUR GANGAUR ABU BLACK-1-STAR 1200 mm Silent Operation 3 Blade Ceiling Fan  (Abu Black, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf6/3.png?raw=true",
        info:"2 Years company warranty",
        description:"LIGHTWEIGHT ALUMINIUM MATERIAL: Low-density Aluminium helps make this ceiling fan lightweight to provide a superior air throw while being easy to clean. STRONG MOTOR The strong copper coil motor spins at 380 revolutions per minute (RPM), delivering 230 CMM of airflow for your comfort. The premium-quality material also enhances heat dissipation for more efficiency. ELEGANT DESIGN: An artistically crafted art design is created in the image of the “Trinetra” form – an indication of the 3 eyes of Lord Shiva or Goddess Durga giving a sophisticated and premium look. POWER CONSUMPTION: This ceiling fan's sophisticated architecture allows it to use only 75 W of power, so you won't have to worry about excessive electricity costs.",
        price: 3631,
    },
    {
        name:"Polycab Superia Lite 02 3 Star 1200 mm Underlight 5 Blade Ceiling Fan  (Brown21, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf7/3.png?raw=true",
        info:"2 Year Company Warranty",
        description:"You can enjoy a cool breeze at all times with the Polycab Superia Lite SP02 Ceiling Fan. It is built with a 1200 mm sweep size and offers an air delivery rate of up to 210 cubic metres per minute for enhanced airflow in all corners of the room. This ceiling fan offers high speeds of up to 340 RPM to offer cool air instantly. Moreover, with its pull-cord mechanism, this ceiling fan lets you adjust its speeds as it gives you three options to choose from.",
        price: 10299,
    },
    {
        name:"Orient Electric AEROSLIM 1200 MM 1200 mm Silent Operation 3 Blade Ceiling Fan  (FLAME GOLD, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf8/3.png?raw=true",
        info:"3 Years Domestic Warranty on Product",
        description:"Orient Electric Limited (OEL) is part of the diversified Indian conglomerate CK Birla Group. A distinguished name in the Indian fan industry for more than 60 years, Orient Electric has today established itself in the market as a one-stop brand for lifestyle electrical solutions which include fans, Lighting, Home Appliances and Switchgears.Orient Electric takes pride in its R&D capabilities, spirit of continuous innovation and commitment to manufacture cutting-edge lifestyle electrical products that meet the needs and expectations of new age consumers. It has fully integrated manufacturing facilities based in Kolkata, Faridabad, Noida and Guwahati. ",
        price: 10290,
    },
    {
        name:"HAVELLS Festiva 1200 mm Anti Dust 3 Blade Ceiling Fan  (Blue, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf9/3.png?raw=true",
        info:"2 Year Company Warranty",
        description:"Havells India Limited is a leading Fast Moving Electrical Goods (FMEG) Company and a major power distribution equipment manufacturer with a strong global presence. Havells enjoys enviable market dominance across a wide spectrum of products, including Industrial & Domestic Circuit Protection Devices, Cables & Wires, Motors, fans, Modular Switches, Home Appliances, Air Conditioners, Electric Water Heaters, Power Capacitors, Luminaires for Domestic, Commercial and Industrial Applications.",
        price: 3649,
    },
    {
        name:"Orient Electric Wendy 1 Star 1200 mm Ultra High Speed 3 Blade Ceiling Fan  (Blue Silver, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/celling%20fan/cf10/3.png?raw=true",
        info:"2 Years Warranty",
        description:"Orient Electric Limited (OEL) is part of the diversified Indian conglomerate CK Birla Group. A distinguished name in the Indian fan industry for more than 60 years, Orient Electric has today established itself in the market as a one-stop brand for lifestyle electrical solutions which include fans, Lighting, Home Appliances and Switchgears.Orient Electric takes pride in its R&D capabilities, spirit of continuous innovation and commitment to manufacture cutting-edge lifestyle electrical products that meet the needs and expectations of new age consumers. It has fully integrated manufacturing facilities based in Kolkata, Faridabad, Noida and Guwahati. It is largest manufacturer and exporter of fans from India with a dominating presence in over 35 international markets.",
        price: 4299,
    },
];
module.exports = { data:cellingFanData};
