const tableFanData=[
    {
        name:"Orient Electric Stand 82 400 mm Energy Saving 3 Blade Pedestal Fan  (Crystal white, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf1/3.png?raw=true",
        info:"1 Year Company Domestic Warranty",
        description:"Orient Electric Limited (OEL) is part of the diversified Indian conglomerate CK Birla Group. A distinguished name in the Indian fan industry for more than 60 years, Orient Electric has today established itself in the market as a one-stop brand for lifestyle electrical solutions which include fans, Lighting, Home Appliances and Switchgears.Orient Electric takes pride in its R&D capabilities, spirit of continuous innovation and commitment to manufacture cutting-edge lifestyle electrical products that meet the needs and expectations of new age consumers. It has fully integrated manufacturing facilities based in Kolkata, Faridabad, Noida and Guwahati. It is largest manufacturer and exporter of fans from India with a dominating presence in over 35 international markets.",
        price: 2349,
    },
    {
        name:"zigma Bullet Heavy Duty ISI CERTIFIED 400 mm Ultra High Speed 3 Blade Pedestal Fan  (Black, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf2/3.png?raw=true",
        info:"1 Year Company Domestic Warranty",
        description:"You can keep yourself cool and comfortable while working, studying, or sleeping with the Zigma Bullet Pedestal Fan. Built with a high-torque motor, it provides excellent performance and longevity. Additionally, this pedestal fan's powder-coated, seven-tank body protects against corrosion while simultaneously providing long-lasting durability. Moreover, with a bird guard, this pedestal fan keeps foreign objects out when it's running and ensures good blade function.",
        price: 1600,
    },
    {
        name:"zigma Charm Anti Dust 12`` 300 mm Ultra High Speed 4 Blade Wall Fan  (Black, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf3/3.png?raw=true",
        info: "1 Year Company Domestic Warranty",     
        description:"Keep your space filled with air at all times with the Zigma Charm Wall Fan. It is equipped with four leaf-like aerodynamically designed blades that offer a high air delivery rate of up to 110 cubic metres per minute to ensure quiet operation and optimal performance. This wall fan offers high speeds of up to 2400 RPM to offer cool air in a jiffy. Moreover, thanks to its synchronous motor, this wall fan ensures smooth oscillation to deliver uniform airflow across the space.",
        price: 1500,
    },
    {
        name:"V-Guard Esfera STS Plus (Yellow Black) 2 in 1 Convertible Fan 400 mm 3 Blade Pedestal Fan  (Yellow Black, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf4/3.png?raw=true",
        info:"2 Year Domestic Warranty",
        description:"f you're looking for a pedestal fan that can provide a cool breeze uniformly, the V-Guard Esfera STS Pedestal Fan might be just what you need. Its three 400 mm aerodynamic blades spin at speeds of up to 1350 RPM, giving you excellent cooling power. Additionally, this pedestal fan’s air delivery rate is also impressive, making sure every nook and cranny of the room gets cooled down in no time. What's more, its powerful copper motor comes with a durable lamination to ensure efficiency and durability. ",
        price: 4999,
    },
    {
        name:"V-Guard Esfera Remote with Timer and Remote Control Operation 400 mm 3 Blade Pedestal Fan  (Orange, Black, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf5/2.png?raw=true ",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf5/3.png?raw=true",
        info:"2 Year Domestic Warranty",
        description:"At V-Guard, we are building products of tomorrow, inspired by the consumer experiences of today. Products that are designed keeping the consumer at the forefront. Thus, by bringing innovation in our products, we are not just delivering household utilities, but meaningful experiences, that promise to bring home a better tomorrow.",
        price: 3249,
    },
    {
        name:"Orient Electric stand 32 3 Blade Pedestal Fan  (peppy red, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf6/3.png?raw=true",
        info:"2 year warranty",
        description:"Orient Electric Limited (OEL) is part of the diversified Indian conglomerate CK Birla Group. A distinguished name in the Indian fan industry for more than 60 years, Orient Electric has today established itself in the market as a one-stop brand for lifestyle electrical solutions which include fans, Lighting, Home Appliances and Switchgears.Orient Electric takes pride in its R&D capabilities, spirit of continuous innovation and commitment to manufacture cutting-edge lifestyle electrical products that meet the needs and expectations of new age consumers. It has fully integrated manufacturing facilities based in Kolkata, Faridabad, Noida and Guwahati. ",
        price: 3135,
    },
    {
        name:"ORBIT Hercules-Red 4 Star 400 mm Silent Operation 3 Blade Pedestal Fan  (Red, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf7/3.png?raw=true",
        info:"1 year warranty",
        description:"Get your air feeling fresh with the orbit 16 inch oscillating stand fan. This oscillating fan has 3 speed settings, allowing you to circulate the air at your pleasure. You can adjust the height and tilt the head of this fan. This oscillation fan is light enough to move easily and heavy enough to stand firm. Designed to withstand voltage fluctuations, this fan has a powerful motor that boasts of a speed of 1400 RPM to deliver high airflow. The aerodynamically-designed blades allow better air circulation, while the low-noise operation of the powerful motor helps maintain a peaceful environment at all times.",
        price: 2224,
    },
    {
        name:"Orient Electric WALL14 HIGH SPEED WALL MOUNT FAN 300 mm 3 Blade Wall Fan  (WHITE & LIGHT BLUE BLADE, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf8/3.png?raw=true",
        info:"2 YEAR WARRANTY",
        description:"Orient Electric Limited (OEL) is part of the diversified Indian conglomerate CK Birla Group. A distinguished name in the Indian fan industry for more than 60 years, Orient Electric has today established itself in the market as a one-stop brand for lifestyle electrical solutions which include fans, Lighting, Home Appliances and Switchgears.Orient Electric takes pride in its R&D capabilities, spirit of continuous innovation and commitment to manufacture cutting-edge lifestyle electrical products that meet the needs and expectations of new age consumers. It has fully integrated manufacturing facilities based in Kolkata, Faridabad, Noida and Guwahati. It is largest manufacturer and exporter of fans from India with a dominating presence in over 35 international markets. ",
        price: 2798,
    },
    {
        name:"Orient Electric Wall 11 300 mm 3 Blade Wall Fan  (White, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf9/3.png?raw=true",
        info:"2 years warranty",
        description:"Orient Electric Limited (OEL) is part of the diversified Indian conglomerate CK Birla Group. A distinguished name in the Indian fan industry for more than 60 years, Orient Electric has today established itself in the market as a one-stop brand for lifestyle electrical solutions which include fans, Lighting, Home Appliances and Switchgears.Orient Electric takes pride in its R&D capabilities, spirit of continuous innovation and commitment to manufacture cutting-edge lifestyle electrical products that meet the needs and expectations of new age consumers. It has fully integrated manufacturing facilities based in Kolkata, Faridabad, Noida and Guwahati. It is largest manufacturer and exporter of fans from India with a dominating presence in over 35 international markets. ",
        price: 2700,
    },
    {
        name:"V-Guard Gatimaan HSW N (Orange Black) 400 mm Ultra High Speed 3 Blade Wall Fan  (Orange Black, Pack of 1)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/summer%20special/table%20fan/tf10/3.png?raw=true",
        info:"2 Year Domestic Warranty",
        description:"At V-Guard, we are building products of tomorrow, inspired by the consumer experiences of today. Products that are designed keeping the consumer at the forefront. Thus, by bringing innovation in our products, we are not just delivering household utilities, but meaningful experiences, that promise to bring home a better tomorrow.",
        price: 2599,
    },
];
module.exports = { data:tableFanData};
