const airPurifierData=[
    {
        name:"BePURE B1 4 Stage HEPA Technology Remote Control based Portable Room Air Purifier  (White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP1/Screenshot%202024-04-09%20102821.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP1/3.png?raw=true",
        info:"500 sq ft :Suitable for a Medium size room HEPA : Cleans common particle allergens, needs periodic replacement180 cu.m/hr : Large rooms need higher CADR ratings to filter more air per min",
        description:"Whether you are looking to improve the air quality in your home, office, or any indoor space, the Bepure B1 Air Purifier is the ideal solution. With its compact, stylish design, this air purifier effortlessly complements the aesthetics of your surroundings. In addition, courtesy of its remote control, touch display, and coverage area of up to 46.45 square.",
        price: 4899,
    },
    {
        name:"White Westing House White Westinghouse Dehumidifier - 12 Litres Portable Room Air Purifier  (WHITE)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP2/3.png?raw=true",
        info:"1 YEARS WARRANTY WITH LIFE TIME service support",
        description:"BRAND :White Westinghouse POWER SUPPLY V/Hz :220-240/50Hz POWER RATED CONSUMPTION : 255W CURRENT : 2.1A AIR FLOW : 210M3/H NOISE LEVEL : 45DB(A) MOISTURE REMOVAL (L / Day) :10L / DAY (26.7°C 60% RH) / 12L / DAY (30°C 80% RH) WATER TANK CAPACITY (litres) :3.1L DIMENSION (H*W*D) :15.9x10.24x9.53 inch RUNNING TEMPERATURE (°C) :5°C - 35°C NET WEIGHT : 8.5KG REFRIGERANT : R290 WARRANTY : 12 MONTHS Area Covered : 1200 Cubic Ft 12 Litres/Day Portable Domestic Purpose.",
        price: 21202,
    },
    {
        name:"voltas AC-M17-SC Room Air Purifier  (White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP4/3.png?raw=true",
        info:"463 sq.ft :Suitable for a Medium size room HEPA : Cleans common particle allergens, needs periodic replacement 360 CMH : Large rooms need higher CADR ratings to filter more air per min",
        description:"Xiaomi Smart Air Purifier 4 Lite Room Air Purifier (White)",
        price: 9999,
    },
    {
        name:"Voltas VAP36TWV Portable Room Air Purifier  (White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP3/3.png?raw=true",
        info:"12 Months Warranty Against Manufacturing Defects",
        description:"Voltas VAP36TWV Yes Portable Room Air Purifier (White)",
        price: 8660,
    },
    
    {
        name:"Prestige PAP 2.0 Portable Room Air Purifier  (White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP5/3.png?raw=true",
        info:"1 Year Manufacturing Warranty",
        description:"Fresh and clean air is essential for well-being of your family. With harmful pollutant particles like dust, hair, gasses, bacteria and viruses, the air inside your home is as polluted as outdoor air which can be harmful for your health. Safeguard your family's health, bring home a Prestige Air Purifier today.",
        price: 7200,
    },
    {
        name:"Dyson Pure Cool Link Tower Air Purifier Portable Room Air Purifier  (Silver)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP6/3.png?raw=true",
        info:"Material ABS Plastic Coverage Area 450 sq ControlType Remote, Mobile App",
        description:"Dyson Pure Cool Link TP03 Yes Portable Room Air Purifier (Silver)",
        price: 29899,
    },
    {
        name:"KENT Alps + Room Air Purifier  (White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP7/3.png?raw=true",
        info:"430 sq ft :Suitable for a Medium size room  HEP: Cleans common particle allergens, needs periodi replacement 400 cu.m/hr : Large rooms need higher CADR ratings to filter more air per min",
        description:"Breathe cleaner air and live a healthy life with KENT Alps+ Air Purifier , World’s 1st Air Purifier with UV LED and purity indicator. The air purifier is designed to solve your air quality concerns completely. It filters out air pollutants and bacteria, viruses, and germs from the polluted air indoors, and offers only cleaner, fresher, and breathable air for your and family’s well-being",
        price: 14000,
    },
    {
        name:"PHILIPS AC 1711/63 Portable Room Air Purifier  (White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP8/3.png?raw=true",
        info:"380 sq ft :Suitable for a Medium size room HEPA, Activated Carbon : Cleans common particle allergens, needs periodic replacement 300 cu.m/hr : Large rooms need higher CADR ratings to filter more air per min",
        description:"The Philips Smart Air Purifier 1000 series, comes with best in class filtration of 99.97% down to 0.003 microns. This device is equipped with many convenience features like Real time AQI display, filter life indication and is super energy efficent (consumes only 27 W)",
        price: 12199,
    },
    {
        name:"INFRES FreshAir 200 Portable Room Air Purifier  (White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP9/Screenshot%202024-04-09%20104329.png?raw=true",
        info:"269 sq ft :Suitable for a Medium size room HEPA, Activated Carbon, Pre-Filter : Cleans common particle allergens, needs periodic replacement 200 cu.m/hr : Large rooms need higher CADR ratings to filter more air per min",
        description:"remove up to PM 2.5, gaseous pollutants, dust mites,pollen, allergens,bacteria,some virus,odour,soot,mould,smoke,smog and other pollutants.Air Purification Stages- Washable primary filter,Honeycomb activated carbon filter,HEPA filter",
        price: 11391,
    },
    {
        name:"AGARO Imperial Air Purifier, 7 Stage Purification System, Anion Generator, True HEPA Portable Room Air Purifier  (white)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Air%20Purifier/AP10/3.png?raw=true",
        info:"400 sq ft :Suitable for a Medium size room HEPA : Cleans common particle allergens, needs periodic replacement 4 cu.m/hr : Large rooms need higher CADR ratings to filter more air per min",
        description:"AGARO Imperial Air Purifier is a 7 Stage Purification System. It comes with Anion Generator, True HEPA and can be adjusted in 3 Speed Settings.",
        price: 14999,
    },
];
module.exports = { data: airPurifierData};
