const washingMachineData=[
    {
        name:"realme TechLife 7.5 kg 5 Star Rating Fabric Safe Wash Fully Automatic Top Load Washing Machine Grey  (RMFA75A5G)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM1/3.png?raw=true",
        info:"2 Years Comprehensive Warranty on Product and 5 Years on Moto",
        description:" The improved scrubbing and whirling movement makes this washing machine highly functional. It has a fuzzy logic feature that picks up the wash cycle time and ensures an effective wash. ",
        price: 11990,
    },
    {
        name:"Godrej 7 kg 5 Star with Turbo 6 Pulsator Washing Machine Fully Automatic Top Load Grey  (WTEON 700 AD 5.0 ROGR)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM2/3.png?raw=true",
        info:"2 Years on Product and 10 Years on Motor from Godrej",
        description:"levate your laundry experience with the Godrej 7 kg Fully Automatic Washing Machine. From its advanced technologies to its user-friendly design, this appliance puts you in control, ensuring efficient and effortless laundry care. Invest in the best and enjoy the transformation it brings to your daily routine.",
        price: 14790,
    },
    {
        name:"realme TechLife 7 kg 5 Star rating Semi Automatic Top Load Washing Machine White, Black  (RMSA705NNNDW)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM3/3.png?raw=true",
        info:"2 Years Comprehensive and 5 Years on Wash Motor",
        description:"You can wash your clothes meticulously with the help of the Realme 7 kg Washing Machine. With up to 1400 RPM spin cycle and air dry circulation through the lid, this washing machine can quickly dry your clothes even during monsoons. ",
        price: 7890,
    },
    {
        name:"MOTOROLA 8 kg 5 star rating Semi Automatic Top Load Washing Machine Black  (MTSA805NNNDB)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM4/3.png?raw=true",
        info:"2 Year Comprehensive Warranty on Product and 5 Years Warranty on Motor.",
        description:"he large air dry lid and 1350 Spin RPM of this washing machine is designed to make drying fast and more efficient, giving you up to 15% quick results. So, no more last-minute outfit panics when you're running late.",
        price: 9890,
    },
    {
        name:"MOTOROLA 7 kg Digital Inverter,� Super Steam Technology with In-built Heater Grey��(MTFL705NHNJG) Fully Automatic Front Load Washing Machine with In-built Heater Grey  (MTFL705NHNJG)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM5/3.png?raw=true",
        info:"2 Year Comprehensive Warranty and 10 Years Warranty on Wash Motor from MOTOROLA",
        description:"You can effortlessly manage all your laundry requirements with the MOTOROLA 7 kg Fully Automatic Front-loading Washing Machine. It comes equipped with temperature, water level, weight, door, foam level, and speed sensors, offering an ideal washing performance for each cycle. ",
        price: 19990,
    },
    {
        name:"Thomson 8.5 kg with Germ Purifier Technology Fully Automatic Front Load Washing Machine with In-built Heater White  (TFL8500)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM6/3.png?raw=true",
        info:"2 Years Warranty on Product and 5 Years on Motor",
        description:"Bring home the Thomson Fully Automatic Front Load with In-built Heater (TFL8500) to get clean, hygienic, and wrinkle-free clothes with every single wash. This home appliance features a Steam Wash Technology to wash clothes with hot water, Multiple Smart Features for convenient performance, and an Anti-vibration Design to deliver noiseless operation.",
        price: 20990,
    },
    {
        name:"IFB 10 kg with Steam 5 Star AI Powered Eco Inverter with Wi-Fi EnabledOxyjet 9 Swirl Wash, 4 Years Comprehensive Warranty Fully Automatic Front Load Washing Machine with In-built Heater Brown  (EXECUTIVE PLUS MXC 1014)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM7/3.png?raw=true",
        info:"4 Years Comprehensive Warranty on Product, 10 Years Warranty on Motor and 10 Years Spares Support",
        description:"This AI-powered IFB washing machine detects the weight, fabric type, and selected wash programme to ensure an effective wash cycle. It features 9 Swirl Wash which uses smart motion to gently clean the clothes and provide long-lasting care to your fabrics. This machine features a 3D warm soak and rinse function which allows you to soak the clothes in warm water to remove the stubborn stains.",
        price: 51029,
    },
    {
        name:"BOSCH 9 kg 1400RPM, Anti Wrinkle, i-DOS system and EcoSilence Drive motor Fully Automatic Front Load Washing Machine with In-built Heater White  (WGA244AWIN)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM8/3.png?raw=true",
        info:"2 years on product, 12 years on motor",
        description:"Bosch 9 kg Inverter Fully-Automatic Front Loading Washing Machine (WGA244AWIN, White, Inbuilt Heater)",
        price: 44900,
    },
    {
        name:"Whirlpool 6 kg with Hard Water Wash Fully Automatic Top Load Washing Machine Grey  (WM ROYAL 6.0 GENX GREY 5YrMW/WM ROYAL 6.0 GENX GREY 5YMW)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM9/3.png?raw=true",
        info:"2 Years Comprehensive Warranty and 5 Years on Motor from Whirlpool",
        description:" Bring home this 6 kg washing machine from Whirlpool and say goodbye to laundry woes. It features a Hard-water Wash, a Delay Wash feature, and ZPF Technology to ensure a thorough wash.",
        price: 13790,
    },
    {
        name:"ONIDA 6.2 kg Fully Automatic Top Load Washing Machine Grey  (T62CGN / CRYSTAL 62)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/washingmachine/WM10/3.png?raw=true",
        info:"2 Years Comprehensive Warranty on Product, 5 Years Warranty on Motor",
        description:"Featuring 10 wash programs, this Onida Washing Machine is equipped to handle all kinds of laundry loads. Once your clothes are washed, the Air Dryer feature removes excess water and moisture from them so they are almost dry when they are taken out of the washer.",
        price: 10990,
    },
];
module.exports = { data: washingMachineData};
