const waterPurifierData=[
    {
        name:"KENT Grand Star-B RO Water Purifier with Digital Display of Purity & Performance 20 L RO + UV + UF + TDS Control + UV in Tank Water Purifier  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/Water%20Purifier1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/Water%20Purifier1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/Water%20Purifier1/3.png?raw=true",
        info:"On-site Service, Customer Needs to Call All India Kent Service / Service Engineer Will Come to the Site to Get the Product Repaired or Inspected ",
        description:"With KENT Grand Star, an advanced ROTM water purifier with multiple purification processes including RO+UV+UF+TDS Control+UV In-tank, and Zero Water Wastage Technology, you can now drink 100% pure and mineral-rich purified water. This purifier has a unique Digital Display of Purity feature that enables real-time tracking of the quality of the purified water, filters life, RO flow rate etc",
        price: 20840,
    },
    {
        name:"KENT ACE - B 8 L RO + UV + UF + TDS Water Purifier Suitable for all - Borewell, Tanker, Municipality Water  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/Water%20Purifier2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/Water%20Purifier2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/Water%20Purifier2/3.png?raw=true",
        info:" 1 Year Warranty Provided by the Manufacturer from Date of Purchase with 3 Years Extended Service without Any Charges",
        description:"Kent ACE - B RO + UV + UF + TDS 8 L Water Purifier Blue, Grey",
        price: 12599,
    },
    {
        name:"LIVPURE Allura - No Service Cost for 2.5 years - All Filters Included 7 L RO + UV + Copper Water Purifier  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP3/3.png?raw=true",
        info:"2.5-Years Unconditional Warranty- Including all filters, membranes & electrical part changes are covered at zero service cost.",
        description:"Experience water purification at its finest with the Livpure Liv-Allura-Premia. This advanced purifier boasts an 8-stage purification system, eliminating impurities, viruses, and bacteria. The super sediment filter ensures microscopic particle removal, while in-tank UV sterilisation guarantees total water safety. With a generous 7-liter storage capacity, you'll never run out of pure water",
        price: 14490,
    },
    {
        name:"Pureit Revito 7 L RO + MF + UV in Tank + Minerals Water Purifier Suitable for all - Borewell, Tanker, Municipality Water  (Teal)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP4/3.png?raw=true",
        info:"1 year domestic warranty on all parts excluding consumables & Germ Kill Kit. Any technician visits, if required, will be charged to the consumer.",
        description:"You can get a consistent supply of clean, fresh, and mineral-enriched water with the Pureit Revito 7 L RO+MF+UV+Minerals Water Purifier. It offers safe drinking water by effectively removing heavy metals. In addition, as this water purifier can purify up to 8000 L of water before requiring filter maintenance, you can get ample clean water for a long time",
        price: 16990,
    },
    {
        name:"V-Guard Requpro High Recovery RO with Stainless Steel Tank, 3X Water Saving & Alkaline 5.5 L RO + UV + UF + Minerals + Alkaline Water Purifier  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP5/3.png?raw=true",
        info:"1 Year Domestic Product Warranty",
        description:" V-Guard RequPro?Water?Purifier is a cutting-edge solution for safe and pure drinking water needs. With its true High Recovery RO technology,?RequPro?can conserve three times more water than conventional RO systems?while still delivering 100% pure RO-purified water, even in high TDS conditions. ",
        price: 17499,
    },
    {
        name:"LG WW152NP 8 L RO + UV Water Purifier Suitable for all - Borewell, Tanker, Municipality Water  (Black",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP6/3.png?raw=true",
        info:" 1 Year on Product and 10 Years on Tank from Manufacture",
        description:"This LG water purifier comes equipped with a multistage RO filtration process that removes harmful bacterias and viruses to give you safe and pure drinking water. The stainless steel tank of this water purifier comes with dual-protection that keeps your purified water fresh and tasty.",
        price: 19990,
    },
    {
        name:"LG WW174NPC 8 L RO + UV + MB Water Purifier  (Crimson Red with Leaf Pattern)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP7/3.png?raw=true",
        info:"1 Year Warranty on Product , Additional 9 Year Warrenty on Stainess Steel Tank .",
        description:"Dual protection airtight Stainless steel Tank with Multi Stage RO Filtration, Ever fresh UV + (In tank UV), Mineral Booster (Ca & Mg)",
        price: 29499,
    },
    {
        name:"Pureit COPPER+ ECO 8 L RO + UV + MF + Minerals Water Purifier  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP8/3.png?raw=true",
        info:"1 Year Comprehensive Domestic Warranty on All Parts excluding Consumables & Germkill Kit. Technician Visit, if applicable, will be charged to the customer.",
        description:"New Pureit Copper+ Eco RO, an advanced purifier that enhances your family’s health by bringing together modern technology and traditional goodness. Its advanced 7 stage purification process gives 100% RO purified water while enriching it with the goodness of copper and giving you highest water saving. ",
        price: 25490,
    },
    {
        name:"Aquaguard Eden Reverse Osmosis (RO) and Ultraviolet (UV) With MTDS Technology & SS Tank 5.2 L RO + UV + MTDS + SS (AS) Water Purifier  (Golden Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP9/3.png?raw=true",
        info:"1 Years Manufacturer Warranty",
        description:"Aquaguard Eden RO+UV+MTDS+SS Water Purifier Comes with inbuilt storage tank made of high grade 304 Stainless Steel along with dual RO+UV purification for clean and pure drinking water. ",
        price: 25999,
    },
    {
        name:"AO Smith Z9 10 L RO Water Purifier Silver Charged Membrane Tech) Water Purifier Black | Hot + Normal Water| 8-Stage Purification",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/HOME%20APPLIANCES/Water%20Purifier/WP10/3.png?raw=true",
        info:"1 Year Comprehensive Warranty & 1 Year RO Membrane Warranty if TDS is < 2000 ppm Hardness is < 400 ppm",
        description:"Kiss goodbye to water-borne diseases with this water purifier from A. O. Smith. With 8 stages of purification, this purifier gives you water that is not just healthy, fresh and clean, but also enriched with minerals.",
        price: 25199,
    },
];
module.exports = { data: waterPurifierData};


