const kettleData=[
    {
        name:"HAVELLS by Havells GHBKTAXK160 Electric Kettle  (1.5 L, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%201/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%201/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%201/3.png?raw=true",
        info:"2 Years Comprehensive Warranty Manufacturing Defects Only",
        description:"Large Capacity,Cool Touch Stainless Steel Body,Digital Control Panel,Optimal Performance,Ease of Operation,Easy Pouring,Dry Boil Protection",
        price: 4099,
    },
    {
        name:"MILTON Vienna Stainless Steel Double Walled Electric Kettle  (1.8 L, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%202/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%202/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%202/3.png?raw=true",
        info:"This Product Is Under 1 Year Warranty From The Date Of Retail Purchase Against Any Manufacturing Defects In Material And Workmanship. The Warranty Does Not Cover Damages Resulting From Accidents, Mishandling Or Tampering With The Mechanism. Warranty Valid Against Producing Original Bill Endorsed By Seller.",
        description:"introducing Milton Vienna Electric 1.8 Stainless Steel Electric Kettle come with Double Walled & Auto Cut-off for long lasting used. Detachable 360 Degree Connector with Cool tough body and cordless pot. ",
        price: 1770,
    },
    {
        name:"V-Guard by V-Guard VKP15 Prime Electric Kettle  (1.5 L, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%203/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%203/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%203/3.png?raw=true",
        info:"2 Year Domestic Warranty. Warranty of the product is limited to manufacturing defects only.",
        description:" V-Guard VKP15 Prime Black Electric Kettle.introducing Milton Vienna Electric 1.8 Stainless Steel Electric Kettle come with Double Walled & Auto Cut-off for long lasting used. Detachable 360 Degree Connector with Cool tough body and cordless pot. ",
        price: 1199,
    },
    {
        name:"KENT 16052 Electric Kettle  (1.8 L, Silver, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%204/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%204/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%204/3.png?raw=true",
        info:"1 Year Warranty.Manufacturing Defects",
        description:"This KENT Electric Electric Kettle is an innovative product that can be carried anywhere you go. The food-grade silicone material of this kettle makes it safe for use, even for kids. In addition, the silicone material offers hassle-free cleaning, making it convenient for your use. The compact design of this kettle makes it travel-friendly, allowing you to easily carry it in your bags",
        price: 1349,
    },
    {
        name:"Prestige PKCB-1.7 Blue Electric Kettle  (1.7 L, Blue)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%205/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%205/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%205/3.png?raw=true",
        info:"1 Year Manufacturer Warranty on the product. Manufacturer defects only",
        description:"Prepare hot water, instant tea etc, in a matter of minutes with Prestige Electric Kettle. With smart features like automatic cut-off, single touch lid locking, beautifully designed ergonomic handle - this glamorously designed electric kettle is a must have accessory for your home.",
        price: 1500,
    },
    {
        name:"HAVELLS Capture Multi Cooker Electric Kettle  (1.2 L, Green)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%206/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%206/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%206/3.png?raw=true",
        info:"2 Years Comprehensive Warranty. Warranty of the Product is Limited to Manufacturing Defects Only",
        description:"The stainless steel inner and removable trays make cleaning up a breeze, giving you more time to relax and enjoy quality moments with your family after a delicious meal.",
        price: 1988,
    },
    {
        name:"KENT Amaze Plus Cool Touch SS Electric Kettle  (1.8 L, Red)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%207/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%207/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%207/3.png?raw=true",
        info:"Guaranteed full replacement, Manufacturing Defects",
        description:"Perfect in looks and perfect features-wise, KENT Amaze Plus Cool-Touch is the right choice your modern kitchen Comes with 1500W power and 1.8L capacity boils water faster and serve 5-6 people at a time Stainless Steel inner body keeps water warm for a long time Its cool-touch plastic exterior lets you handle the kettle without having concerns about safety 360° cordless rotation will help you easily detach it from the base for easy pouring The wide-mouth design ensures hassle-free pouring & cleaning Auto switch-off function for safer operation",
        price: 1699,
    },
    {
        name:"AGARO Regal Electric Kettle with Keep Warm Function, Stainless Steel & Glass body Electric Kettle  (1.5 L, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%208/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%208/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%208/3.png?raw=true",
        info:"1 Year Warranty, Any Manufacturing Defect",
        description:"Prepare hot water, instant tea etc, in a matter of minutes with Prestige Electric Kettle. With smart features like automatic cut-off, single touch lid locking, beautifully designed ergonomic handle - this glamorously designed electric kettle is a must have accessory for your home",
        price: 1999,
    },
   
    {
        name:"HAVELLS Crystal Tea-Coffee Maker Glass with Filter Basket | Transparent Glass 600 W Electric Kettle  (1 L, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%209/Screenshot%202024-04-12%20230948.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%209/Screenshot%202024-04-12%20231013.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%209/Screenshot%202024-04-12%20231026.png?raw=true",
        info:"2 YEAR WARRANTY any manufacturing detail cover in warranty.physical damage not cover in warranty",
        description:" Brew a quick and delicious cup of tea or coffee with the Havells Crystal Tea and Coffee Maker. It uses a power consumption of up to 600 W to lend you superior performance. Also, this tea and coffee maker features a unique filter basket that helps speed up the process of brewing. Thanks to the quality temperature controller, you can preset time as per your preference. ",
        price: 2390,
    },
    {
        name:"AGARO Regency Vintage Electric Kettle  (1.8 L, Green)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%2010/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%2010/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/KETTLE/KETTLE%2010/3.png?raw=true",
        info:"2 Year warranty ,manufacturing defects ",
        description:"This AGARO Vintage Kettle comes with 1.8L capacity with a temperature gauge. It is useful for boiling water to make tea coffe",
        price: 3499,
    },
];
module.exports = { data: kettleData};
