const roomheaterData=[
    {
        name:"Weltherm Tower Heater HPC-Feugo+ with BONFIRE Display 1400/2000 watts Tower Heater HPC-Feugo+ with BONFIRE Display 1400/2000 watts Room heater Radiant Room Heater",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM1/3.png?raw=true",
        info:"Type:Radiant, Color: Black,  Climate Control:  No Heat Settings :2000W",
        description:" HPC-Feugo+ has two heat settings, including 1400 W and 2000 W so that you can choose your preferred temperature. This room heater features a PTC ceramic heating element that ensures optimal performance. ",
        price: 4400,
    },
    {
        name:"HAVELLS BERORH 800 W Quartz Room Heater",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM2/3.png?raw=true",
        info:"On site 2 yr.Manfg defects.",
        description:"Quartz Tube Bero comes with 2 Quartz heating tubes providing more warmth. Customer can also use either of the tube depending upon the requirement.",
        price: 2149,
    },
    {
        name:"Crompton Insta Airohot Fan Room Heater",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM3/3.png?raw=true",
        info:"1 Year Warranty on Product.Warranty Covers on Manufacturing Defects Only",
        description:"Keep yourself warm and cosy with the Crompton Insta Airohot Room Heater. Its adjustable thermostat helps control the temperature in your space. And, as soon as the temperature starts to decrease, it turns on the heating to maintain the required temperature. In addition, the 35 W twin-blade fan of this room heater offers corner-to-corner and balanced heating across the room",
        price: 2219,
    },
    {
        name:"Crompton Insta Cozy Insta cozy halogen Halogen Room Heater",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM4/3.png?raw=true",
        info:"1 Year Warranty on Product.Warranty Covers on Manufacturing Defects Only",
        description:"Keep yourself warm and cosy with the Crompton Insta Airohot Room Heater. Its adjustable thermostat helps control the temperature in your space. And, as soon as the temperature starts to decrease, it turns on the heating to maintain the required temperature. In addition, the 35 W twin-blade fan of this room heater offers corner-to-corner and balanced heating across the room",
        price: 2161,
    },
    {
        name:"BAJAJ Majesty RH3H Halogen Room Heater",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM5/3.png?raw=true",
        info:"2 Year Manufacturer Warranty.Any Manufacturing defect except rods",
        description:"Presenting Bajaj Majesty RH3H Halogen Heater with multiple Heat settings for optimum Heat transfer & Power Saving.",
        price: 2758,
    },
    {
        name:"THERMOCOOL HH _ 115 HH _ 115 | Room Heater Fan Room Heater",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM6/3.png?raw=true",
        info:"2 Year Manufacturer Warranty.Any Manufacturing defect except rods",
        description:"We are a household name in promoting pristine technological novelty and perfection. From contemporary design to great functionally, we have it all. Our products steadily outperform peers with outstanding service that makes every customer smile with technology-driven home appliances. ",
        price: 2300,
    },
    {
        name:"Weltherm TowerHeater HPCFUME1300W/2000W roomheaterTouchControlDigitalDisplaywithremote HPC FUME Fan Room Heater",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM7/3.png?raw=true",
        info:"1 Year Manufacturer Warranty.Any Manufacturing defect except rods",
        description:"The Weltherm HPC Fume Tower Room Heater is a cutting-edge heating solution designed to provide efficient warmth and comfort to any indoor space while maintaining excellent air quality. Engineered with advanced features and thoughtful design, this heater offers an exceptional heating experience tailored to modern living environments.",
        price: 4450,
    },
    {
        name:"HAVELLS OFR 9 WAVE FIN WITH FAN BEIGE 2400 W (GHROFAEC240) Oil Filled Room Heater",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM8/3.png?raw=true",
        info:"2 YEAR PRODUCT WARRANTY",
        description:"SI MARKED , NO DEPLETION OF OXYGEN , ANTI DRYNESS , COMFORTABLE BREATHING , HOME SERVICE WITHIN 24 HOURS , 13 FINS OIL , 3 HEAT SETTING , OVERHEAT PROTECTION , CORD STORAGE , REAR SAFETY COVER , TILT OVER SWITCH FOR SAFETY , THERMOSTATIC HEAT CONTROL , QUICK HEATING WITH PTC FAN , CASTOR WHEELS FOR EASY MOBILITY , EASE TO USE WITH 3 POWR SETTING , HIGH QUALITY HEATING OIL FOR BETTER HIT CONDUCTION AND QUICKER HEATING .",
        price: 8970,
    },
    {
        name:"ORPAT Climate Control PTC Heaters OPH-1430 1100W/2200W - Blue Radiant Room Heater",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM9/3.png?raw=true",
        info:"2 YEAR PRODUCT WARRANTY",
        description:" A PTC heating device that is very effective with its features which are namely a two heat setting system (1100 W and 2200W). A PTC ceramic heating element making it an energy-efficient heater with less suffocation as it burns less oxygen, overheat auto-cutoff protection, wide-angle auto oscillating function, variable thermostat for setting",
        price: 3780,
    },
    {
        name:"ORPAT Climate Control - Quartz Heater - OQH-1470 - Empire Red Quartz Room Heater",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/ROOM%20HEATER/RM10/3.png?raw=true",
        info:"2 YEAR PRODUCT WARRANTY",
        description:" brilliant quartz heating device that is characterized by a number of features such as an international ergonomic design and styling, Low bright & high heat producing advanced quartz heater tube, Rust proof long life metal body, variable thermostat setting for temperature control, it has 4 heat setting system (550W, 1100W, 1650W and 2200W).",
        price: 2140,
    },
];
module.exports = { data: roomheaterData};
