const gryserData=[
    {
        name:"V-Guard 25 L Storage Water Geyser (Matteo DG 25 Litre, 5 Star, White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser1/3.png?raw=true",
        info:"Matteo DG 25L comes with a 2-year offsite domestic warranty for manufacturing defects. The Heating Element has a warranty of 3 years & the Inner Tank has a warranty of 5 years. Please contact V-Guard Customer Care 1800 103 1300(Toll-free) for service-related issues.",
        description:"Built with a thick and high-density PUF insulation, the V-Guard Matteo DG 25 L Storage Water Heater ensures high energy efficiency and helps retain hot water for an extended period of time.",
        price: 8199,
    },
    {
        name:"HAVELLS 25 L Storage Water Geyser (Electric Geyser, White & Mustard)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser2/Screenshot%202024-04-11%20224355.png?raw=true",
        info:"2 Years Comprehensive Warranty on Product, 7 Years Warranty on Inner Container and 4 Years Warranty on Heating Element",
        description:" If you are looking for an efficient storage water heater, then this Havells water heater is ideal for your home. Its high-density PUF insulation is free of CFC and prevents loss of radiation, which makes it energy-efficient. On top of that, it boasts an LED indicator that changes colour to indicate the heating status.",
        price: 10339,
    },
    {
        name:"V-Guard 25 L Storage Water Geyser (Pebble Shine 25 Litre, 5 Star, White-Grape Frost)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser3/3.png?raw=true",
        info:"2 Year on Product, 4 Year on Heating Element, 7 Year on Inner Tank. Product, Inner Tank, Heating Element",
        description:"Storage Useful for Bathroom, can store heated water25 L Greater the Capacity, more the users can be served for bath/wash 8 Bar : Pressure rating >8 bar is suitable for High Rise buildings Vertical : Suitable for large wall spaces",
        price: 9499,
    },
    {
        name:"V-Guard 15 L Storage Water Geyser (Pebble Pro 15 Ltr BEE 5-star rating With Energy-Saving Technology & Rust- proof, White & Violet)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser4/3.png?raw=true",
        info:"3 years on product, 4 years on heating element and 10 years on inner tank . During Installation Customer will choose to change interchange panel.3 others clr available",
        description:"The Pebble Pro series boast of a BEE 5-star rating for its energy-saving technology which includes PUF insulation that conserves heat, keeping your water hot for longer, while also using less energy to do so. So, what are you waiting for? Get the storage electric water heater you desire. ",
        price: 10650,
    },
    {
        name:"V-Guard 25 L Storage Water Geyser (Calino 25L, White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser5/3.png?raw=true",
        info:"Calino 25L comes with a 2-year offsite domestic warranty for manufacturing defects. The Heating Element has a warranty of 3 years & the Inner Tank has a warranty of 7 years. Please contact V-Guard Customer Care 1800 103 1300(Toll-free) for service-related issues.",
        description:"After a long tiring day, all that one craves for will be that instant joy from a warm soothing shower providing that much needed rejuvenation for your body and your soul. Well, if you are looking for that advanced electric geyser for the perfect hot shower, which also offers a long-lasting durability, ultimate safety and higher energy savings, look no further than V-Guard Calino 25L, designed to give your bathroom an added classy distinctive touch.",
        price: 10799,
    },
    {
        name:"Hindware 3 L Instant Water Geyser (Immedio, White & Blue)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser6/1%20(1).png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser6/3.png?raw=true",
        info:"24 months overall warranty, 5 years on tank and 24 months on heating",
        description:"You can get hot water in no time with the help of the Hindware Atlantic Immedio Blue 3 L Instant Water Heater. Its rust-resistant, strong, and high-quality engineered polymer construction ensures enduring performance. Additionally, the superior finish of its outer body ensures that this water heater keeps looking good even after extended use. Moreover, this water heater has LED indicators, which turn red when turned on and turn green when the heating is activated.",
        price: 2499,
    },
    {
        name:"Crompton 3 L Instant Water Geyser (AIWH-3LJUNO3KW5Y, White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser7/3.png?raw=true",
        info:"Tank: 5 years, Heating Element: 2 years, Product: 2 years, Manufacturer Defects covered under warranty",
        description:"You can start off your mornings by having hot water baths with the Crompton Juno 3 L Instant Water Heater. Built with an up to 3000 W high-grade copper heating element, this water heater offers quick heating. Additionally, it has the ability to endure up to 6.5 kg/cm2 pressure, making this water heater ideal for high-rise buildings. Furthermore, made with a robust body, this water heater is tough and heat resistant.",
        price: 2844,
    },
    {
        name:"HAVELLS 25 L Storage Water Geyser (Adonia Spin, White, Blue)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser8/3.png?raw=true",
        info:"7 Year Warranty on Inner Container 4 Year Warranty on Heating Element 2 Year Comprehensive Warranty. Warranty of the Product is Limited to Manufacturing Defects Only",
        description:"Thanks to Whirlflow technology, the Havells Adonia Spin 25 L Storage Water Heater makes sure that the cold water does not mix with the hot water in the tank, providing a continuous flow of hot water without a drop in the temperature.",
        price: 12990,
    },
    {
        name:"HAVELLS 25 L Storage Water Geyser (Magnatron, White, Gold)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser9/3.png?raw=true",
        info:"2 Years Comprehensive Warranty on Product and 7 Years on Inner Container. Warranty of the Product is Limited to Manufacturing Defects Only",
        description:"You can start off your mornings by having hot water baths with the Crompton Juno 3 L Instant Water Heater. Built with an up to 3000 W high-grade copper heating element, this water heater offers quick heating. Additionally, it has the ability to endure up to 6.5 kg/cm2 pressure, making this water heater ideal for high-rise buildings",
        price: 17990,
    },
    {
        name:"HAVELLS 25 L Storage Water Geyser (Otto, Grey)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/WINTER%20APPLIANCES/water%20gryser/gryser10/3.png?raw=true",
        info:"2 Years Comprehensive Warranty, 4 Years Warranty on Heating Element, 7 Years Warranty on Inner Containe",
        description:"You can start off your mornings by having hot water baths with the Crompton Juno 3 L Instant Water Heater. Built with an up to 3000 W high-grade copper heating element, this water heater offers quick heating. Additionally, it has the ability to endure up to 6.5 kg/cm2 pressure, making this water heater ideal for high-rise buildings",
        price: 13399,
    },
];
module.exports = { data:gryserData};
