const floorLampData=[
    {
        name:"Homesake Tree Floor Lamp",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl1/3.png?raw=true",
        info:"4 month warranty",
        description:"Contemporary Metal Floor Lamp,Contemporary Minimalist Standing Floor Light with Iron Legs,E27 Lamp Base,Modern Design Standing Light ,Study Room and Bedroom Antique Gold, Floral, White",
        price: 2045,
    },
    {
        name:"MUSHK VINTAGE CREATION Club Floor Lamp",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl2/3.png?raw=true",
        info:"4 month warranty",
        description:"Brighten Up Your Room Space As Well As Your Mind With This Cute Contemporary Style Club Metal Lamp. Made Of High Quality Metal and Fabric Along With The Pole Base Design, ThisPole Lighting Fixture Is Solid And Sturdy. It Will Update The Interior Of Your Home With Its Industrial Design And Will Accommodate A Variety Of Indoor Decor Styles. It Is Also A Great Accent For Your Bars, Study, Living Room, Dinning Room, Office And So On.",
        price: 1942,
    },
    {
        name:"Prodezine Tripod Floor lamp",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl3/3.png?raw=true",
        info:"4 month warranty",
        description:"Brighten Up Your Room Space As Well As Your Mind With This Cute Contemporary Style Club Metal Lamp. Made Of High Quality Metal and Fabric Along With The Pole Base Design, ThisPole Lighting Fixture Is Solid And Sturdy. It Will Update The Interior Of Your Home With Its Industrial Design And Will Accommodate A Variety Of Indoor Decor Styles. It Is Also A Great Accent For Your Bars, Study, Living Room, Dinning Room, Office And So On.",
        price: 1699,
    },
    {
        name:"MUSHK VINTAGE CREATION Club Floor Lamp",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl4/3.png?raw=true",
        info:"4 month warranty",
        description:"It’s not only brings elegant designs to your modern home decoration but also represents stability and durability for daily use. Apart from that, this quietly dramatic floor lamp comes with sophisticated tripod base which can be rotate anywhere in your place as per requirement having features of high quality and energy saving. It’s exclusively handcrafted by Indian artisans and can give elegance to any room, cafe, hotels and office. It is unique enough to decorate your particular space. You can install it by hand without any other tools. So,decorate home with our lamp give suitable position whether it’s side of sofa or any of your space where you want to relax and enjoy",
        price: 2200,
    },
    {
        name:"MUSHK VINTAGE CREATION Club Floor Lamp",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl5/3.png?raw=true",
        info:"4 month warranty",
        description:"Contemporary Metal Floor Lamp,Contemporary Minimalist Standing Floor Light with Iron Legs,E27 Lamp Base,Modern Design Standing Light ,Study Room and Bedroom Antique Gold, Floral, White",
        price: 1499,
    },
    {
        name:"Crosscut Wood Night Lamp  (110 cm, Blue)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl6/3.png?raw=true",
        info:"4 month warranty",
        description:"It Crosscut Tripod Floor lamp Helps to Glow Your Room that can light each and every corner of the house, The Lamps that has great aesthetic Value and are made up of Glossy Polish Which Only Crosscut Currently It Looks Great in Finishing and has a Premium Feel Over the Matt Polished Lamps Hence Do Check About Polish Finishing if it's Matt or Glossy",
        price: 2099,
    },
    {
        name:"Prodezine Tripod Floor lamp",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl7/3.png?raw=true",
        info:"4 month warranty",
        description:"It Crosscut Tripod Floor lamp Helps to Glow Your Room that can light each and every corner of the house, The Lamps that has great aesthetic Value and are made up of Glossy Polish Which Only Crosscut Currently It Looks Great in Finishing and has a Premium Feel Over the Matt Polished Lamps Hence Do Check About Polish Finishing if it's Matt or Glossy",
        price: 1885,
    },
    {
        name:"BEVERLY STUDIO Tripod Floor lamp",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl8/3.png?raw=true",
        info:"4 month warranty",
        description:"Enjoy your study or work time adorning your table top with a bright light by picking any one of these tripods table lamps. High on utility and efficiency, these designer lamps will illuminate your table space in the most modern and stylish way. The strong and sturdy make of these lamps will render you a lasting use. Bring this beautiful wooden tripod table lamp to your home.from the house of Beverly studio.",
        price: 5999,
    },
    {
        name:"BEVERLY STUDIO Column Floor Lamp",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl9/3.png?raw=true",
        info:"4 month warranty",
        description:"It Crosscut Tripod Floor lamp Helps to Glow Your Room that can light each and every corner of the house, The Lamps that has great aesthetic Value and are made up of Glossy Polish Which Only Crosscut Currently It Looks Great in Finishing and has a Premium Feel Over the Matt Polished Lamps Hence Do Check About Polish Finishing if it's Matt or Glossy",
        price: 5699,
    },
    {
        name:"IKEA Table Floor Lamp",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/floor%20lamp/fl10/3.png?raw=true",
        info:"4 month warranty",
        description:"table floor lamp is a great option if you're searching for a long-lasting and multi-functional hardwood floor for for your house or office. It's a real show-stopper that will draw attention in any room. Long-lasting and energy-efficient features Eyes that don't hurt Light That Remains Wooden Floor Lamp of High Quality It goes with any style of home — Contemporary, Modern, or Mid-Century Ideal for any living or work environment. Your friends and families will remember you for a long time. The light is simple to switch on or off.",
        price: 1599,
    },
];
module.exports = { data:floorLampData};
