const jhumarData=[
    {
        name:"Prop It Up Exclusive Economic Range of 5 Light Chandelier with FLOWER Shape Glass Shade & Very fine ANTIQUE Finished frem, for Bedroom, Drawing Room, Hall, Dinning, Shop, Office etc.120/5 (white) Chandelier Ceiling Lamp  (White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c1/3.png?raw=true",
        info:"6 month warranty",
        description:"prop it up exclusive economic range of 5 light chandelier with leaves shape glass shade & very fine steel/crom finished frem, (BULB NOT INCLUDED) for bedroom, drawing room, hall, dinning, shop, office etc. ",
        price: 3539,
    },
    {
        name:"Classical Chandelier Ceiling Lamp  (Gold, Brown)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c2/3.png?raw=true",
        info:"6 month warranty",
        description:"This Amazing Hanging Lamp From House Of Somil Is A Useful Addition To Your Home Decor Arsenal. Crafted With High Quality Material. This Hanging Lamp Is Long Lasting And Energy Efficient. This Hanging Lamp Produce A Designer Lighting Effects When It Light And Decorated Your Place With A Extra Lighting Decoration. You Can Use Any Bulb As LED, CFL, Incandescent, Fluorescent Or Any Other As Per Your Choice Of Any Watt As Per Your Choice And Requirement It Will Function Same By Producing Designer Lighting Effects. Also You Can Adjust It Length As Per Your Need And Requirement At Time Of Installation. It Also Energy Efficient as It Produce Same Light As Normal One But It Also Add Some Designer Effects In Lighting. Use In Home- Indoor, Bad Room, Drawing Room, Dining Room, Living Room, Kids Room, Guest Room, Lobby, Hall, Restaurant, Hotel, Party",
        price: 3300,
    },
    {
        name:"GAUVIK 8827 12 LIGHT Jhoomar/Chandelier for Restaurant,Bedroom,Living Room,Home Decor Chandelier Ceiling Lamp  (Gold, Clear)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c3/3.png?raw=true",
        info:"6 month warranty",
        description:"APPLICATION: Decorative Jhoomar/Chandelier/Jhoomar Hanging Light/Jhoomar Ceiling Light to décor your Home, Bedroom, Drying Room, Living room, Staircase, Balcony, Kitchen, Study Table, Office, Restaurant, Hotel, Shop, Cafe, Dinning, Coffee etc. HOLDER TYPE: E27 (Screw Type) , BULB NOT INCLUDED ; COLOR: Black Antique ; MATERIAL: Metal and Glass ; INSTALLATION: Easy to Install, Recommendation- Please call Professional to Install.",
        price: 4999,
    },
    {
        name:"GAUVIK Chandelier Ceiling Lamp  (Multicolor)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c4/3.png?raw=true",
        info:"6 month warranty",
        description:"A Useful Addition To Your Home Decor Arsenal. Crafted From High Quality Brass And Glass Material, This Unique Chandelier Is Long Lasting And Energy Efficient. This Chandelier Produces The Same Amount Of Light As Normal Ones And Features A Look That Is Similar To Traditional Incandescent Lights",
        price: 3899,
    },
    {
        name:"ORAB K9 Crystal Black Gold polish metal 400mm chandelier hanging ceiling jhoomer Chandelier Ceiling Lamp  (Black, Gold)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c5/3.png?raw=true",
        info:"6 month warranty",
        description:"A Useful Addition To Your Home Decor Arsenal. Crafted From High Quality Brass And Glass Material, This Unique Chandelier Is Long Lasting And Energy Efficient. This Chandelier Produces The Same Amount Of Light As Normal Ones And Features A Look That Is Similar To Traditional Incandescent Lights",
        price: 3949,
    },
    {
        name:"Somil Pendants Ceiling Hanging Lamp Light Of 3 , 25X25X66 CM. Chandelier Ceiling Lamp  (Black, Yellow)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c6/3.png?raw=true",
        info:"6 month warranty",
        description:"This Amazing Hanging Lamp From House Of Somil Is A Useful Addition To Your Home Decor Arsenal. Crafted With High Quality Material. This Hanging Lamp Is Long Lasting And Energy Efficient. This Hanging Lamp Produce A Designer Lighting Effects When It Light And Decorated Your Place With A Extra Lighting Decoration. You Can Use Any Bulb As LED, CFL, Incandescent, Fluorescent Or Any Other As Per Your Choice Of Any Watt As Per Your Choice And Requirement It Will Function Same By Producing Designer Lighting Effects. Also You Can Adjust It Length As Per Your Need And Requirement At Time Of Installation. It Also Energy Efficient as It Produce Same Light As Normal One But It Also Add Some Designer Effects In Lighting. Use In Home- Indoor, Bad Room, Drawing Room, Dining Room, Living Room, Kids Room, Guest Room, Lobby, Hall, Restaurant, Hotel, Party",
        price: 1110,
    },
    {
        name:"Crysta World pirameed shape 18 inch k9 crystal Chandelier Ceiling Lamp  (Yellow)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c7/3.png?raw=true",
        info:"6 month warranty",
        description:"[Easy to Install Flush Mount Chandelier] Hanging the flush mount crystal light fixture base on the ceiling first, then you just need to hang up the crystal lighting crystal strings according to the instruction. We pack a glove to protect the hand for easy installation. Please cut off the power before installation., Application Space: Living Room, Dining Room, Staircase, Hallway, Foyer, Kitchen Island, Craft Room, Hotel, Etc, [Modern Ceiling Chandelier Material] First-class crystal ball and crystal beads silver chandelier, Elaborate cut, when sunlight hits the crystal ball, there will reflect rainbow light, very beautiful! bedroom light fixture base is made of stainless metal, Safe and reliable.",
        price: 1500,
    },
    {
        name:"Crysta World K9 Crystal Chandelier Ceiling Lamp  (Yellow)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c8/3.png?raw=true",
        info:"6 month warranty",
        description:"Elegant Chandelier Ceiling Lights for Living Room CRYSTA WORLD Flush Mount Crystal Chandelier looks amazing in your room and it looks very elegant! Great product of chandelier lights and crystals light up the dining table. Whoever comes just admire chandelier. It is such beautiful modern ceiling lamps! Great home decor! which could be Halloween and Christmas decorations. Gorgeous Living Room Chandelier So elegant! Contemporary Chandelier Pendant Lamp perfect for living room, It such a beautiful chandelier. When turned on it really sparkles. The lamps for living room Looks amazing and adds a nice touch to your living room. Gorgeous Living Room Chandelier So elegant! Contemporary Chandelier Pendant Lamp perfect for living room, It such a beautiful chandelier. When turned on it really sparkles.",
        price: 2000,
    },
    {
        name:"Shri Mahal Antiques 300mm Jhhomar Lamp Ceiling Light For Living Room/Hall/Bed Room etc. Chandelier Ceiling Lamp  (Multicolor)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c9/3.png?raw=true",
        info:"6 month warranty",
        description:"300mm chandelier best quality glass * rgb color * 1 remote 300mm chandelier each Rediscover the magic of lighting and decorating your spaces with our range of beautiful chandeliers. We offer pieces with unique designs",
        price: 2899,
    },
    {
        name:"Shri Mahal Antiques Chandelier Ceiling Lamp  (Gold)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/jhumar/c10/3.png?raw=true",
        info:"6 month warranty",
        description:"The Chandelier Ceiling Lamp is made from premium Crystal and Iron components, demonstrating unmatched durability that will survive the test of time. These dependable components work together to guarantee that the lamp will continue to have both structural integrity and elegant beauty for many years to come. The Iron structure acts as a sturdy base for the delicate Crystal parts, striking a beautiful balance between elegance and strength",
        price: 2297,
    },
];
module.exports = { data:jhumarData};
