const wallLampData=[
    {
        name:"Artica Uplight Wall Lamp With Bulb",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w1/3.png?raw=true",
        info:"2 month warranty",
        description:"Back Light Shadow Wooden LED wall Lamp",
        price: 761,
    },
    {
        name:"Blissbells Pendant Wall Lamp With Bulb",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w2/3.png?raw=true",
        info:"2 month warranty",
        description:"Led Modern Style Crystal Short Shaded Pendant Chandelier Material: Metal, Crystal; Fixture finish: Gold; Crystal: clear Fixture: Included Inbuilt Led Light No Bulb Needed",
        price: 5300,
    },
    {
        name:"Blissbells Wallchiere Wall Lamp With Bulb",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w3/1.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w3/3.png?raw=true",
        info:"2 month warranty",
        description:"Selected aluminum die-casting materials, anti-oxidation, anti-corrosion and excellent heat dissipation effect. Adopts acrylic lens, light transmission is soft 2.This creative LED wall light is widely used in bedroom, bedside, living room, Lounge, girl room, bars, cafe and some other places as you 3.Simple Installation, Suitable for any smooth indoor surface, making for a stress-free setup.",
        price: 2936,
    },
    {
        name:"Blissbells Wallchiere Wall Lamp With Bulb",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w4/3.png?raw=true",
        info:"2 month warranty",
        description:"Selected aluminum die-casting materials, anti-oxidation, anti-corrosion and excellent heat dissipation effect. Adopts acrylic lens, light transmission is soft 2.This creative LED wall light is widely used in bedroom, bedside, living room, Lounge, girl room, bars, cafe and some other places as you 3.Simple Installation, Suitable for any smooth indoor surface, making for a stress-free setup. 4.It can complement the decoration of the space and provide more personality to your home decor. 5.The simple design integrates the lamp with the wall and bed board, making it suitable for various environments and creating a personalized working environment for you.",
        price: 3499,
    },
    {
        name:"Blissbells Wallchiere Wall Lamp With Bulb",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w5/3.png?raw=true",
        info:"2 month warranty",
        description:"Creative LED Wall Lamp Modern Minimalist Bedroom Bedside Lamp Nordic Aisle Decoration Background Wall Art Design Lighting",
        price: 3599,
    },
    {
        name:"Blissbells Wallchiere Wall Lamp With Bulb",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w6/3.png?raw=true",
        info:"2 month warranty",
        description:"Requires 2 E-14 Bulbs (Not Included) Design: Post-modern creative design wall-mounted fixture, gold metal tube & transparent crystal tube combination wall lamp, to meet the auxiliary lighting needs of your room. Size 60x25Cm Modern Industrial Style One-Light Indoor Wall Fixture Is Perfect For Use In Restaurant, Bedroom, Living Room, Bedside, Cafe, Bar, Corridor, Balcony. A Perfect Match With Retro-Industrial Style: Wood Color, Minimalist Wood Glass Shade Wall Sconces. This Vintage Antique Wall Lamp Comes With Every Element You Need For Creating A Retro-Industrial Style Environment. This Wall Sconce Is High Quality Chrome Crystal Light And Well Constructed. Circular Shape For Extra Bright Light Which Spreads On A Larger Area",
        price: 4449,
    },
    {
        name:"Blissbells Wallchiere Wall Lamp With Bulb",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w7/3.png?raw=true",
        info:"2 month warranty",
        description:"Suitable For exhibition hall, meeting room, supermarket, restaurant and amusement park etc. Architecture and home decoration, recessed/ceiling/wall lighting, cabinet/Counter, step lighting included. It is high quality traditional hanging light.",
        price: 4499,
    },
    {
        name:"Musa Kazim Handicrafts Picture Light Wall Lamp With Bulb",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w8/3.png?raw=true",
        info:"2 month warranty",
        description:"A wall panel is a decorative or functional element that is designed to cover and enhance the appearance of interior walls. These panels are typically made from a variety of materials, including wood, MDF (Medium Density Fiberboard), PVC (Polyvinyl Chloride), metal, fabric, leather, or other composite materials. Wall panels can serve both aesthetic and practical purposes, and they come in various styles, sizes, and designs to suit different interior design preferences.",
        price: 3389,
    },
    {
        name:"1st Time Wallchiere Wall Lamp With Bulb",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w9/3.png?raw=true",
        info:"2 month warranty",
        description:"Explore Our LED Wood Wall Lamp, A Stunning Lighting Piece That Effortlessly Transforms Your Home With Designer Lighting Effects. Crafted With Care And Expertise By 1st Time Enterprises, It Promises A Long-Lasting Life And An Aesthetic That's Simply Captivating. This Lamp Not Only Illuminates But Also Creates A Beautiful Designer Lighting Effect, Making It A True Eye-Catcher In Any Room. Its Attractive Design Adds A Touch Of Elegance To Your Decor, Enhancing The Visual Appeal Of Your Space. Easy To Install And Requiring No Maintenance, This LED Wood Wall Lamp Is Perfect For Indoor Lighting Decoration.",
        price: 670,
    },
    {
        name:"Blissbells Uplight Wall Lamp With Bulb",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/decorative/wall%20lamp/w10/3.png?raw=true",
        info:"2 month warranty",
        description:"Blissbells LED 7W warm white wall light product features a unique, modern look for lighting up the exterior of your home. Also suitable for indoor areas, ideal for Bedroom, the Corridor wall, Staircase, Balcony, Porch, Garden, and any other lighting occasions and decoration. It can be mounted directly on a wall and plugs in to your 86-265V mains, the product includes all fixing accessories for the ease of installation. Lamp creates a beautiful Up and Down lighting effect, adds romantic & harmonious atmosphere to your room. Material: Die cast aluminum.",
        price: 1099,
    },
];
module.exports = { data:wallLampData};