const airfdata=[
    {
        name:"AGARO Regency Air Fryer  (12 L)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF1/3.png?raw=true",
        info:"Pan Capacity 12L Power Consumption 1800w",
       description:"The Agaro Regency Air fryer has a temperature control system in it that lets you control the temperature as per your cooking requirements. You can control the temperature of this air fryer according to the food you are preparing.",
        price: 8799,
    },
    {
        name:"HAVELLS Prolife Crystal Air Fryer  (5 L)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF2/3.png?raw=true",
        info:"2 year warranty on product Power Consumption: 1500 W Capacity: 5 L",
        description:"Havells Air fryer lets you fry, bake, toast, roast, grill as well as reheat the food with hot air, keeping it up to 85% less oily over traditional deep frying. It features a patented round basket with slots at side wall for better air circulation",
        price: 9000,
    },
    {
        name:"Pigeon Healthifry digital airfryer 4.2 L 1200W Air Fryer  (4.2 L)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF3/3.png?raw=true",
        info:"Power Consumption: 1200 W  Power Requirement220 - 240 V",
        description:"Air Fryer Capacity: 4.2 liters capacity is enough to enjoy your favorite french fries, samosas and nuggets without the worry.Pigeon Healthifry Digital Air Fryer is one such appliance which is used to cook food with 85% less oil which means that with only one spoon of oil, you can cook your favorite foods.",
        price: 3017,
    },
    {
        name:"MasterChef NutriKing with Digital Touch Panel Air Fryer  (4.5 L",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF4/3.png?raw=true",
        info:"Pan Capacity4.5  power requirement AC 230 V, 50 Hz",
        description:"MasterChef 4.5L AirFryer is perfect for cooking family size options. Grill, Roast, Bake at easy with Uniform Heating and 360 degree circulation. Opt for an Healthy cooking with Less oil recipes. Non stick Cooking basket and tray to simplify the cooking process. 6 predefined menu options for indian Needs.",
        price: 2499,
    },
    {
        name:"IMPEX Air fryer DS45 Smart fry with Transparent window Air Fryer  (4.5 L)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF5/3.png?raw=true",
        info:"2 Year Free Home Service",
        description:"he air fryer with the setting function only is used for making fried foods such as meat, pastries and potato chips.Air Fryer Capacity: 4.5 liters capacity is enough to enjoy your favorite french fries, samosas and nuggets without the worry. ",
        price: 3499,
    },
    {
        name:"Glen Digital Air Fryer SA 3042 Air Fryer  (6 L)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF6/3.png?raw=true",
        info:"2 Year Manufacturer Warranty",
        description:"The Glen Digital Fryer circulates ultra hot air around your food, eliminating the need for all the oil you find in typical deep fried foods. The rapidly circulating hot air gets you healthier meals while still bringing you the same crispy on the outside & perfectly moist on the inside results",
        price: 4099,
    },
    {
        name:"LIBRA 6 Liter Air Fryer For Home uses 99% Less Fat with Preset Controls Air Fryer  (6 L)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF7/3.png?raw=true",
        info:"1 Year Manufacturer Warranty",
        description:"Power Consumption: 1200 W  Power Requirement220 - 240 V",
        price: 4299,
    },
    {
        name:"FABER FAF 2.0L DLX BK 1200W, Fry, Roast, Grill, Bake, Swirl Cooking, Cool Touch Handle, 85% Reduced Oil Usage, Auto Shut Off, BPA Free, Compact Sleek Design, Manual Control, Non-Stick Pan Air Fryer  (2 L)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF8/3.png?raw=true",
        info:"Power Consumption: 1200 W Capacity: 2 L",
        description:"85% Reduced Oil Usage, Auto Shut Off, BPA Free, Compact Sleek Design, Manual Control, Non-Stick Pan Air Fryer ",
        price: 2990,
    },
    {
        name:"AGARO 34029 Air Fryer  (4.5 L)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF9/3.png?raw=true",
        info:"Pan Capacity4.5 LPower Consumption 2400 W",
        description:"AGARO Imperial 2400W Non Stick Dual Basket Digital Air Fryer comes with two 4.5L baskets. It comes with 10 Preset Cooking Modes, Digital Display withTouch Screen",
        price: 9309,
    },
    {
        name:"Inalsa Nutri Fry Dual Zone , 2100W , XL 10litres Capacity , Digital Display Air Fryer  (10 L)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/AIR%20FRYER/AF10/3.png?raw=true",
        info:"2 Years Warranty by Inalsa",
        description:"Manufacturing Defects",
        price: 8795,
    },
];
module.exports = { data: airfdata };
