const chimneyData=[
    {
        name:"Whirlpool CLASSIC CF 60 BK HOOD Wall Mounted Chimney  (Black 750 CMH)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney1/3.png?raw=true",
        info:"5 years on Motor and 1 year comprehensive from Date of Purchase.",
        description:"5 years on Motor and 1 year comprehensive from Date of Purchase.",
        price: 5590,
    },
    {
        name:"ruwa VIVA 60 BLACK Wall Mounted Chimney  (Black 800 CMH",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney2/3.png?raw=true",
        info:"To avail warranty please register your product's warranty online. Please note the warranty will not be considered if not registered online.",
        description:"High efficiency Motor with Suction 800 m3/Hr, Easy to clean Baffle filters, 3 Speed Push buttons, LED light with 1 year comprehensive warranty and 3 years warranty on Motor. The Installation / Services are Chargeable and does not include in the price of the chimney",
        price: 3499,
    },
    {
        name:"ONLINE Allia Chimney 60 Cms, Push Control, BAFFLE FILTER, 1 Year General Warranty Wall Mounted Chimney  (Black 800 CMH)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney3/3.png?raw=true",
        info:"Warranty: 1 year General Warranty (Main PCB and Blower- 5 years, Motor: Lifetime), For warranty registration, Kindly check our manufacturer details on the product details below and contact us on the given number. Online works on customer delight. We look to deliver you the best service within a minimum time.",
        description:" Warranty: 1 year General Warranty (Main PCB and Blower- 2 years, Motor: Lifetime), For warranty registration, Kindly check our manufacturer details on the product details below and contact us on the given number. Online works on customer delight",
        price: 4590,
    },
    {
        name:"Kutchina SIGNIA 90 Auto Clean Wall Mounted Chimney  (black 1250 CMH)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney4/3.png?raw=true",
        info:"Domestic warranty, only lifetime warranty on motor (9 years) 1 year warranty on product",
        description:"he Signia 90 kitchen chimney by Kutchina is all you need to keep your kitchen smoke-free. With a suction capacity of 1200 m3/hr. The chimney efficiently removes smoke and greasy particles from your kitchen, thereby keeping it clean.",
        price: 10499,
    },
    {
        name:"WONDERCHEF Ruby Sleek 60CM Auto Clean Wall Mounted Chimney  (Black 1400 CMH)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney5/3.png?raw=true",
        info:"2 Year Warranty on Motor & 1 Year on comprehensive",
        description:"Warranty of the product is limited to manufacturing defects only",
        price: 9499,
    },
    {
        name:"Elica WD TFL HAC 90 MS NERO with Installation Kit Included Auto Clean Wall Mounted Chimney  (Black 1425 CMH)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney6/1.png?raw=true",
         image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney6/3.png?raw=true",
        info:"15 Years Warranty on Motor and 2 Years Comprehensive Warranty.",
        description:"Filterless Technology,Good Suction Capacity",
        price: 16249,
    },
    {
        name:"Elica EFL 207 HAC LTW VMS 60 Auto Clean Wall Mounted Chimney  (Black 1350 CMH)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney7/3.png?raw=true",
        info:"Lifetime (15 years) on Motor and 2 years comprehensive from Date of Purchase.",
        description:"Elica No Filter Technology kitchen chimneys offer comfort and convenience during your cooking process. You can do away with the smoke and the odour with the metal blower system available in the chimney. ",
        price: 13890,
    },
    {
        name:"Hindware Greta Neo Autoclean 60 Auto Clean with Powerful Suction Capacity,Motion Sensor Wall Mounted Chimney  (Black 1350 CMH)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney8/3.png?raw=true",
        info:"2 Years Comprehensive & 10 Years On Motor",
        description:"Manufacturing Defects",
        price: 16749,
    },
    {
        name:"kraft GRAZIE 60 Auto Clean Wall Mounted Chimney  (STAINLESS STEEL 2200 CMH",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney9/1%20(1).png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney9/2.png?raw=true",
        info:"2 Years Comprehensive & 10 Years On Motor",
        description:"Enhance the look of your kitchen with the charming design of Kraft kitchen chimney! This chimney is your ticket to a hassle free cooking experience. Continuous exposure to smoke and strong aromas affect your health. ",
        price: 14989,
    },
    {
        name:"FABER HOOD BLISS FL SC AC BK 90 Auto Clean Slant Glass 90 cm| Touch & Gesture Control| Autoclean| Filterless|Powerful Suction|Low Noise Wall Mounted Chimney  (Black 1350 CMH)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/chimneys/chimney10/3.png?raw=true",
        info:"2 years on product, 12 years on motor",
        description:"Manufacturing Defects only  Not Covered in WarrantyGlass, Damage caused to finish due to usage",
        price: 22740,
    },
];
module.exports = { data: chimneyData };