const cmData=[
    {
        name:"PHILIPS HD7432/20 7 Cups Coffee Maker  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM1/3.png?raw=true",
        info:"2 Years Warranty",
        description:"Manufacturing Defect",
        price: 3299,
    },
    {
        name:"AGARO Imperial Espresso Coffee Maker, Coffee Machine, 15 Bars, 6 Cups Coffee Maker  (Silver)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM2/3.png?raw=true",
        info:"1 Year",
        description:"Manufacturing Defect",
        price: 9299,
    },
    {
        name:"AGARO Grand Coffee Grinder, Stainless Steel Electric, Capacity 60 Gms Dry Coffee Bean 6 Cups Coffee Maker  (Silver)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM3/3.png?raw=true",
        info:"1 year",
        description:"manufacturing warranty",
        price: 1299,
    },
    {
        name:"Bialetti Moka Express Red 3 Cups Coffee Maker  (Red)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM4/3.png?raw=true",
        info:"Six month of International and domestic warranty/",
        description:"Enduring quality & design The Bialetti Moka celebrates more than 80 years of classic design elegance and technological simplicity. From the early 1950s to the present day, Bialetti has manufactured over 200 million coffee makers. In particular, the Moka",
        price: 4603,
    },
    {
        name:"AGARO Supreme Coffee Grinder With Portafilter Holder Conical Burr Grinder, 15 Cups Coffee Maker  (Silver)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM5/3.png?raw=true",
        info:"1 Year Warranty for manufacturing defects",
        description:"Manufacturing defects",
        price: 5990,
    },
    {
        name:"Morphy Richards Europa Xpresso 4 Cups Coffee Maker  (Black",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM6/1%20(1).png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM6/3.png?raw=true",
        info:"1 YEAR SERVICE ON MAIN PRODUCT",
        description:"Manufacturing Defects",
        price: 4640,
    },
    {
        name:"AGARO Regency Espresso Coffee Maker, Adjustable Pressure up to 20 Bars, 2 Cups Coffee Maker  (White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM7/3.png?raw=true",
        info:"1 Year Warranty",
        description:"Manufacturing defects",
        price: 10990,
    },
    {
        name:"AGARO Supreme Espresso Coffee Maker With Grinder, 20 Bars Semi Automatic 2 Cups Coffee Maker  (Silver)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM8/3.png?raw=true",
        info:"1 Year",
        description:"MANUFACTURING WARRANTY",
        price: 32990,
    },
    {
        name:"Morphy Richards AutoPresso 3-In-1 6 Cups Coffee Maker  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM9/3.png?raw=true",
        info:"Manufacturing Defects",
        description:"Manufacturing Defects",
        price: 17290,
    },
    {
        name:"Kaff FONTANA RED Coffee Machine 2 Cups Coffee Maker  (Red)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM10/2.png?raw=true ",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/coffee%20meaker/CM10/3.png?raw=true",
        info:"1 year on product",
        description:"Suitable for ground Coffee Can do Coffee or Steam Conveniently 1350 Watts, 19 Bar High Pressure Pump 1.4L Detachable Transparent Food Grade water tank Volumetric control : Preset 1 and 2 Cup With safety valve.",
        price: 10990,
    },
];
module.exports = { data: cmData};
