const dwData=[
    {
        name:"Midea TORRINO,WQP12-5201F Free Standing 13 Place Settings Intensive Kadhai Cleaning| No Pre-rinse Required Dishwasher",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW1/3.png?raw=true",
        info:"2 Years Comprehensive Warranty on Product",
        description:"Warranty Covers Only Manufacturing Defects in Material and Workmanship that may Arise Despite Normal Operation and Usage of the Appliance as Mentioned in the Operating Manual",
        price: 22990,
    },
    {
        name:"IFB Neptune VX1, Dark Silver, In Built Heater with Hygienic Steam & Water Softener Built-in 12 Place Settings Dishwasher",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW2/3.png?raw=true",
        info:"2 Years & 8 Years Spare Parts Support",
        description:"Warranty of the product is limited to manufacturing defects only.",
        price: 44000,
    },
    {
        name:"BOSCH SMS66GW01I Free Standing 13 Place Settings Intensive Kadhai Cleaning| No Pre-rinse Required Dishwasher",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW3/Screenshot%202024-04-08%20212213.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW3/3.png?raw=true",
        info:"2 Years on Product",
        description:"Warranty Is Confined Only to the First Purchase of the Appliance and is Non- Transferrable. Warranty Period Starts from the Date of Purchase of Product. Warranty Covers Only Manufacturing Defects in Material and Workmanship that may Arise Despite Normal Operation and Usage of the Appliance as Mentioned in the Operating Manual",
        price: 41500,
    },
    {
        name:"Kaff DW VETRA Free Standing 12 Place Settings Dishwasher",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW4/3.png?raw=true",
        info:"5 YEARS WARRANTY ON MOTOR & WASHING PUMP & 2 YEARS WARRANTY ON PARTS.",
        description:"Free standing dishwasher Stainless steel finish door panel and interior 12 standard place settings Adjustable automatic rinse agent detergent Automatic detergent dispenser Salt container with water softener Safety interlock door mechanism Quiet operation A+ energy efficiency Upper and lower spray arm Three stage filtration Touch control with Digital display Half load Delay function.",
        price: 43990,
    },
    {
        name:"Crompton FS-DWVOA13PS-ENT Free Standing 13 Place Settings Dishwasher",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW5/3.png?raw=true",
        info:"2 Years Comprehensive Warranty and 10 Years Warranty on Motor",
        description:"Crompton's 13-place setting dishwasher is tailored for families of 4-6 members, offering a comprehensive package. Boasting 5 wash programs, such as Intensive for heavy utensils and Eco for energy savings, it caters to diverse needs.",
        price: 33999,
    },
    {
        name:"BOSCH SMS6HVI01I/SMS6HVI00I Free Standing 14 Place Settings Dishwasher",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW6/3.png?raw=true",
        info:"2 years warranty on product and 10 years warranty against rust through on",
        description:"Warranty Is Confined Only to the First Purchase of the Appliance and is Non- Transferrable. Warranty Period Starts from the Date of Purchase of Product. Warranty Covers Only Manufacturing Defects in Material and Workmanship that may Arise Despite Normal Operation and Usage of the Appliance as Mentioned in the Operating Manual",
        price: 56999,
    },
    {
        name:"BOSCH SMS6ITI01I Free Standing 13 Place Settings Dishwasher",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW7/3.png?raw=true",
        info:"2 Years on Product",
        description:"Warranty Is Confined Only to the First Purchase of the Appliance and is Non- Transferrable. Warranty Period Starts from the Date of Purchase of Product. Warranty Covers Only Manufacturing Defects in Material and Workmanship that may Arise Despite Normal Operation and Usage of the Appliance as Mentioned in the Operating Manual",
        price: 51999,
    },
    {
        name:"BOSCH SMI4IVS00I Built-in 13 Place Settings Dishwasher",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW8/3.png?raw=true",
        info:"2 Years Warranty on Product",
        description:"Warranty Covers Only Manufacturing Defects in Material and Workmanship that may Arise Despite Normal Operation and Usage of the Appliance as Mentioned in the Operating Manual",
        price: 78490,
    },
    {
        name:"Hindware ITALO WITH HALF LOAD FUNCTION, HEATING ELEMENT AND A+ ENERGY EFFICIENCY Free Standing 12 Place Settings Dishwasher",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW9/3.png?raw=true",
        info:"2 Years Comprehensive",
        description:"HALF LOAD FUNCTION, INTENSIVE, NORMAL, ECO, GLASS",
        price: 23930,
    },
    {
        name:"FABER FFSD 6PR 8S ACE BLACK Free Standing 8 Place Settings Intensive Kadhai Cleaning| No Pre-rinse Required Dishwasher",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/DISHWASHER/DW10/3.png?raw=true",
        info:"2 Years on Product and 5 Years on Rust Through from Faber",
        description:"Warranty Covers Only Manufacturing Defects in Material and Workmanship that may Arise Despite Normal Operation and Usage of the Appliance as Mentioned in the Operating Manual",
        price: 24725,
    },
];
module.exports = { data: dwData};
