const eCockrData=[
    {
        name:"WONDERCHEF Nutri-Pot Electric Pressure Cooker  (6 L, Black & Silver)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC1/3.png?raw=true",
        info:"2 Years Accessories",
        description:"Make cooking convenient for you and your family with the 6 L Wonderchef Nutri-pot Electric Pressure Cooker. You just need to put the ingredients inside, set a cooking function, and this cooker cooks without hassles",
        price: 6999,
    },
    {
        name:"WONDERCHEF Nutri Pot Electric Pressure Cooker  (3 L, Black & Silver)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC2/3.png?raw=true",
        info:"Capacity 3 L Total Pan Capacity 3 L",
        description:"You can enjoy cooking different dishes of your choice with the Wonderchef Nutri-pot 3 L Electric Pressure Cooker. This automatic appliance requires you to just add the ingredients inside, press the button, and it will perform all the cooking tasks for you",
        price: 5799,
    },
    {
        name:"Lifelong LLEPC922 Electric Pressure Cooker  (5 L, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC3/3.png?raw=true",
        info:"1 Year Lifelong Online Retail Pvt. Ltd. Domestic Warranty",
        description:"Any manufacturing defects upto 1 year of purchase",
        price: 5799,
    },
    {
        name:"BAJAJ Majesty RCX28 Deluxe Multifunction Electric Rice Cooker  (2.8 L, White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC4/3.png?raw=true",
        info:"2 Year Company Warranty",
        description:"Warranty of the product is limited to manufacturing defects only",
        price: 4050,
    },
    {
        name:"BAJAJ Majesty RCX 28 Electric Rice Cooker  (2.8 L, White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC5/3.png?raw=true",
        info:"2 years Manufacture Defualt",
        description:"f you are a passionate cook and love calling friends and family home for dinner, then this electric rice cooker from Bajaj is what you need. This 2.8L rice cooker makes your task of cooking for a large crowd easy",
        price: 3990,
    },
    {
        name:"SKYTONE Electric Rice Cooker - Multi Purpose Cooker and Food Steamer Electric Pressure Cooker  (5 L, Maroon)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC6/3.png?raw=true",
        info:"1 Year Manufacturer Warranty",
        description:"ALL-IN-1 FUNCTIONALITY: Pressure Cook, Slow Cook, Rice Cooker, Gravy, Biriyani, Khichadi, Chicken, Sambar, Yogurt Maker, Steamer, Sauté pan, Bean/Grain, Meat/Poultry, Oatmeal/Porridgeand food warmer. NUTRITIOUS MEALS EVERY TIME - The unique locking system preserves the food's nutrition, while the anodized aluminum pot prevents",
        price: 6749,
    },
    {
        name:"Panasonic SR-WA22H(SS) Electric Rice Cooker with Steaming Feature  (2.2 L, Gold)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC7/3.png?raw=true",
        info:"2 Year for the Product and 5 Years for the Heater",
        description:"Anodized Aluminium Pan,Circular Coil for Even Heating",
        price: 3199,
    },
    {
        name:"Kuvings KMP 600 Electric Pressure Cooker Electric Pressure Cooker  (6 L, Silver)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC8/3.png?raw=true",
        info:"5 Years on Heating Element & 6 Months on Parts",
        description:"Electric Pressure Cooker with Multiple Cooking Options like: Pressure Cook, Slow Cook, Saute, Steam, Egg, Cake, Yogurt, Porridge, Multi Grain, Rice, Soup, Beans, Poultry and Meat.",
        price: 14019,
    },
    {
        name:"AGARO Regal Electric Rice Cooker  (3 L, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC9/3.png?raw=true",
        info:"1 Year Warranty",
        description:"AGARO Regal Electric Rice Cooker, 3L, Ceramic Inner Bowl with SS Steamer, Preset cooking functions, Multi Cooking Modes, Black",
        price: 3999,
    },
    {
        name:"Wellspire Instant Pot with #304 Stainless Steel Inner Pot Electric Pressure Cooker  (6 L, Tranquil Green)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Electric%20cooker/EC10/3.png?raw=true",
        info:"3 years for Heating plate and 1 year on other electronic parts",
        description:"BEST BRAND FOR ELECTRIC PRESSURE COOKER: Wellspire has brought happiness to more than 5 Lac families across India, and over years it has won customers' trust for having premium quality products and robust after-sales service across India. SAFTY FIRST: Wellspire Instant pot 6L Electric Pressure Cooker is tested & approved by BIS",
        price: 5999,
    },
];
module.exports = { data: eCockrData};
