const grinderData=[
    {
        name:"PHILIPS Avance Collection HL7707 750 W Mixer Grinder with Gear Drive Technology, PowerChop Technology (4 Jars, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder1/3.png?raw=true",
        info:"5 Years warranty on motors by Philips , Manufacturing Defects",
        description:"The Philips Avance Collection HL7707 750 W Mixer Grinder makes it easy for you to grind, blend, and knead various food ingredients with ease. This kitchen appliance comes with a 750 W Motor, the Gear Drive Technology, and Multiple Attachments for effortless and effective performance.",
        price: 7699,
    },
    {
        name:"Butterfly MAGIC / MAGIC 5 JAR Rapid Food Processor 750 Juicer Mixer Grinder Atta Kneading, Veggie Chopping Features and India's First cool touch Chutney Jar with Air-Gap Cooling (5 Jars, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder2/3.png?raw=true",
        info:"2 Year Manufacturer Warranty",
        description:"Butterfly Magic 5 Jar mixer grinder comes with a powerful 750W overload protected motor. Whip up chutneys, grind masalas, chopping, kneading atta, making smoothies & shakes for summer effortlessly with the Butterfly Magic Mixer Grinde",
        price: 3799,
    },
    {
        name:"BAJAJ by Bajaj NEO JX4 B07DMM41W1 450 Juicer Mixer Grinder (2 Jars, Multicolor)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder3/3.png?raw=true",
        info:"manufacturer default",
        description:"Power Required 230V Revolutions 18000",
        price: 3199,
    },
    {
        name:"Butterfly Rapid - 4J / Rapid 750 W Juicer Mixer Grinder (4 Jars, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder4/3.png?raw=true",
        info:"2 Years Limited Domestic Brand Warranty",
        description:"Butterfly Rapid 4 jar mixer grinder comes with a powerful 750W overload protected motor. Whip up chutneys, grind masalas and prepare yummy shakes effortlessly with the Butterfly Rapid Mixer Grinder. This mixer grinder with its 4 multipurpose jars makes cooking easy and convenient.",
        price: 2799,
    },
    {
        name:"USHA JMG -3345 8956 450 Mixer Grinder (2 Jars, White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder5/3.png?raw=true",
        info:"One Unit of Juicer Mixer Grinder, One Liquidizing Jar with Lid, One Grinder Jar With Lid, Juicer Mesh, Pusher, Spatula",
        description:"Multifunctional Appliance,Durable and Powerful,High-performance Motor,Versatile Usage",
        price: 3150,
    },
    {
        name:"WONDERCHEF Nutri-blend 22000 RPM 400 W Juicer Mixer Grinder 2 Years Warranty (2 Jars, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder6/3.png?raw=true",
        info:"2 Years Wonderchef Warranty",
        description:"If you love smoothies, then this juicer, mixer, and grinder from Wonderchef is your choice. Its compact size takes up less space in your kitchen. It comes with two jars and all kinds of blades to offer you an optimum blending experience. Furthermore, it has a push start button which makes grinding and blending quick and easy.",
        price: 2499,
    },
    {
        name:"USHA FP 3811 1000 W Juicer Mixer Grinder (5 Jars, Steel, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder7/3.png?raw=true",
        info:"2 Years on Product and 5 Years on Motor",
        description:"1 Mixer Grinder Juicer, Processing Bowl with Lid, Pusher, Centrifugal Juicer Assembly, Citrus Juicer Assembly, Blender Jar, Multipurpose Jar, Chutney Jar, Chopping Blade, Atta Kneading Blade, Slicing Blade, Grating Blade, Shredding Blade, Blade Holder, Whisker, Spindle, Spatula, User Manual",
        price: 12280,
    },
    {
        name:"Prestige Macho Watt- 1000 Juicer Mixer Grinder (6 Jars, Black, Silver)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder8/3.png?raw=true",
        info:"2 Years Warranty On Product And 5 Years Warranty On Motor",
        description:"Presenting the new Prestige Macho Mixer Grinder that can take care of all your grinding and juicing needs, and look stunning while doing so. Embodying true versatility, this mixer grinder, powered by a 1000-watt motor can grind both wet and dry ingredients so, you can have chutney for your dosas, powdered masala for your curries, and more ",
        price: 6690,
    },
    {
        name:"HAVELLS Vitonica 500 W Juicer Mixer Grinder (3 Jars, White - Light Blue)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder9/3.png?raw=true",
        info:"2 Years Comprehensive Warranty",
        description:"Havells Vitonica GHFJMDDE050 500 W Juicer Mixer Grinder (White and Blue, 3 Jar)",
        price: 1,
    },
    {
        name:"HAVELLS Silencio Low Noise 500 W Mixer Grinder 4 Jars (Grey & Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/juicer%20and%20mixer%20grinder/grinder10/3.png?raw=true",
        info:"2 Years Warranty on Product and 5 Years Warranty on Motor",
        description:"You can whip up healthy shakes for breakfast, grind spices for various recipes, and prepare a range of delicious condiments by bringing home the HAVELLS Silencio mixer grinder. Equipped with double-layer insulated jar technology, this mixer grinder minimises noise during operations and keeps the outer surface cool for comfortable handling",
        price: 14995,
    },
];
module.exports = { data: grinderData};
