const inductionData=[
    {
        name:"PHILIPS HD4938/01 Induction Cooktop  (Black, Touch Panel)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP1/3.png?raw=true",
        info:"The Philips cook top offers 1 Year warranty",
        description:"Upgrade your kitchen with the Philips HD4938/01 Induction Cooktop that helps you maintain a minimalist, tidy, and mess-free cooking area. This induction cooktop comes with ten preset menus to let you cook different Indian dishes.",
        price: 4499,
    },
    {
        name:"BAJAJ Majesty Slim 2100 Watt Induction Cooktop  (Black, Touch Panel)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP2/3.png?raw=true",
        info:"Power Consumption: 2100 W Automatic shut-off:Yes",
        description:"2100 Watts Induction Cooktop for higher range of power and fast cooking 8 Auto Cook Indian menus lets you variety of dishes at the touch of a button. Boil : Yes Variable Time, Temperature & Power Selection to cook various kind of dishes Feather Touch Controls for your aesthetics and convenience. ",
        price: 3780,
    },
    {
        name:"PHILIPS HD4928/01 Induction Cooktop  (Black, Push Button)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP3/2.png?raw=true",
        info:"The Philips cook top offers 1 Year warranty",
        description:"Cooking is not one of those things that come naturally to you. The stove and gas connection might be a little intimidating but you don’t have to worry. The Philips HD4928 Induction Cook Top ensures that you never have to worry about another meal again. All you have to do is switch it on and the table awaits for your feast.",
        price: 2999,
    },
    {
        name:"Prestige Atlas Touch Induction 2000W Induction Cooktop  (Black, Touch Panel)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP4/3.png?raw=true",
        info:"1 Year Manufacturer Warranty",
        description:"Manufacturinf Defects Only",
        price: 2599,
    },
    {
        name:"Prestige Atlas 2.0 Induction Cooktop  (Black, Red, Touch Panel)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP5/3.png?raw=true",
        info:"1 Year Manufacturer Warranty",
        description:"Combining optimal performance with a sleek design, the Prestige Atlas 2.0 Induction Cooktop is a must-have. It requires very little storage space on your kitchen countertop with its sleek and minimalist design. Featuring a quick and efficient performance, this induction cooktop ensures a user-friendly experience. ",
        price: 2999,
    },
    {
        name:"Prestige PIC 3.1 v3 Induction Cooktop  (Black, Push Button)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP6/3.png?raw=true",
        info:"1 Year Prestige India Warranty",
        description:"The Prestige PIC 3.1 v3 induction cooktop is a useful kitchen appliance that comes in handy for rustling up a wide variety of delicious Indian dishes. It can help simplify your everyday cooking routine as it is equipped with a wide variety of preset options.",
        price: 3660,
    },
    {
        name:"USHA INDUCTION COOKTOP IC-CJ2000WTC Induction Cooktop  (Black, Touch Panel)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP7/3.png?raw=true",
        info:"1 YEAR WARRANTY",
        description:"NDUCTION COOK TOP SLIMMEST INDUCTION EVER 2000W",
        price: 3149,
    },
    {
        name:"HAVELLS by HAVELLS INDIA LTD GHCICDRK120 Induction Cooktop  (Black, Touch Panel)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP8/3.png?raw=true",
        info:"Manufacturing Defects and electrical faults",
        description:"Intelligent programs with auto pan detection sensor and auto power off Powerful 2 W for quicker cooking 9 different modes of cooking; Up to 3 hrs. pre set timer for greater convenience in usage Automatic protection at higher temperature; Soft and full touch enabled operations Digital LED Indicator for easy operation; Child lock function for enhanced safety",
        price: 3999,
    },
    {
        name:"KWW STOVA IR-IF01 Radiant Cooktop  (Black, Touch Panel)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP9/3.png?raw=true",
        info:"1 Year Warranty on Manufacturing Defects",
        description:"KWW Stova Infrared Induction Cooktop touch panel is a 2000w quick heating electric induction stove cooker suitable for all types of utensils. Its latest infrared technology warms up the center of the wide cooking surface faster than a traditional induction cooker, it has a higher heat conduction effect",
        price: 2992,
    },
    {
        name:"UNIDUS S9 2000W INFRARED WITH GRILL Radiant Cooktop  (Gold, Black, Jog Dial, Touch Panel)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/induction%20tops/INDUCTION%20TOP10/3.png?raw=true",
        info:"1 Year Limited Domestic Brand Warranty",
        description:"UNIDUS presents a whole new range of electric induction cooktops. The product is powered by a strong 2000-watt infrared heating element that provides longevity and smooth, quiet cooking. It comes with various modes for cooking and a digital LED touch panel display for easy operations",
        price: 2157,
    },
];
module.exports = { data: inductionData};
