const ovenData=[
    {
        name:"LG 28 L Diet Fry and 360 Motorised Rotisserie for crispy and tasty bar-be-que recipes Convection Microwave Oven  (MC2886BRUM, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven1/3.png?raw=true",
        info:"Manufacturer Warranty: 1 year on Product from the date of purchase ,Parts & Labour: Covered under Warranty against any Defect arising out of Faulty or Defective Material or Workmanship.",
        description:"Pleasing to the eyes and (especially) your stomach. This 28 L LG microwave oven comes with innovative features that will make cooking feel like a piece of cake (pun intended). It’s equipped with a Diet Fry feature that lets you cook mouth-watering dishes with minimal oil. ",
        price: 16290,
    },
    {
        name:"LG 32 L Diet Fry and 360 Motorised Rotisserie for crispy and tasty bar-be-que recipes Convection Microwave Oven  (MC3286BLU, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven2/3.png?raw=true",
        info:"Manufacturer Warranty: 1 year on Product from the date of purchase",
        description:"LG 32 L Convection Microwave Oven MC3286BLU Black",
        price: 15990,
    },
    {
        name:"SAMSUNG 28 L Curd Making, A Perfect Gift With 10 Yr Warranty Convection & Grill Microwave Oven  (MC28A5013AK, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven3/3.png?raw=true",
        info:"1 Year Standard Warranty on Product, 10 Years Warranty on Ceramic Enamel Cavity",
        description:"You can serve delicious meals to your family with the Samsung 28 L Convection and Grill Microwave Oven. With its Auto Cook menu, this microwave oven lets you select from a host of preprogrammed Indian recipes. Owing to its Fermentation function, this microwave oven makes use of sophisticated fermentation technology that can make fresh dough and yogurt at the proper temperature",
        price: 12490,
    },
    {
        name:"IFB 24 L Solo Microwave Oven  (24PM2B, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven4/3.png?raw=true",
        info:"24 L SoloTouch Key Pad (Membrane) is sensitive to touch and easy to cleanChild Lock : Ensures complete safety especially for homes with small children",
        description:" IFB 25 L Solo Microwave Oven 24PM2B Black",
        price: 7999,
    },
    {
        name:"Voltas Beko 20 L Smart Convection Microwave Oven  (MC20SD, Silver)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven5/3.png?raw=true",
        info:"20 LConvection : Can be used for baking along with grilling, reheating, defrosting and cookingTouch Key Pad (Membrane) is sensitive to touch and easy to clean",
        description:"Microwave Type : Convection Cavity Capacity : 20 L Maximum Microwave Power : 1200 Microwave Control Type : Electronic No. of Microwave Power Levels : 10 Warranty : 01 year comprehensive + additional 01 year on Magnetron  ",
        price: 8490,
    },
    {
        name:"LG 20 L i-wave Technology and Anti Bacteria Cavity Solo Microwave Oven  (MS2043BP, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven6/3.png?raw=true",
        info:"Manufacturer Warranty: 1 year on Product from the date of purchase",
        description:"Make eating healthy, homemade food your second nature by bringing home this LG 20 L Solo Microwave Oven. This kitchen essential features LG’s i-wave technology for fast and healthy cooking, an Anti Bacteria Cavity for an odour-free interior, and an Even Reheat and Defrost Function to ensure that cooking is an effortless task for you.",
        price: 6890,
    },
    
    {
        name:"LG 32 L Wi-Fi Enabled Scan to Cook & 360 degreeMotorised Rotisserie Convection Microwave Oven  (MJEN326PKW, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven7/3.png?raw=true",
        info:"Manufacturer Warranty: 1 year on Product from the date of purchase | 10 Year Warranty Applicable only on Charcoal Heater (Parts Only)",
        description:"LG 32 L Convection Microwave Oven MJEN326PKW Black",
        price: 23990,
    },
    {
        name:"LG 21 L Convection Microwave Oven  (MC2146BG, BLACK)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven8/3.png?raw=true",
        info:" 1 year warranty on Product from LG",
        description:"his LG Microwave Oven is designed to simplify your life; whether you’re someone who’s looking for an appliance which will help you explore different ways to prepare your favourite dishes, or if you’re a person who is looking to cut down on your daily calorie intake. This oven comes with the Health Plus Menu feature which lets you prepare food in a healthy way.",
        price: 11090,
    },
    {
        name:"Compare Share SAMSUNG 32 L Convection & Grill Microwave Oven  (MC32B7382QD/TL, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven9/3.png?raw=true",
        info:"32 L Convection & Grill Touch Key Pad (Membrane) is sensitive to touch and easy to clean",
        description:" Product Have Smart Control (Wi-Fi Connectivity), SmartThings Cooking, Wide Grill",
        price: 28740,
    },
    {
        name:"Pigeon 20-Litre 16321 Oven Toaster Grill (OTG)  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven10/1.png?raw=true ",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/oven/oven10/3.png?raw=true",
        info:"1 year warranty against the manufacturing defects",
        description:"Convection & Grill Function Cooling Function Accessories: Baking Plate Auto Deodorizer Auto Protection Auto Reminder Digital Display Express Cooking",
        price: 3665,
    },
];
module.exports = { data: ovenData};
