const sandwichData=[
    {
        name:"Prestige by Prestige PGMFB Toast  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM1/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM1/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM1/3.png?raw=true",
        info:"1 Year Domestic Warranty",
        description:"You can easily make toast and delectable sandwiches with the Prestige PGMFB Sandwich Maker. Built with a durable non-stick coating, this sandwich maker lets you effortlessly make delicious sandwiches while using minimal oil or butter.",
        price: 1380,
    },
    {
        name:"iBELL SM1515 Sandwich Maker with Floating Hinges, 1000 Watt, Panini / / Toast, Grill  (Black, Silver)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM2/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM2/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM2/Screenshot%202024-04-10%20233723.png?raw=true",
        info:"1 Year Standard Warranty + 1 Year additional Warranty on Registration (Connect to 1800-2020-260)",
        description:"iBELL sandwich makers: Prepare healthy and tasty sandwiches in the convenience of your kitchen. It has an attractive finish, making it a stylish modern day kitchen appliance with an grip handle and helps you instant sandwich. Sandwich / Panini Maker with Thermostatically Controlled Heating Elemen",
        price: 1474,
    },
    {
        name:"iBELL SM1201G Sandwich Maker, Electric, Floating Hinges, 4 Bread Big Size, Grill and Toast  (Silver, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM3/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM3/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM3/Screenshot%202024-04-10%20233758.png?raw=true",
        info:"1 Year Standard Warranty + 1 Year additional Warranty on Registration",
        description:"andwich Maker with Thermostatically controlled Heating Element. Adjustable hinges which adjusts to any size of toast or snack. Red indicator – Power on & ready; Green Indicator turns off automatically once grilling plates are heated Non-Stick Sandwich Plates |",
        price: 2999,
    },
    {
        name:"Morphy Richards LUXE TWG Grill, Toast, Waffle  (ROSEGOLD, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM4/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM4/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM4/3.png?raw=true",
        info:"2 YEARS ON SITE",
        description:"PRODUCT FEATURES: 3-in-1 Sandwich Toaster: Make toasts, waffles and grills! Ilag Swiss coating for easy cleaning and long coating life. Easy to maintain interchangeable plates 750W power for quick heating Glossy rose gold finish Anti skid feet for stability In-built cord winder Power on and ready indicator",
        price: 2940,
    },
    {
        name:"HAVELLS big fill Grill  (Silver)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM5/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM5/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM5/3.png?raw=true",
        info:"1 year warranty,physical damage is not covered ",
        description:"Product Description , Rapid Performance,Indicator Lights ",
        price: 2199,
    },
    {
        name:"Morphy Richards by morphy richards 370072 Toast  (BLACK ANS SS)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM6/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM6/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM6/3.png?raw=true",
        info:"2 Years Warranty on Product, imperio grill sandwich maker toaster",
        description:"500W power For quick and Crisp cooking Droping oil Container avoid mess with Easy disposal 180* opening angle for open barbecues and grill Sandwich",
        price: 2850,
    },
    {
        name:"Pigeon 15968 Grill, Toast, Waffle  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM7/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM7/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM7/3.png?raw=true",
        info:"1 Year Warranty",
        description:"Pigeon 15968 Grill, Toast, Waffle Black",
        price: 1999,
    },
    {
        name:"BOROSIL JUMBO GRILL BGRILLSS22 Toast, Grill  (Silver, Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM8/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM8/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM8/3.png?raw=true",
        info:"2 Years Domestic Warranty On Product",
        description:"Brand: Borosil, Specification - 230V - 50Hz, 1000W Power, 2 Year Warranty on Product. Large Size Non Stick Coated Heating Plate For 4 Slice Grilling, Red & Green Operation Indication Display. Slide Type Plate Locking. Heating Plate Openable Angle 105 Degrees, Non Stick Grill Surface, Thermal Fuse For Extra Safety.",
        price:2651,
    },
    {
        name:"BOROSIL SuperJumbo 180 Grill Sandwich Maker Grill  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM9/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM9/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM9/3.png?raw=true",
        info:"2 Years Domestic Warranty On Product",
        description:"The Borosil Super Jumbo 180 Grill Sandwich Maker allows you to make 4 sandwiches with the jumbo sized slices, at the same time! The oil collector tray is your perfect health check - it ensures that the sandwich maker uses only as much oil or butter as necessary, and all the extra drips out. The lid opens up 180°, allowing for easy assembly and removal.",
        price: 5999,
    },
    {
        name:"BAJAJ by Bajaj NEW GRILL ULTRA MAJESTY Grill  (Gray,Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM10/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM10/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/sandwich%20maker/SM10/3.png?raw=true",
        info:"2 Year Warranty on Product",
        description:"1. SS Outer body and Front Panel. 2. 4 Slice Press Sandwich Maker with Open Contact Grill. 3. 180 degree Flat-Bed Open grill or Griddle. 4. Adjustable Temperature control Knob. 5. Neon Indicator for Power and ready to Cook. 6. Non-Stick Coating Plate for Easy Cleaning. 7. Automatically adjustable Floating Hinges. 8. Drip Collector Bowl for Collecting Excess Oil. 9. 2000W Power.",
        price: 4799,
    },
];
module.exports = { data: sandwichData};
