const tosterData=[
    {
        name:"AGARO Grand 4 Slice 2300 W Pop Up Toaster  (Grey, Red)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%201/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%201/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%201/3.png?raw=true",
        info:"Brand AGARO, Model Grand 4 SliceColor, Grey, Red",
        description:"The 4 Slice Pop up Toaster from AGARO offers a simple yet effective way to make crispy toast within minutes. The toaster comes with a 4-slice capacity and variable levels of browning. The toaster also comes with an auto shut-off functionality. The bread centering feature of the toaster will help in uniform heating. The slide-out crumb tray helps you clean the leftover breadcrumbs from the toaster bed. Make a crunchy toast out of your bread regularly for your breakfast.",
        price: 3999,
    },
    {
        name:"iBELL 130G 2-in-1 Bread Toaster, 4 Slices with Detachable Bun Warmer Grill 230 W Pop Up Toaster  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%202/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%202/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%202/3.png?raw=true",
        info:"1 Year Standard + 6 Months Additional Warranty on FREE Registration",
        description:"1 Year Standard + 6 Months Additional Warranty on FREE Registration",
        price: 3300,
    },
    {
        name:"MORPHY by MORPHY RICHARDS WINDSOR Digital Toaster 2 Slice 800 W Pop Up Toaster  (Glossy Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%203/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%203/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%203/3.png?raw=true",
        info:"2 year warranty on product",
        description:"Morphy Richards Windsor Series Digital 2 Slice 800W Pop Up Toaster|8-Browning Levels|Reheat&Defrost|Wide Bread Slots|Bun Warmer|Dust Cover|Removable Crumb Tray|2-Yr Warranty By Brand|Black,800 Watts",
        price: 3360,
    },
    {
        name:"KENT Crisp Pop Up 750 W Pop Up Toaster  (Blue)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%204/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%204/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%204/Screenshot%202024-04-11%20153048.png?raw=true",
        info:"24 months warranty",
        description:"Good quality product. It comes in various range & variety and hence fulfills the need of all.",
        price: 1099,
    },
    {
        name:"BAJAJ by BAJAJ ATX3 750 W Pop Up Toaster  (Silver and black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%205/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%205/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%205/3.png?raw=true",
        info:" 2 Year Warranty on Product",
        description:"HELPS IN SELECTING DESIRED LEVEL OF BROWNING CANCEL/STOP BUTTON HELPS TO CANCEL THE CYCLE",
        price: 1749,
    },
    {
        name:"PHILIPS HD2582/00 830 W Pop Up Toaster  (White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%206/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%206/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%206/3.png?raw=true",
        info:"2 Years Warranty by Philips",
        description:"The Philips HD2582 830 W Pop Up Toaster is a compact toaster which gives you good toast every time. It has two bread slots with variable width for the bread slots and browning control. This allows you to enjoy your toast exactly the way you want it.",
        price: 1929,
    },
    {
        name:"royalry by ROYALRY CRISP AUTOMATIC 750 W Pop Up Toaster  (Red)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%207/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%207/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%207/3.png?raw=true",
        info:" 6 MONTHS Limited Domestic Brand Warranty",
        description:"Model CRISP AUTOMATIC Type AUTO POP UP TOASTER",
        price: 1139,
    },
    {
        name:"PHILIPS HD2582/90 830 W Pop Up Toaster  (Black)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%208/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%208/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%208/3.png?raw=true",
        info:"2 Years Manufacturer Defect",
        description:"This compact toaster comes with 8 settings and 2 large variable slots, so you can have even toasting result regardless of different bread types. The integrated bun rack also allows you to warm your favorite buns, pastries and rolls easily.",
        price: 2795,
    },
    {
        name:"Morphy Richards pop toaster 1450 W Pop Up Toaster  (White)",
        image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%209/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%209/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%209/3.png?raw=true",
        info:"2 YEAR company damage product",
        description:"Morphy Richards AT 402 4 Slice Pop Up Toaster 1450 W power for quick toasting 4 slice toaster with wider slots: Allows thick thin size breads to be toasted. 4 Slice slots lets you toast multiple bread at a time. Convenient Time-Saving.",
        price: 2599,
    },
    {
        name:"The Better Home FUMATO 1000-Watt 2 Slice Pop-up Toastmate, Dust Cover & Slide Out Crumb Tray 1000 W Pop Up Toaster  (Pink)",
         image1:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%2010/1.png?raw=true",
        image2:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%2010/2.png?raw=true",
        image3:"https://github.com/Amarendra-sahoo-mca/MajorProject-GITA/blob/main/images/KITCHEN%20APPLIANCES/Toaster/Toaster%2010/3.png?raw=true",
        info:"1 year warranty from date of purchase",
        description:"Introducing Fumato, The Better Home premium home appliance sub-brand that takes your home living experience to the next level. Toastmate 1000 Watt 2-Slice Pop-up Toaster, a versatile kitchen appliance that combines functionality and convenience. With its dust cover and slide-out crumb tray, cleaning up after toasting is a breeze.",
        price:2919,
    },
];
module.exports = { data: tosterData};


